# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]: off.}
import wayland/native/client
import wayland/native/common
import protocols/river/client as river_client
import code
export code

## The river_layer_shell_v1 CLIENT protocol
## ########################################
## 
## Interfaces
## ==========
## 
## * river_layer_shell_v1
## * river_layer_shell_output_v1
## * river_layer_shell_seat_v1
## 
## Copyright
## =========
## 
## SPDX-FileCopyrightText: © 2025 Isaac Freund
## SPDX-License-Identifier: MIT
## 
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to
## deal in the Software without restriction, including without limitation the
## rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
## sell copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
## 
## The above copyright notice and this permission notice shall be included in
## all copies or substantial portions of the Software.
## 
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
## IN THE SOFTWARE.
## 

proc setUserData*(
    riverLayerShellV1: ptr RiverLayerShellV1, userData: pointer
) {.inline.} =
  cast[ptr Proxy](riverLayerShellV1).set_user_data(user_data)

proc getUserData*(riverLayerShellV1: ptr RiverLayerShellV1): pointer {.inline.} =
  cast[ptr Proxy](riverLayerShellV1).get_user_data()

proc getVersion*(riverLayerShellV1: ptr RiverLayerShellV1): uint32 {.inline.} =
  cast[ptr Proxy](riverLayerShellV1).get_version()

proc destroy*(riverLayerShellV1: ptr RiverLayerShellV1) {.inline.} =
  ## destroy the river_layer_shell_v1 object
  ## 
  ## This request indicates that the client will no longer use the
  ## river_layer_shell_v1 object.
  ## 
  cast[ptr Proxy](riverLayerShellV1).marshal_flags(
    RiverLayerShellV1Request_destroy.ord,
    nil,
    cast[ptr Proxy](riverLayerShellV1).get_version(),
    WL_MARSHAL_FLAG_DESTROY,
  )

proc getOutput*(
    riverLayerShellV1: ptr RiverLayerShellV1, output: ptr RiverOutputV1
): ptr RiverLayerShellOutputV1 {.inline.} =
  ## get layer shell output state
  ## 
  ## It is a protocol error to make this request more than once for a given
  ## river_output_v1 object.
  ## 
  cast[ptr RiverLayerShellOutputV1](cast[ptr Proxy](riverLayerShellV1).marshal_flags(
    RiverLayerShellV1Request_get_output.ord,
    addr river_layer_shell_output_v1_interface,
    cast[ptr Proxy](riverLayerShellV1).get_version(),
    0,
    nil,
    output,
  ))

proc getSeat*(
    riverLayerShellV1: ptr RiverLayerShellV1, seat: ptr RiverSeatV1
): ptr RiverLayerShellSeatV1 {.inline.} =
  ## get layer shell seat state
  ## 
  ## It is a protocol error to make this request more than once for a given
  ## river_seat_v1 object.
  ## 
  cast[ptr RiverLayerShellSeatV1](cast[ptr Proxy](riverLayerShellV1).marshal_flags(
    RiverLayerShellV1Request_get_seat.ord,
    addr river_layer_shell_seat_v1_interface,
    cast[ptr Proxy](riverLayerShellV1).get_version(),
    0,
    nil,
    seat,
  ))

type RiverLayerShellOutputV1Listener* = object
  nonExclusiveArea*: proc(
    data: pointer,
    riverLayerShellOutputV1: ptr RiverLayerShellOutputV1,
    x: int32,
    y: int32,
    width: int32,
    height: int32,
  ) {.nimcall.}

proc addListener*(
    riverLayerShellOutputV1: ptr RiverLayerShellOutputV1,
    listener: ptr RiverLayerShellOutputV1Listener,
    data: pointer,
): int {.inline.} =
  cast[ptr Proxy](riverLayerShellOutputV1).add_listener(listener, data)

proc setUserData*(
    riverLayerShellOutputV1: ptr RiverLayerShellOutputV1, userData: pointer
) {.inline.} =
  cast[ptr Proxy](riverLayerShellOutputV1).set_user_data(user_data)

proc getUserData*(
    riverLayerShellOutputV1: ptr RiverLayerShellOutputV1
): pointer {.inline.} =
  cast[ptr Proxy](riverLayerShellOutputV1).get_user_data()

proc getVersion*(
    riverLayerShellOutputV1: ptr RiverLayerShellOutputV1
): uint32 {.inline.} =
  cast[ptr Proxy](riverLayerShellOutputV1).get_version()

proc destroy*(riverLayerShellOutputV1: ptr RiverLayerShellOutputV1) {.inline.} =
  ## destroy the object
  ## 
  ## This request indicates that the client will no longer use the
  ## river_layer_shell_output_v1 object and that it may be safely destroyed.
  ## 
  ## This request should be made after the river_output_v1.removed event is
  ## received to complete destruction of the output.
  ## 
  cast[ptr Proxy](riverLayerShellOutputV1).marshal_flags(
    RiverLayerShellOutputV1Request_destroy.ord,
    nil,
    cast[ptr Proxy](riverLayerShellOutputV1).get_version(),
    WL_MARSHAL_FLAG_DESTROY,
  )

proc setDefault*(riverLayerShellOutputV1: ptr RiverLayerShellOutputV1) {.inline.} =
  ## Set default output for layer surfaces
  ## 
  ## Mark this output as the default for new layer surfaces which do not
  ## request a specific output themselves. This request overrides any
  ## previous set_default request on any river_layer_shell_output_v1 object.
  ## 
  ## If no set_default request is made or if the default output is destroyed,
  ## the default output is undefined until the next set_default request.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverLayerShellOutputV1).marshal_flags(
    RiverLayerShellOutputV1Request_set_default.ord,
    nil,
    cast[ptr Proxy](riverLayerShellOutputV1).get_version(),
    0,
  )

type RiverLayerShellSeatV1Listener* = object
  focusExclusive*:
    proc(data: pointer, riverLayerShellSeatV1: ptr RiverLayerShellSeatV1) {.nimcall.}
  focusNonExclusive*:
    proc(data: pointer, riverLayerShellSeatV1: ptr RiverLayerShellSeatV1) {.nimcall.}
  focusNone*:
    proc(data: pointer, riverLayerShellSeatV1: ptr RiverLayerShellSeatV1) {.nimcall.}

proc addListener*(
    riverLayerShellSeatV1: ptr RiverLayerShellSeatV1,
    listener: ptr RiverLayerShellSeatV1Listener,
    data: pointer,
): int {.inline.} =
  cast[ptr Proxy](riverLayerShellSeatV1).add_listener(listener, data)

proc setUserData*(
    riverLayerShellSeatV1: ptr RiverLayerShellSeatV1, userData: pointer
) {.inline.} =
  cast[ptr Proxy](riverLayerShellSeatV1).set_user_data(user_data)

proc getUserData*(
    riverLayerShellSeatV1: ptr RiverLayerShellSeatV1
): pointer {.inline.} =
  cast[ptr Proxy](riverLayerShellSeatV1).get_user_data()

proc getVersion*(riverLayerShellSeatV1: ptr RiverLayerShellSeatV1): uint32 {.inline.} =
  cast[ptr Proxy](riverLayerShellSeatV1).get_version()

proc destroy*(riverLayerShellSeatV1: ptr RiverLayerShellSeatV1) {.inline.} =
  ## destroy the object
  ## 
  ## This request indicates that the client will no longer use the
  ## river_layer_shell_seat_v1 object and that it may be safely destroyed.
  ## 
  ## This request should be made after the river_seat_v1.removed event is
  ## received to complete destruction of the seat.
  ## 
  cast[ptr Proxy](riverLayerShellSeatV1).marshal_flags(
    RiverLayerShellSeatV1Request_destroy.ord,
    nil,
    cast[ptr Proxy](riverLayerShellSeatV1).get_version(),
    WL_MARSHAL_FLAG_DESTROY,
  )
