# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]: off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code
import protocols/river/code as river_code

var riverLayerShellV1_types: array[8, ptr Interface]
type RiverLayerShellOutputV1* = object
type RiverLayerShellSeatV1* = object
type RiverLayerShellV1* = object

let
  river_layer_shell_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr river_layer_shell_v1_types[0]),
    Message(
      name: "get_output", signature: "no", types: addr river_layer_shell_v1_types[4]
    ),
    Message(
      name: "get_seat", signature: "no", types: addr river_layer_shell_v1_types[6]
    ),
  ]

  river_layer_shell_v1_interface* {.exportc.} = Interface(
    name: "river_layer_shell_v1",
    version: 1,
    method_count: 3,
    methods: addr river_layer_shell_v1_requests[0],
  )

  river_layer_shell_output_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr river_layer_shell_v1_types[0]),
    Message(
      name: "set_default", signature: "", types: addr river_layer_shell_v1_types[0]
    ),
  ]

  river_layer_shell_output_v1_events {.exportc.} = [
    Message(
      name: "non_exclusive_area",
      signature: "iiii",
      types: addr river_layer_shell_v1_types[0],
    )
  ]

  river_layer_shell_output_v1_interface* {.exportc.} = Interface(
    name: "river_layer_shell_output_v1",
    version: 1,
    method_count: 2,
    methods: addr river_layer_shell_output_v1_requests[0],
    event_count: 1,
    events: addr river_layer_shell_output_v1_events[0],
  )

  river_layer_shell_seat_v1_requests {.exportc.} =
    [Message(name: "destroy", signature: "", types: addr river_layer_shell_v1_types[0])]

  river_layer_shell_seat_v1_events {.exportc.} = [
    Message(
      name: "focus_exclusive", signature: "", types: addr river_layer_shell_v1_types[0]
    ),
    Message(
      name: "focus_non_exclusive",
      signature: "",
      types: addr river_layer_shell_v1_types[0],
    ),
    Message(
      name: "focus_none", signature: "", types: addr river_layer_shell_v1_types[0]
    ),
  ]

  river_layer_shell_seat_v1_interface* {.exportc.} = Interface(
    name: "river_layer_shell_seat_v1",
    version: 1,
    method_count: 1,
    methods: addr river_layer_shell_seat_v1_requests[0],
    event_count: 3,
    events: addr river_layer_shell_seat_v1_events[0],
  )

type RiverLayerShellV1Error* {.size: sizeof(uint32).} = enum
  error_object_already_created = 0

func since*(e: RiverLayerShellV1Error): int =
  case e
  of error_object_already_created: 1
proc isValid*(e: RiverLayerShellV1Error, version: int): bool =
  version >= e.since

type RiverLayerShellV1Request* {.size: sizeof(uint32).} = enum
  RiverLayerShellV1Request_destroy
  RiverLayerShellV1Request_get_output
  RiverLayerShellV1Request_get_seat

proc since*(e: RiverLayerShellV1Request): int =
  case e
  of RiverLayerShellV1Request_destroy: 1
  of RiverLayerShellV1Request_get_output: 1
  of RiverLayerShellV1Request_get_seat: 1

type RiverLayerShellOutputV1Event* {.size: sizeof(uint32).} = enum
  RiverLayerShellOutputV1Event_non_exclusive_area

proc since*(e: RiverLayerShellOutputV1Event): int =
  case e
  of RiverLayerShellOutputV1Event_non_exclusive_area: 1

type RiverLayerShellOutputV1Request* {.size: sizeof(uint32).} = enum
  RiverLayerShellOutputV1Request_destroy
  RiverLayerShellOutputV1Request_set_default

proc since*(e: RiverLayerShellOutputV1Request): int =
  case e
  of RiverLayerShellOutputV1Request_destroy: 1
  of RiverLayerShellOutputV1Request_set_default: 1

type RiverLayerShellSeatV1Event* {.size: sizeof(uint32).} = enum
  RiverLayerShellSeatV1Event_focus_exclusive
  RiverLayerShellSeatV1Event_focus_non_exclusive
  RiverLayerShellSeatV1Event_focus_none

proc since*(e: RiverLayerShellSeatV1Event): int =
  case e
  of RiverLayerShellSeatV1Event_focus_exclusive: 1
  of RiverLayerShellSeatV1Event_focus_non_exclusive: 1
  of RiverLayerShellSeatV1Event_focus_none: 1

type RiverLayerShellSeatV1Request* {.size: sizeof(uint32).} = enum
  RiverLayerShellSeatV1Request_destroy

proc since*(e: RiverLayerShellSeatV1Request): int =
  case e
  of RiverLayerShellSeatV1Request_destroy: 1

riverLayerShellV1_types = [
  nil,
  nil,
  nil,
  nil,
  addr river_layer_shell_output_v1_interface,
  addr river_output_v1_interface,
  addr river_layer_shell_seat_v1_interface,
  addr river_seat_v1_interface,
]
