# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]: off.}
import wayland/native/server
import wayland/native/common
import protocols/river/server as river_server
import code
export code

## The river_layer_shell_v1 SERVER protocol
## ########################################
## 
## Interfaces
## ==========
## 
## * river_layer_shell_v1
## * river_layer_shell_output_v1
## * river_layer_shell_seat_v1
## 
## Copyright
## =========
## 
## SPDX-FileCopyrightText: © 2025 Isaac Freund
## SPDX-License-Identifier: MIT
## 
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to
## deal in the Software without restriction, including without limitation the
## rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
## sell copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
## 
## The above copyright notice and this permission notice shall be included in
## all copies or substantial portions of the Software.
## 
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
## IN THE SOFTWARE.
## 

type RiverLayerShellV1Interface* = object
  destroy*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  getOutput*: proc(
    client: ptr Client, resource: ptr Resource, id: uint32, output: ptr Resource
  ) {.nimcall.}
  getSeat*: proc(
    client: ptr Client, resource: ptr Resource, id: uint32, seat: ptr Resource
  ) {.nimcall.}

type RiverLayerShellOutputV1Interface* = object
  destroy*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  setDefault*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}

proc riverLayerShellOutputV1SendNonExclusiveArea*(
    resource: ptr Resource, x: int32, y: int32, width: int32, height: int32
) {.inline, exportc: "river_layer_shell_output_v1_send_non_exclusive_area".} =
  ## Sends an non_exclusive_area event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *x*: global x coordinate
  ## * *y*: global y coordinate
  ## * *width*: area width
  ## * *height*: area height
  resource.post_event(
    RiverLayerShellOutputV1Event_non_exclusive_area.ord, x, y, width, height
  )

type RiverLayerShellSeatV1Interface* = object
  destroy*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}

proc riverLayerShellSeatV1SendFocusExclusive*(
    resource: ptr Resource
) {.inline, exportc: "river_layer_shell_seat_v1_send_focus_exclusive".} =
  ## Sends an focus_exclusive event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLayerShellSeatV1Event_focus_exclusive.ord)

proc riverLayerShellSeatV1SendFocusNonExclusive*(
    resource: ptr Resource
) {.inline, exportc: "river_layer_shell_seat_v1_send_focus_non_exclusive".} =
  ## Sends an focus_non_exclusive event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLayerShellSeatV1Event_focus_non_exclusive.ord)

proc riverLayerShellSeatV1SendFocusNone*(
    resource: ptr Resource
) {.inline, exportc: "river_layer_shell_seat_v1_send_focus_none".} =
  ## Sends an focus_none event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLayerShellSeatV1Event_focus_none.ord)
