import os, posix, strutils, tables
import ../core/app_identity

type
  ShellOverlayResult* = object
    rootPath*: string
    sharePath*: string
    ok*: bool
    warning*: string

const GenericTerminalSvg = """<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">
  <rect x="6" y="10" width="52" height="44" rx="7" fill="#1f2933"/>
  <rect x="9" y="13" width="46" height="38" rx="5" fill="#111827"/>
  <path d="M18 25l8 7-8 7" fill="none" stroke="#8bd5ff" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M31 40h15" fill="none" stroke="#d9e2ec" stroke-width="5" stroke-linecap="round"/>
</svg>
"""

proc defaultRuntimeDir(): string =
  getEnv("XDG_RUNTIME_DIR", "/tmp")

func stripDesktopSuffix(value: string): string =
  if value.toLowerAscii().endsWith(".desktop"):
    value[0 ..< value.len - ".desktop".len]
  else:
    value

func canonicalDesktopId(id: string): string =
  id.strip().toLowerAscii()

func iconAliasName(entry: DesktopEntry): string =
  let base = entry.id.stripDesktopSuffix().toLowerAscii()
  result = "triad-"
  var previousDash = false
  for ch in base:
    if ch.isAlphaNumeric():
      result.add(ch)
      previousDash = false
    elif not previousDash:
      result.add('-')
      previousDash = true
  while result.endsWith("-"):
    result.setLen(result.len - 1)
  if result == "triad":
    result = "triad-terminal"

proc xdgShareDirs(): seq[string] =
  let dataHome = getEnv("XDG_DATA_HOME", getHomeDir() / ".local" / "share")
  result.add(dataHome)

  let dataDirs = getEnv("XDG_DATA_DIRS", "/usr/local/share:/usr/share")
  for dir in dataDirs.split(PathSep):
    let trimmed = dir.strip()
    if trimmed.len > 0:
      result.add(trimmed)

proc iconCandidates(shareDir, iconName: string): seq[string] =
  let names =
    if iconName.toLowerAscii() == iconName:
      @[iconName]
    else:
      @[iconName, iconName.toLowerAscii()]

  for name in names:
    for size in ["512x512", "256x256", "128x128", "64x64", "48x48", "32x32"]:
      result.add(shareDir / "icons" / "hicolor" / size / "apps" / (name & ".png"))
    result.add(shareDir / "icons" / "hicolor" / "scalable" / "apps" / (name & ".svg"))
    result.add(shareDir / "pixmaps" / (name & ".png"))
    result.add(shareDir / "pixmaps" / (name & ".svg"))

proc findIconSource(iconNames: openArray[string]): string =
  for iconName in iconNames:
    if iconName.startsWith(DirSep) and fileExists(iconName):
      return iconName

  for shareDir in xdgShareDirs():
    for iconName in iconNames:
      if iconName.len == 0 or iconName.startsWith(DirSep):
        continue
      for candidate in iconCandidates(shareDir, iconName):
        if fileExists(candidate):
          return candidate
  ""

proc copyOrLinkIcon(sourcePath, destPath: string) =
  if fileExists(destPath):
    removeFile(destPath)

  when defined(posix):
    if symlink(sourcePath, destPath) == 0:
      return

  copyFile(sourcePath, destPath)

proc writeIconAlias(rootPath: string; entry: DesktopEntry) =
  let source = findIconSource([
    entry.icon,
    entry.id.stripDesktopSuffix(),
    entry.id.stripDesktopSuffix().toLowerAscii()
  ])
  let iconName = entry.iconAliasName()

  if source.len > 0:
    let ext = source.splitFile().ext.toLowerAscii()
    if ext == ".png":
      let destDir = rootPath / "share" / "icons" / "hicolor" / "48x48" / "apps"
      createDir(destDir)
      copyOrLinkIcon(source, destDir / (iconName & ".png"))
      return
    if ext == ".svg":
      let destDir = rootPath / "share" / "icons" / "hicolor" / "scalable" / "apps"
      createDir(destDir)
      copyOrLinkIcon(source, destDir / (iconName & ".svg"))
      return

  let destDir = rootPath / "share" / "icons" / "hicolor" / "scalable" / "apps"
  createDir(destDir)
  writeFile(destDir / (iconName & ".svg"), GenericTerminalSvg)

func desktopEntryText(entry: DesktopEntry): string =
  let desktopId = entry.id.canonicalDesktopId()
  let name = if entry.name.len > 0: entry.name else: entry.id.stripDesktopSuffix()
  let execLine = if entry.execLine.len > 0: entry.execLine else: entry.execBase
  let categories =
    if entry.categories.len > 0: entry.categories.join(";") & ";"
    else: "System;TerminalEmulator;"

  "[Desktop Entry]\n" &
  "Type=Application\n" &
  "Name=" & name & "\n" &
  "GenericName=Terminal\n" &
  "Comment=Terminal emulator\n" &
  "Exec=" & execLine & "\n" &
  "Icon=" & entry.iconAliasName() & "\n" &
  "Terminal=false\n" &
  "Categories=" & categories & "\n" &
  "X-Triad-SourceDesktopId=" & desktopId & "\n"

proc writeIconThemeIndex(rootPath: string) =
  let themeDir = rootPath / "share" / "icons" / "hicolor"
  createDir(themeDir)
  writeFile(themeDir / "index.theme", """
[Icon Theme]
Name=Triad Shell Compatibility
Comment=Runtime icon aliases generated by Triad
Directories=scalable/apps,48x48/apps

[scalable/apps]
Size=48
MinSize=16
MaxSize=256
Type=Scalable
Context=Applications

[48x48/apps]
Size=48
Type=Fixed
Context=Applications
""")

proc terminalEntries(index: AppIdentityIndex): seq[DesktopEntry] =
  var seen = initTable[string, bool]()
  for entry in index.desktopEntries:
    if not entry.isTerminalEntry:
      continue
    let id = entry.id.canonicalDesktopId()
    if id.len == 0 or seen.hasKey(id):
      continue
    seen[id] = true
    result.add(entry)

proc installShellOverlay*(
    runtimeDir = defaultRuntimeDir();
    index = defaultAppIdentityIndex()
  ): ShellOverlayResult =
  result.rootPath = runtimeDir / "triad-shell-compat"
  result.sharePath = result.rootPath / "share"

  try:
    if dirExists(result.rootPath):
      removeDir(result.rootPath)

    let applicationsDir = result.sharePath / "applications"
    createDir(applicationsDir)
    writeIconThemeIndex(result.rootPath)

    for entry in terminalEntries(index):
      writeFile(applicationsDir / entry.id.canonicalDesktopId(), desktopEntryText(entry))
      writeIconAlias(result.rootPath, entry)

    result.ok = true
  except CatchableError as e:
    result.ok = false
    result.warning = "failed to install shell compatibility overlay: " & e.msg
