# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/client
import wayland/native/common
import protocols/river_input_management/client as river_input_management_client
import code
export code

## The river_xkb_config_v1 CLIENT protocol
## #######################################
## 
## Interfaces
## ==========
## 
## * river_xkb_config_v1
## * river_xkb_keymap_v1
## * river_xkb_keyboard_v1
## 
## Copyright
## =========
## 
## SPDX-FileCopyrightText: © 2026 Isaac Freund
## SPDX-License-Identifier: MIT
## 
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to
## deal in the Software without restriction, including without limitation the
## rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
## sell copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
## 
## The above copyright notice and this permission notice shall be included in
## all copies or substantial portions of the Software.
## 
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
## IN THE SOFTWARE.
## 

type RiverXkbConfigV1Listener* = object
  finished*: proc(
    data: pointer;
    riverXkbConfigV1: ptr RiverXkbConfigV1;
  ) {.nimcall.}
  xkbKeyboard*: proc(
    data: pointer;
    riverXkbConfigV1: ptr RiverXkbConfigV1;
    id: ptr RiverXkbKeyboardV1;
  ) {.nimcall.}
proc addListener*(riverXkbConfigV1: ptr RiverXkbConfigV1; listener: ptr RiverXkbConfigV1Listener; data: pointer): int {.inline.} =
  cast[ptr Proxy](riverXkbConfigV1).add_listener(listener, data)

proc setUserData*(riverXkbConfigV1: ptr RiverXkbConfigV1; userData: pointer) {.inline.} =
  cast[ptr Proxy](riverXkbConfigV1).set_user_data(user_data)
proc getUserData*(riverXkbConfigV1: ptr RiverXkbConfigV1): pointer {.inline.} =
  cast[ptr Proxy](riverXkbConfigV1).get_user_data()
proc getVersion*(riverXkbConfigV1: ptr RiverXkbConfigV1): uint32 {.inline.} =
  cast[ptr Proxy](riverXkbConfigV1).get_version()
proc stop*(riverXkbConfigV1: ptr RiverXkbConfigV1) {.inline.} =
  ## stop sending events
  ## 
  ## This request indicates that the client no longer wishes to receive
  ## events on this object.
  ## 
  ## The Wayland protocol is asynchronous, which means the server may send
  ## further events until the stop request is processed. The client must wait
  ## for a river_xkb_config_v1.finished event before destroying this object.
  ## 
  cast[ptr Proxy](riverXkbConfigV1).marshal_flags(RiverXkbConfigV1Request_stop.ord, nil, cast[ptr Proxy](riverXkbConfigV1).get_version(), 0)
proc destroy*(riverXkbConfigV1: ptr RiverXkbConfigV1) {.inline.} =
  ## destroy the river_xkb_config_v1 object
  ## 
  ## This request should be called after the finished event has been received
  ## to complete destruction of the object.
  ## 
  ## It is a protocol error to make this request before the finished event
  ## has been received.
  ## 
  ## If a client wishes to destroy this object it should send a
  ## river_xkb_config_v1.stop request and wait for a
  ## river_xkb_config_v1.finished event. Once the finished event is received
  ## it is safe to destroy this object and any other objects created through
  ## this interface.
  ## 
  cast[ptr Proxy](riverXkbConfigV1).marshal_flags(RiverXkbConfigV1Request_destroy.ord, nil, cast[ptr Proxy](riverXkbConfigV1).get_version(), WL_MARSHAL_FLAG_DESTROY)
proc createKeymap*(riverXkbConfigV1: ptr RiverXkbConfigV1; fd: int32; format: uint32): ptr RiverXkbKeymapV1 {.inline.} =
  ## create a keymap object
  ## 
  ## The server must be able to mmap the fd with MAP_PRIVATE.
  ## The server will fstat the fd to obtain the size of the keymap.
  ## The client must not modify the contents of the fd after making this request.
  ## The client should seal the fd with fcntl.
  ## 
  cast[ptr RiverXkbKeymapV1](cast[ptr Proxy](riverXkbConfigV1).marshal_flags(RiverXkbConfigV1Request_create_keymap.ord, addr river_xkb_keymap_v1_interface, cast[ptr Proxy](riverXkbConfigV1).get_version(), 0, nil, fd, format))
type RiverXkbKeymapV1Listener* = object
  success*: proc(
    data: pointer;
    riverXkbKeymapV1: ptr RiverXkbKeymapV1;
  ) {.nimcall.}
  failure*: proc(
    data: pointer;
    riverXkbKeymapV1: ptr RiverXkbKeymapV1;
    errorMsg: cstring;
  ) {.nimcall.}
proc addListener*(riverXkbKeymapV1: ptr RiverXkbKeymapV1; listener: ptr RiverXkbKeymapV1Listener; data: pointer): int {.inline.} =
  cast[ptr Proxy](riverXkbKeymapV1).add_listener(listener, data)

proc setUserData*(riverXkbKeymapV1: ptr RiverXkbKeymapV1; userData: pointer) {.inline.} =
  cast[ptr Proxy](riverXkbKeymapV1).set_user_data(user_data)
proc getUserData*(riverXkbKeymapV1: ptr RiverXkbKeymapV1): pointer {.inline.} =
  cast[ptr Proxy](riverXkbKeymapV1).get_user_data()
proc getVersion*(riverXkbKeymapV1: ptr RiverXkbKeymapV1): uint32 {.inline.} =
  cast[ptr Proxy](riverXkbKeymapV1).get_version()
proc destroy*(riverXkbKeymapV1: ptr RiverXkbKeymapV1) {.inline.} =
  ## destroy the keymap object
  ## 
  ## This request indicates that the client will no longer use the keymap
  ## object and that it may be safely destroyed.
  ## 
  cast[ptr Proxy](riverXkbKeymapV1).marshal_flags(RiverXkbKeymapV1Request_destroy.ord, nil, cast[ptr Proxy](riverXkbKeymapV1).get_version(), WL_MARSHAL_FLAG_DESTROY)
type RiverXkbKeyboardV1Listener* = object
  removed*: proc(
    data: pointer;
    riverXkbKeyboardV1: ptr RiverXkbKeyboardV1;
  ) {.nimcall.}
  inputDevice*: proc(
    data: pointer;
    riverXkbKeyboardV1: ptr RiverXkbKeyboardV1;
    device: ptr RiverInputDeviceV1;
  ) {.nimcall.}
  layout*: proc(
    data: pointer;
    riverXkbKeyboardV1: ptr RiverXkbKeyboardV1;
    index: uint32;
    name: cstring;
  ) {.nimcall.}
  capslockEnabled*: proc(
    data: pointer;
    riverXkbKeyboardV1: ptr RiverXkbKeyboardV1;
  ) {.nimcall.}
  capslockDisabled*: proc(
    data: pointer;
    riverXkbKeyboardV1: ptr RiverXkbKeyboardV1;
  ) {.nimcall.}
  numlockEnabled*: proc(
    data: pointer;
    riverXkbKeyboardV1: ptr RiverXkbKeyboardV1;
  ) {.nimcall.}
  numlockDisabled*: proc(
    data: pointer;
    riverXkbKeyboardV1: ptr RiverXkbKeyboardV1;
  ) {.nimcall.}
  done*: proc(
    data: pointer;
    riverXkbKeyboardV1: ptr RiverXkbKeyboardV1;
  ) {.nimcall.}
proc addListener*(riverXkbKeyboardV1: ptr RiverXkbKeyboardV1; listener: ptr RiverXkbKeyboardV1Listener; data: pointer): int {.inline.} =
  cast[ptr Proxy](riverXkbKeyboardV1).add_listener(listener, data)

proc setUserData*(riverXkbKeyboardV1: ptr RiverXkbKeyboardV1; userData: pointer) {.inline.} =
  cast[ptr Proxy](riverXkbKeyboardV1).set_user_data(user_data)
proc getUserData*(riverXkbKeyboardV1: ptr RiverXkbKeyboardV1): pointer {.inline.} =
  cast[ptr Proxy](riverXkbKeyboardV1).get_user_data()
proc getVersion*(riverXkbKeyboardV1: ptr RiverXkbKeyboardV1): uint32 {.inline.} =
  cast[ptr Proxy](riverXkbKeyboardV1).get_version()
proc destroy*(riverXkbKeyboardV1: ptr RiverXkbKeyboardV1) {.inline.} =
  ## destroy the xkb keyboard object
  ## 
  ## This request indicates that the client will no longer use the keyboard
  ## object and that it may be safely destroyed.
  ## 
  cast[ptr Proxy](riverXkbKeyboardV1).marshal_flags(RiverXkbKeyboardV1Request_destroy.ord, nil, cast[ptr Proxy](riverXkbKeyboardV1).get_version(), WL_MARSHAL_FLAG_DESTROY)
proc setKeymap*(riverXkbKeyboardV1: ptr RiverXkbKeyboardV1; keymap: ptr RiverXkbKeymapV1) {.inline.} =
  ## set the keymap
  ## 
  ## Set the keymap for the keyboard.
  ## 
  ## Setting a keymap will reset all layout/modifier state.
  ## 
  ## It is a protocol error to pass a keymap object for which the
  ## river_xkb_keymap_v1.success event was not received.
  ## 
  cast[ptr Proxy](riverXkbKeyboardV1).marshal_flags(RiverXkbKeyboardV1Request_set_keymap.ord, nil, cast[ptr Proxy](riverXkbKeyboardV1).get_version(), 0, keymap)
proc setLayoutByIndex*(riverXkbKeyboardV1: ptr RiverXkbKeyboardV1; index: int32) {.inline.} =
  ## set the active layout by index
  ## 
  ## Set the active layout for the keyboard's keymap. Has no effect if the
  ## layout index is out of bounds for the current keymap.
  ## 
  cast[ptr Proxy](riverXkbKeyboardV1).marshal_flags(RiverXkbKeyboardV1Request_set_layout_by_index.ord, nil, cast[ptr Proxy](riverXkbKeyboardV1).get_version(), 0, index)
proc setLayoutByName*(riverXkbKeyboardV1: ptr RiverXkbKeyboardV1; name: cstring) {.inline.} =
  ## set the active layout by name
  ## 
  ## Set the active layout for the keyboard's keymap. Has no effect if there
  ## is no layout with the give name for the keyboard's keymap.
  ## 
  cast[ptr Proxy](riverXkbKeyboardV1).marshal_flags(RiverXkbKeyboardV1Request_set_layout_by_name.ord, nil, cast[ptr Proxy](riverXkbKeyboardV1).get_version(), 0, name)
proc capslockEnable*(riverXkbKeyboardV1: ptr RiverXkbKeyboardV1) {.inline.} =
  ## enable capslock
  ## 
  ## Enable capslock for the keyboard.
  ## 
  cast[ptr Proxy](riverXkbKeyboardV1).marshal_flags(RiverXkbKeyboardV1Request_capslock_enable.ord, nil, cast[ptr Proxy](riverXkbKeyboardV1).get_version(), 0)
proc capslockDisable*(riverXkbKeyboardV1: ptr RiverXkbKeyboardV1) {.inline.} =
  ## disable capslock
  ## 
  ## Disable capslock for the keyboard.
  ## 
  cast[ptr Proxy](riverXkbKeyboardV1).marshal_flags(RiverXkbKeyboardV1Request_capslock_disable.ord, nil, cast[ptr Proxy](riverXkbKeyboardV1).get_version(), 0)
proc numlockEnable*(riverXkbKeyboardV1: ptr RiverXkbKeyboardV1) {.inline.} =
  ## enable numlock
  ## 
  ## Enable numlock for the keyboard.
  ## 
  cast[ptr Proxy](riverXkbKeyboardV1).marshal_flags(RiverXkbKeyboardV1Request_numlock_enable.ord, nil, cast[ptr Proxy](riverXkbKeyboardV1).get_version(), 0)
proc numlockDisable*(riverXkbKeyboardV1: ptr RiverXkbKeyboardV1) {.inline.} =
  ## disable numlock
  ## 
  ## Disable numlock for the keyboard.
  ## 
  cast[ptr Proxy](riverXkbKeyboardV1).marshal_flags(RiverXkbKeyboardV1Request_numlock_disable.ord, nil, cast[ptr Proxy](riverXkbKeyboardV1).get_version(), 0)
