# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code
import protocols/river_input_management/code as river_input_management_code

var riverXkbConfigV1_types: array[8, ptr Interface]
type RiverXkbConfigV1* = object
type RiverXkbKeyboardV1* = object
type RiverXkbKeymapV1* = object

let
  river_xkb_config_v1_requests {.exportc.} = [
    Message(name: "stop", signature: "", types: addr river_xkb_config_v1_types[0]),
    Message(name: "destroy", signature: "", types: addr river_xkb_config_v1_types[0]),
    Message(name: "create_keymap", signature: "nhu", types: addr river_xkb_config_v1_types[2]),
  ]

  river_xkb_config_v1_events {.exportc.} = [
    Message(name: "finished", signature: "", types: addr river_xkb_config_v1_types[0]),
    Message(name: "xkb_keyboard", signature: "n", types: addr river_xkb_config_v1_types[5]),
  ]

  river_xkb_config_v1_interface* {.exportc.} = Interface(
    name: "river_xkb_config_v1",
    version: 2,
    method_count: 3,
    methods: addr river_xkb_config_v1_requests[0],
    event_count: 2,
    events: addr river_xkb_config_v1_events[0],
  )

  river_xkb_keymap_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr river_xkb_config_v1_types[0]),
  ]

  river_xkb_keymap_v1_events {.exportc.} = [
    Message(name: "success", signature: "", types: addr river_xkb_config_v1_types[0]),
    Message(name: "failure", signature: "s", types: addr river_xkb_config_v1_types[0]),
  ]

  river_xkb_keymap_v1_interface* {.exportc.} = Interface(
    name: "river_xkb_keymap_v1",
    version: 2,
    method_count: 1,
    methods: addr river_xkb_keymap_v1_requests[0],
    event_count: 2,
    events: addr river_xkb_keymap_v1_events[0],
  )

  river_xkb_keyboard_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr river_xkb_config_v1_types[0]),
    Message(name: "set_keymap", signature: "o", types: addr river_xkb_config_v1_types[6]),
    Message(name: "set_layout_by_index", signature: "i", types: addr river_xkb_config_v1_types[0]),
    Message(name: "set_layout_by_name", signature: "s", types: addr river_xkb_config_v1_types[0]),
    Message(name: "capslock_enable", signature: "", types: addr river_xkb_config_v1_types[0]),
    Message(name: "capslock_disable", signature: "", types: addr river_xkb_config_v1_types[0]),
    Message(name: "numlock_enable", signature: "", types: addr river_xkb_config_v1_types[0]),
    Message(name: "numlock_disable", signature: "", types: addr river_xkb_config_v1_types[0]),
  ]

  river_xkb_keyboard_v1_events {.exportc.} = [
    Message(name: "removed", signature: "", types: addr river_xkb_config_v1_types[0]),
    Message(name: "input_device", signature: "o", types: addr river_xkb_config_v1_types[7]),
    Message(name: "layout", signature: "u?s", types: addr river_xkb_config_v1_types[0]),
    Message(name: "capslock_enabled", signature: "", types: addr river_xkb_config_v1_types[0]),
    Message(name: "capslock_disabled", signature: "", types: addr river_xkb_config_v1_types[0]),
    Message(name: "numlock_enabled", signature: "", types: addr river_xkb_config_v1_types[0]),
    Message(name: "numlock_disabled", signature: "", types: addr river_xkb_config_v1_types[0]),
    Message(name: "done", signature: "2", types: addr river_xkb_config_v1_types[0]),
  ]

  river_xkb_keyboard_v1_interface* {.exportc.} = Interface(
    name: "river_xkb_keyboard_v1",
    version: 2,
    method_count: 8,
    methods: addr river_xkb_keyboard_v1_requests[0],
    event_count: 8,
    events: addr river_xkb_keyboard_v1_events[0],
  )


type RiverXkbConfigV1Error* {.size: sizeof(uint32).} = enum
  error_invalid_destroy = 0
  error_invalid_format = 1
func since*(e: RiverXkbConfigV1Error): int =
  case e
  of error_invalid_destroy: 1
  of error_invalid_format: 1
proc isValid*(e: RiverXkbConfigV1Error; version: int): bool =
  version >= e.since

type RiverXkbConfigV1KeymapFormat* {.size: sizeof(uint32).} = enum
  keymap_format_text_v1 = 1
  keymap_format_text_v2 = 2
func since*(e: RiverXkbConfigV1KeymapFormat): int =
  case e
  of keymap_format_text_v1: 1
  of keymap_format_text_v2: 1
proc isValid*(e: RiverXkbConfigV1KeymapFormat; version: int): bool =
  version >= e.since

type RiverXkbKeyboardV1Error* {.size: sizeof(uint32).} = enum
  error_invalid_keymap = 0
func since*(e: RiverXkbKeyboardV1Error): int =
  case e
  of error_invalid_keymap: 1
proc isValid*(e: RiverXkbKeyboardV1Error; version: int): bool =
  version >= e.since

type RiverXkbConfigV1Event* {.size: sizeof(uint32).} = enum
  RiverXkbConfigV1Event_finished
  RiverXkbConfigV1Event_xkb_keyboard
proc since*(e: RiverXkbConfigV1Event): int =
  case e
  of RiverXkbConfigV1Event_finished: 1
  of RiverXkbConfigV1Event_xkb_keyboard: 1

type RiverXkbConfigV1Request* {.size: sizeof(uint32).} = enum
  RiverXkbConfigV1Request_stop
  RiverXkbConfigV1Request_destroy
  RiverXkbConfigV1Request_create_keymap
proc since*(e: RiverXkbConfigV1Request): int =
  case e
  of RiverXkbConfigV1Request_stop: 1
  of RiverXkbConfigV1Request_destroy: 1
  of RiverXkbConfigV1Request_create_keymap: 1

type RiverXkbKeymapV1Event* {.size: sizeof(uint32).} = enum
  RiverXkbKeymapV1Event_success
  RiverXkbKeymapV1Event_failure
proc since*(e: RiverXkbKeymapV1Event): int =
  case e
  of RiverXkbKeymapV1Event_success: 1
  of RiverXkbKeymapV1Event_failure: 1

type RiverXkbKeymapV1Request* {.size: sizeof(uint32).} = enum
  RiverXkbKeymapV1Request_destroy
proc since*(e: RiverXkbKeymapV1Request): int =
  case e
  of RiverXkbKeymapV1Request_destroy: 1

type RiverXkbKeyboardV1Event* {.size: sizeof(uint32).} = enum
  RiverXkbKeyboardV1Event_removed
  RiverXkbKeyboardV1Event_input_device
  RiverXkbKeyboardV1Event_layout
  RiverXkbKeyboardV1Event_capslock_enabled
  RiverXkbKeyboardV1Event_capslock_disabled
  RiverXkbKeyboardV1Event_numlock_enabled
  RiverXkbKeyboardV1Event_numlock_disabled
  RiverXkbKeyboardV1Event_done
proc since*(e: RiverXkbKeyboardV1Event): int =
  case e
  of RiverXkbKeyboardV1Event_removed: 1
  of RiverXkbKeyboardV1Event_input_device: 1
  of RiverXkbKeyboardV1Event_layout: 1
  of RiverXkbKeyboardV1Event_capslock_enabled: 1
  of RiverXkbKeyboardV1Event_capslock_disabled: 1
  of RiverXkbKeyboardV1Event_numlock_enabled: 1
  of RiverXkbKeyboardV1Event_numlock_disabled: 1
  of RiverXkbKeyboardV1Event_done: 2

type RiverXkbKeyboardV1Request* {.size: sizeof(uint32).} = enum
  RiverXkbKeyboardV1Request_destroy
  RiverXkbKeyboardV1Request_set_keymap
  RiverXkbKeyboardV1Request_set_layout_by_index
  RiverXkbKeyboardV1Request_set_layout_by_name
  RiverXkbKeyboardV1Request_capslock_enable
  RiverXkbKeyboardV1Request_capslock_disable
  RiverXkbKeyboardV1Request_numlock_enable
  RiverXkbKeyboardV1Request_numlock_disable
proc since*(e: RiverXkbKeyboardV1Request): int =
  case e
  of RiverXkbKeyboardV1Request_destroy: 1
  of RiverXkbKeyboardV1Request_set_keymap: 1
  of RiverXkbKeyboardV1Request_set_layout_by_index: 1
  of RiverXkbKeyboardV1Request_set_layout_by_name: 1
  of RiverXkbKeyboardV1Request_capslock_enable: 1
  of RiverXkbKeyboardV1Request_capslock_disable: 1
  of RiverXkbKeyboardV1Request_numlock_enable: 1
  of RiverXkbKeyboardV1Request_numlock_disable: 1

riverXkbConfigV1_types = [
  nil,
  nil,
  addr river_xkb_keymap_v1_interface,
  nil,
  nil,
  addr river_xkb_keyboard_v1_interface,
  addr river_xkb_keymap_v1_interface,
  addr river_input_device_v1_interface,
]


