# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/server
import wayland/native/common
import protocols/river_input_management/server as river_input_management_server
import code
export code

## The river_xkb_config_v1 SERVER protocol
## #######################################
## 
## Interfaces
## ==========
## 
## * river_xkb_config_v1
## * river_xkb_keymap_v1
## * river_xkb_keyboard_v1
## 
## Copyright
## =========
## 
## SPDX-FileCopyrightText: © 2026 Isaac Freund
## SPDX-License-Identifier: MIT
## 
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to
## deal in the Software without restriction, including without limitation the
## rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
## sell copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
## 
## The above copyright notice and this permission notice shall be included in
## all copies or substantial portions of the Software.
## 
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
## IN THE SOFTWARE.
## 

type RiverXkbConfigV1Interface* = object
  stop*: proc(
    client: ptr Client;
    resource: ptr Resource;
  ) {.nimcall.}
  destroy*: proc(
    client: ptr Client;
    resource: ptr Resource;
  ) {.nimcall.}
  createKeymap*: proc(
    client: ptr Client;
    resource: ptr Resource;
    id: uint32;
    fd: int32;
    format: uint32;
  ) {.nimcall.}

proc riverXkbConfigV1SendFinished*(resource: ptr Resource) {.inline, exportc: "river_xkb_config_v1_send_finished".} =
  ## Sends an finished event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverXkbConfigV1Event_finished.ord)

proc riverXkbConfigV1SendXkbKeyboard*(resource: ptr Resource; id: ptr Resource) {.inline, exportc: "river_xkb_config_v1_send_xkb_keyboard".} =
  ## Sends an xkb_keyboard event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverXkbConfigV1Event_xkb_keyboard.ord, id)

type RiverXkbKeymapV1Interface* = object
  destroy*: proc(
    client: ptr Client;
    resource: ptr Resource;
  ) {.nimcall.}

proc riverXkbKeymapV1SendSuccess*(resource: ptr Resource) {.inline, exportc: "river_xkb_keymap_v1_send_success".} =
  ## Sends an success event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverXkbKeymapV1Event_success.ord)

proc riverXkbKeymapV1SendFailure*(resource: ptr Resource; errorMsg: cstring) {.inline, exportc: "river_xkb_keymap_v1_send_failure".} =
  ## Sends an failure event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverXkbKeymapV1Event_failure.ord, errorMsg)

type RiverXkbKeyboardV1Interface* = object
  destroy*: proc(
    client: ptr Client;
    resource: ptr Resource;
  ) {.nimcall.}
  setKeymap*: proc(
    client: ptr Client;
    resource: ptr Resource;
    keymap: ptr Resource;
  ) {.nimcall.}
  setLayoutByIndex*: proc(
    client: ptr Client;
    resource: ptr Resource;
    index: int32;
  ) {.nimcall.}
  setLayoutByName*: proc(
    client: ptr Client;
    resource: ptr Resource;
    name: cstring;
  ) {.nimcall.}
  capslockEnable*: proc(
    client: ptr Client;
    resource: ptr Resource;
  ) {.nimcall.}
  capslockDisable*: proc(
    client: ptr Client;
    resource: ptr Resource;
  ) {.nimcall.}
  numlockEnable*: proc(
    client: ptr Client;
    resource: ptr Resource;
  ) {.nimcall.}
  numlockDisable*: proc(
    client: ptr Client;
    resource: ptr Resource;
  ) {.nimcall.}

proc riverXkbKeyboardV1SendRemoved*(resource: ptr Resource) {.inline, exportc: "river_xkb_keyboard_v1_send_removed".} =
  ## Sends an removed event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverXkbKeyboardV1Event_removed.ord)

proc riverXkbKeyboardV1SendInputDevice*(resource: ptr Resource; device: ptr Resource) {.inline, exportc: "river_xkb_keyboard_v1_send_input_device".} =
  ## Sends an input_device event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverXkbKeyboardV1Event_input_device.ord, device)

proc riverXkbKeyboardV1SendLayout*(resource: ptr Resource; index: uint32; name: cstring) {.inline, exportc: "river_xkb_keyboard_v1_send_layout".} =
  ## Sends an layout event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverXkbKeyboardV1Event_layout.ord, index, name)

proc riverXkbKeyboardV1SendCapslockEnabled*(resource: ptr Resource) {.inline, exportc: "river_xkb_keyboard_v1_send_capslock_enabled".} =
  ## Sends an capslock_enabled event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverXkbKeyboardV1Event_capslock_enabled.ord)

proc riverXkbKeyboardV1SendCapslockDisabled*(resource: ptr Resource) {.inline, exportc: "river_xkb_keyboard_v1_send_capslock_disabled".} =
  ## Sends an capslock_disabled event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverXkbKeyboardV1Event_capslock_disabled.ord)

proc riverXkbKeyboardV1SendNumlockEnabled*(resource: ptr Resource) {.inline, exportc: "river_xkb_keyboard_v1_send_numlock_enabled".} =
  ## Sends an numlock_enabled event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverXkbKeyboardV1Event_numlock_enabled.ord)

proc riverXkbKeyboardV1SendNumlockDisabled*(resource: ptr Resource) {.inline, exportc: "river_xkb_keyboard_v1_send_numlock_disabled".} =
  ## Sends an numlock_disabled event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverXkbKeyboardV1Event_numlock_disabled.ord)

proc riverXkbKeyboardV1SendDone*(resource: ptr Resource) {.inline, exportc: "river_xkb_keyboard_v1_send_done".} =
  ## Sends an done event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverXkbKeyboardV1Event_done.ord)

