# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/client
import wayland/native/common
import protocols/river_input_management/client as river_input_management_client
import code
export code

## The river_libinput_config_v1 CLIENT protocol
## ############################################
## 
## Interfaces
## ==========
## 
## * river_libinput_config_v1
## * river_libinput_device_v1
## * river_libinput_accel_config_v1
## * river_libinput_result_v1
## 
## Copyright
## =========
## 
## SPDX-FileCopyrightText: © 2025 Isaac Freund
## SPDX-License-Identifier: MIT
## 
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to
## deal in the Software without restriction, including without limitation the
## rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
## sell copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
## 
## The above copyright notice and this permission notice shall be included in
## all copies or substantial portions of the Software.
## 
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
## IN THE SOFTWARE.
## 

type RiverLibinputConfigV1Listener* = object
  finished*: proc(
    data: pointer;
    riverLibinputConfigV1: ptr RiverLibinputConfigV1;
  ) {.nimcall.}
  libinputDevice*: proc(
    data: pointer;
    riverLibinputConfigV1: ptr RiverLibinputConfigV1;
    id: ptr RiverLibinputDeviceV1;
  ) {.nimcall.}
proc addListener*(riverLibinputConfigV1: ptr RiverLibinputConfigV1; listener: ptr RiverLibinputConfigV1Listener; data: pointer): int {.inline.} =
  cast[ptr Proxy](riverLibinputConfigV1).add_listener(listener, data)

proc setUserData*(riverLibinputConfigV1: ptr RiverLibinputConfigV1; userData: pointer) {.inline.} =
  cast[ptr Proxy](riverLibinputConfigV1).set_user_data(user_data)
proc getUserData*(riverLibinputConfigV1: ptr RiverLibinputConfigV1): pointer {.inline.} =
  cast[ptr Proxy](riverLibinputConfigV1).get_user_data()
proc getVersion*(riverLibinputConfigV1: ptr RiverLibinputConfigV1): uint32 {.inline.} =
  cast[ptr Proxy](riverLibinputConfigV1).get_version()
proc stop*(riverLibinputConfigV1: ptr RiverLibinputConfigV1) {.inline.} =
  ## stop sending events
  ## 
  ## This request indicates that the client no longer wishes to receive
  ## events on this object.
  ## 
  ## The Wayland protocol is asynchronous, which means the server may send
  ## further events until the stop request is processed. The client must wait
  ## for a river_libinput_config_v1.finished event before destroying this
  ## object.
  ## 
  cast[ptr Proxy](riverLibinputConfigV1).marshal_flags(RiverLibinputConfigV1Request_stop.ord, nil, cast[ptr Proxy](riverLibinputConfigV1).get_version(), 0)
proc destroy*(riverLibinputConfigV1: ptr RiverLibinputConfigV1) {.inline.} =
  ## destroy the river_libinput_config_v1 object
  ## 
  ## This request should be called after the finished event has been received
  ## to complete destruction of the object.
  ## 
  ## It is a protocol error to make this request before the finished event
  ## has been received.
  ## 
  ## If a client wishes to destroy this object it should send a
  ## river_libinput_config_v1.stop request and wait for a
  ## river_libinput_config_v1.finished event. Once the finished event is
  ## received it is safe to destroy this object and any other objects created
  ## through this interface.
  ## 
  cast[ptr Proxy](riverLibinputConfigV1).marshal_flags(RiverLibinputConfigV1Request_destroy.ord, nil, cast[ptr Proxy](riverLibinputConfigV1).get_version(), WL_MARSHAL_FLAG_DESTROY)
proc createAccelConfig*(riverLibinputConfigV1: ptr RiverLibinputConfigV1; profile: uint32): ptr RiverLibinputAccelConfigV1 {.inline.} =
  ## create a acceleration config
  ## 
  ## Create a acceleration config which can be applied
  ## with river_libinput_device_v1.apply_accel_config.
  ## 
  cast[ptr RiverLibinputAccelConfigV1](cast[ptr Proxy](riverLibinputConfigV1).marshal_flags(RiverLibinputConfigV1Request_create_accel_config.ord, addr river_libinput_accel_config_v1_interface, cast[ptr Proxy](riverLibinputConfigV1).get_version(), 0, nil, profile))
type RiverLibinputDeviceV1Listener* = object
  removed*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
  ) {.nimcall.}
  inputDevice*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    device: ptr RiverInputDeviceV1;
  ) {.nimcall.}
  sendEventsSupport*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    modes: uint32;
  ) {.nimcall.}
  sendEventsDefault*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    mode: uint32;
  ) {.nimcall.}
  sendEventsCurrent*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    mode: uint32;
  ) {.nimcall.}
  tapSupport*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    fingerCount: int32;
  ) {.nimcall.}
  tapDefault*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    state: uint32;
  ) {.nimcall.}
  tapCurrent*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    state: uint32;
  ) {.nimcall.}
  tapButtonMapDefault*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    buttonMap: uint32;
  ) {.nimcall.}
  tapButtonMapCurrent*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    buttonMap: uint32;
  ) {.nimcall.}
  dragDefault*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    state: uint32;
  ) {.nimcall.}
  dragCurrent*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    state: uint32;
  ) {.nimcall.}
  dragLockDefault*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    state: uint32;
  ) {.nimcall.}
  dragLockCurrent*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    state: uint32;
  ) {.nimcall.}
  threeFingerDragSupport*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    fingerCount: int32;
  ) {.nimcall.}
  threeFingerDragDefault*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    state: uint32;
  ) {.nimcall.}
  threeFingerDragCurrent*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    state: uint32;
  ) {.nimcall.}
  calibrationMatrixSupport*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    supported: int32;
  ) {.nimcall.}
  calibrationMatrixDefault*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    matrix: ptr Array;
  ) {.nimcall.}
  calibrationMatrixCurrent*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    matrix: ptr Array;
  ) {.nimcall.}
  accelProfilesSupport*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    profiles: uint32;
  ) {.nimcall.}
  accelProfileDefault*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    profile: uint32;
  ) {.nimcall.}
  accelProfileCurrent*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    profile: uint32;
  ) {.nimcall.}
  accelSpeedDefault*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    speed: ptr Array;
  ) {.nimcall.}
  accelSpeedCurrent*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    speed: ptr Array;
  ) {.nimcall.}
  naturalScrollSupport*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    supported: int32;
  ) {.nimcall.}
  naturalScrollDefault*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    state: uint32;
  ) {.nimcall.}
  naturalScrollCurrent*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    state: uint32;
  ) {.nimcall.}
  leftHandedSupport*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    supported: int32;
  ) {.nimcall.}
  leftHandedDefault*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    state: uint32;
  ) {.nimcall.}
  leftHandedCurrent*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    state: uint32;
  ) {.nimcall.}
  clickMethodSupport*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    methods: uint32;
  ) {.nimcall.}
  clickMethodDefault*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    `method`: uint32;
  ) {.nimcall.}
  clickMethodCurrent*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    `method`: uint32;
  ) {.nimcall.}
  clickfingerButtonMapDefault*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    buttonMap: uint32;
  ) {.nimcall.}
  clickfingerButtonMapCurrent*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    buttonMap: uint32;
  ) {.nimcall.}
  middleEmulationSupport*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    supported: int32;
  ) {.nimcall.}
  middleEmulationDefault*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    state: uint32;
  ) {.nimcall.}
  middleEmulationCurrent*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    state: uint32;
  ) {.nimcall.}
  scrollMethodSupport*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    methods: uint32;
  ) {.nimcall.}
  scrollMethodDefault*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    `method`: uint32;
  ) {.nimcall.}
  scrollMethodCurrent*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    `method`: uint32;
  ) {.nimcall.}
  scrollButtonDefault*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    button: uint32;
  ) {.nimcall.}
  scrollButtonCurrent*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    button: uint32;
  ) {.nimcall.}
  scrollButtonLockDefault*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    state: uint32;
  ) {.nimcall.}
  scrollButtonLockCurrent*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    state: uint32;
  ) {.nimcall.}
  dwtSupport*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    supported: int32;
  ) {.nimcall.}
  dwtDefault*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    state: uint32;
  ) {.nimcall.}
  dwtCurrent*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    state: uint32;
  ) {.nimcall.}
  dwtpSupport*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    supported: int32;
  ) {.nimcall.}
  dwtpDefault*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    state: uint32;
  ) {.nimcall.}
  dwtpCurrent*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    state: uint32;
  ) {.nimcall.}
  rotationSupport*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    supported: int32;
  ) {.nimcall.}
  rotationDefault*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    angle: uint32;
  ) {.nimcall.}
  rotationCurrent*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
    angle: uint32;
  ) {.nimcall.}
  done*: proc(
    data: pointer;
    riverLibinputDeviceV1: ptr RiverLibinputDeviceV1;
  ) {.nimcall.}
proc addListener*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1; listener: ptr RiverLibinputDeviceV1Listener; data: pointer): int {.inline.} =
  cast[ptr Proxy](riverLibinputDeviceV1).add_listener(listener, data)

proc setUserData*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1; userData: pointer) {.inline.} =
  cast[ptr Proxy](riverLibinputDeviceV1).set_user_data(user_data)
proc getUserData*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1): pointer {.inline.} =
  cast[ptr Proxy](riverLibinputDeviceV1).get_user_data()
proc getVersion*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1): uint32 {.inline.} =
  cast[ptr Proxy](riverLibinputDeviceV1).get_version()
proc destroy*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1) {.inline.} =
  ## destroy the libinput device object
  ## 
  ## This request indicates that the client will no longer use the input
  ## device object and that it may be safely destroyed.
  ## 
  cast[ptr Proxy](riverLibinputDeviceV1).marshal_flags(RiverLibinputDeviceV1Request_destroy.ord, nil, cast[ptr Proxy](riverLibinputDeviceV1).get_version(), WL_MARSHAL_FLAG_DESTROY)
proc setSendEvents*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1; mode: uint32): ptr RiverLibinputResultV1 {.inline.} =
  ## set send events mode
  ## 
  ## Set the send events mode for the device.
  ## 
  cast[ptr RiverLibinputResultV1](cast[ptr Proxy](riverLibinputDeviceV1).marshal_flags(RiverLibinputDeviceV1Request_set_send_events.ord, addr river_libinput_result_v1_interface, cast[ptr Proxy](riverLibinputDeviceV1).get_version(), 0, nil, mode))
proc setTap*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1; state: uint32): ptr RiverLibinputResultV1 {.inline.} =
  ## enable/disable tap-to-click
  ## 
  ## Configure tap-to-click on this device, with a default mapping of
  ## 1, 2, 3 finger tap mapping to left, right, middle click, respectively.
  ## 
  cast[ptr RiverLibinputResultV1](cast[ptr Proxy](riverLibinputDeviceV1).marshal_flags(RiverLibinputDeviceV1Request_set_tap.ord, addr river_libinput_result_v1_interface, cast[ptr Proxy](riverLibinputDeviceV1).get_version(), 0, nil, state))
proc setTapButtonMap*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1; buttonMap: uint32): ptr RiverLibinputResultV1 {.inline.} =
  ## set tap-to-click button map
  ## 
  ## Set the finger number to button number mapping for tap-to-click. The
  ## default mapping on most devices is to have a 1, 2 and 3 finger tap to
  ## map to the left, right and middle button, respectively.
  ## 
  cast[ptr RiverLibinputResultV1](cast[ptr Proxy](riverLibinputDeviceV1).marshal_flags(RiverLibinputDeviceV1Request_set_tap_button_map.ord, addr river_libinput_result_v1_interface, cast[ptr Proxy](riverLibinputDeviceV1).get_version(), 0, nil, buttonMap))
proc setDrag*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1; state: uint32): ptr RiverLibinputResultV1 {.inline.} =
  ## set tap-and-drag state
  ## 
  ## Configure tap-and-drag functionality on the device.
  ## 
  cast[ptr RiverLibinputResultV1](cast[ptr Proxy](riverLibinputDeviceV1).marshal_flags(RiverLibinputDeviceV1Request_set_drag.ord, addr river_libinput_result_v1_interface, cast[ptr Proxy](riverLibinputDeviceV1).get_version(), 0, nil, state))
proc setDragLock*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1; state: uint32): ptr RiverLibinputResultV1 {.inline.} =
  ## set drag lock state
  ## 
  ## Configure drag-lock during tapping on this device. When enabled, a
  ## finger may be lifted and put back on the touchpad and the drag process
  ## continues. A timeout for lifting the finger is optional. When disabled,
  ## lifting the finger during a tap-and-drag will immediately stop the drag.
  ## See the libinput documentation for more details.
  ## 
  cast[ptr RiverLibinputResultV1](cast[ptr Proxy](riverLibinputDeviceV1).marshal_flags(RiverLibinputDeviceV1Request_set_drag_lock.ord, addr river_libinput_result_v1_interface, cast[ptr Proxy](riverLibinputDeviceV1).get_version(), 0, nil, state))
proc setThreeFingerDrag*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1; state: uint32): ptr RiverLibinputResultV1 {.inline.} =
  ## set three finger drag state
  ## 
  ## Configure three finger drag functionality for the device.
  ## 
  cast[ptr RiverLibinputResultV1](cast[ptr Proxy](riverLibinputDeviceV1).marshal_flags(RiverLibinputDeviceV1Request_set_three_finger_drag.ord, addr river_libinput_result_v1_interface, cast[ptr Proxy](riverLibinputDeviceV1).get_version(), 0, nil, state))
proc setCalibrationMatrix*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1; matrix: ptr Array): ptr RiverLibinputResultV1 {.inline.} =
  ## set calibration matrix
  ## 
  ## Set calibration matrix.
  ## 
  cast[ptr RiverLibinputResultV1](cast[ptr Proxy](riverLibinputDeviceV1).marshal_flags(RiverLibinputDeviceV1Request_set_calibration_matrix.ord, addr river_libinput_result_v1_interface, cast[ptr Proxy](riverLibinputDeviceV1).get_version(), 0, nil, matrix))
proc setAccelProfile*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1; profile: uint32): ptr RiverLibinputResultV1 {.inline.} =
  ## set acceleration profile
  ## 
  ## Set the acceleration profile.
  ## 
  cast[ptr RiverLibinputResultV1](cast[ptr Proxy](riverLibinputDeviceV1).marshal_flags(RiverLibinputDeviceV1Request_set_accel_profile.ord, addr river_libinput_result_v1_interface, cast[ptr Proxy](riverLibinputDeviceV1).get_version(), 0, nil, profile))
proc setAccelSpeed*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1; speed: ptr Array): ptr RiverLibinputResultV1 {.inline.} =
  ## set acceleration speed
  ## 
  ## Set the acceleration speed within a range of [-1, 1], where 0 is
  ## the default acceleration for this device, -1 is the slowest acceleration
  ## and 1 is the maximum acceleration available on this device.
  ## 
  cast[ptr RiverLibinputResultV1](cast[ptr Proxy](riverLibinputDeviceV1).marshal_flags(RiverLibinputDeviceV1Request_set_accel_speed.ord, addr river_libinput_result_v1_interface, cast[ptr Proxy](riverLibinputDeviceV1).get_version(), 0, nil, speed))
proc applyAccelConfig*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1; config: ptr RiverLibinputAccelConfigV1): ptr RiverLibinputResultV1 {.inline.} =
  ## apply acceleration config
  ## 
  ## Apply a pointer accleration config.
  ## 
  cast[ptr RiverLibinputResultV1](cast[ptr Proxy](riverLibinputDeviceV1).marshal_flags(RiverLibinputDeviceV1Request_apply_accel_config.ord, addr river_libinput_result_v1_interface, cast[ptr Proxy](riverLibinputDeviceV1).get_version(), 0, nil, config))
proc setNaturalScroll*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1; state: uint32): ptr RiverLibinputResultV1 {.inline.} =
  ## set natural scroll state
  ## 
  ## Set natural scroll state.
  ## 
  cast[ptr RiverLibinputResultV1](cast[ptr Proxy](riverLibinputDeviceV1).marshal_flags(RiverLibinputDeviceV1Request_set_natural_scroll.ord, addr river_libinput_result_v1_interface, cast[ptr Proxy](riverLibinputDeviceV1).get_version(), 0, nil, state))
proc setLeftHanded*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1; state: uint32): ptr RiverLibinputResultV1 {.inline.} =
  ## set left-handed mode state
  ## 
  ## Set left-handed mode state.
  ## 
  cast[ptr RiverLibinputResultV1](cast[ptr Proxy](riverLibinputDeviceV1).marshal_flags(RiverLibinputDeviceV1Request_set_left_handed.ord, addr river_libinput_result_v1_interface, cast[ptr Proxy](riverLibinputDeviceV1).get_version(), 0, nil, state))
proc setClickMethod*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1; `method`: uint32): ptr RiverLibinputResultV1 {.inline.} =
  ## set click method
  ## 
  ## Set click method.
  ## 
  cast[ptr RiverLibinputResultV1](cast[ptr Proxy](riverLibinputDeviceV1).marshal_flags(RiverLibinputDeviceV1Request_set_click_method.ord, addr river_libinput_result_v1_interface, cast[ptr Proxy](riverLibinputDeviceV1).get_version(), 0, nil, `method`))
proc setClickfingerButtonMap*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1; buttonMap: uint32): ptr RiverLibinputResultV1 {.inline.} =
  ## set clickfinger button map
  ## 
  ## Set clickfinger button map.
  ## Supported if click_methods.clickfinger is supported.
  ## 
  cast[ptr RiverLibinputResultV1](cast[ptr Proxy](riverLibinputDeviceV1).marshal_flags(RiverLibinputDeviceV1Request_set_clickfinger_button_map.ord, addr river_libinput_result_v1_interface, cast[ptr Proxy](riverLibinputDeviceV1).get_version(), 0, nil, buttonMap))
proc setMiddleEmulation*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1; state: uint32): ptr RiverLibinputResultV1 {.inline.} =
  ## set middle mouse button emulation state
  ## 
  ## Set middle mouse button emulation state.
  ## 
  cast[ptr RiverLibinputResultV1](cast[ptr Proxy](riverLibinputDeviceV1).marshal_flags(RiverLibinputDeviceV1Request_set_middle_emulation.ord, addr river_libinput_result_v1_interface, cast[ptr Proxy](riverLibinputDeviceV1).get_version(), 0, nil, state))
proc setScrollMethod*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1; `method`: uint32): ptr RiverLibinputResultV1 {.inline.} =
  ## set scroll method
  ## 
  ## Set scroll method.
  ## 
  cast[ptr RiverLibinputResultV1](cast[ptr Proxy](riverLibinputDeviceV1).marshal_flags(RiverLibinputDeviceV1Request_set_scroll_method.ord, addr river_libinput_result_v1_interface, cast[ptr Proxy](riverLibinputDeviceV1).get_version(), 0, nil, `method`))
proc setScrollButton*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1; button: uint32): ptr RiverLibinputResultV1 {.inline.} =
  ## set scroll button
  ## 
  ## Set scroll button.
  ## Supported if scroll_methods.on_button_down is supported.
  ## 
  cast[ptr RiverLibinputResultV1](cast[ptr Proxy](riverLibinputDeviceV1).marshal_flags(RiverLibinputDeviceV1Request_set_scroll_button.ord, addr river_libinput_result_v1_interface, cast[ptr Proxy](riverLibinputDeviceV1).get_version(), 0, nil, button))
proc setScrollButtonLock*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1; state: uint32): ptr RiverLibinputResultV1 {.inline.} =
  ## set scroll button lock state
  ## 
  ## Set scroll button lock state.
  ## Supported if scroll_methods.on_button_down is supported.
  ## 
  cast[ptr RiverLibinputResultV1](cast[ptr Proxy](riverLibinputDeviceV1).marshal_flags(RiverLibinputDeviceV1Request_set_scroll_button_lock.ord, addr river_libinput_result_v1_interface, cast[ptr Proxy](riverLibinputDeviceV1).get_version(), 0, nil, state))
proc setDwt*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1; state: uint32): ptr RiverLibinputResultV1 {.inline.} =
  ## set disable-while-typing state
  ## 
  ## Set disable-while-typing state.
  ## 
  cast[ptr RiverLibinputResultV1](cast[ptr Proxy](riverLibinputDeviceV1).marshal_flags(RiverLibinputDeviceV1Request_set_dwt.ord, addr river_libinput_result_v1_interface, cast[ptr Proxy](riverLibinputDeviceV1).get_version(), 0, nil, state))
proc setDwtp*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1; state: uint32): ptr RiverLibinputResultV1 {.inline.} =
  ## set disable-while-trackpointing state
  ## 
  ## Set disable-while-trackpointing state.
  ## 
  cast[ptr RiverLibinputResultV1](cast[ptr Proxy](riverLibinputDeviceV1).marshal_flags(RiverLibinputDeviceV1Request_set_dwtp.ord, addr river_libinput_result_v1_interface, cast[ptr Proxy](riverLibinputDeviceV1).get_version(), 0, nil, state))
proc setRotation*(riverLibinputDeviceV1: ptr RiverLibinputDeviceV1; angle: uint32): ptr RiverLibinputResultV1 {.inline.} =
  ## set rotation angle
  ## 
  ## Set rotation angle in degrees clockwise off the logical neutral
  ## position. Angle must be in the range [0-360).
  ## 
  cast[ptr RiverLibinputResultV1](cast[ptr Proxy](riverLibinputDeviceV1).marshal_flags(RiverLibinputDeviceV1Request_set_rotation.ord, addr river_libinput_result_v1_interface, cast[ptr Proxy](riverLibinputDeviceV1).get_version(), 0, nil, angle))
proc setUserData*(riverLibinputAccelConfigV1: ptr RiverLibinputAccelConfigV1; userData: pointer) {.inline.} =
  cast[ptr Proxy](riverLibinputAccelConfigV1).set_user_data(user_data)
proc getUserData*(riverLibinputAccelConfigV1: ptr RiverLibinputAccelConfigV1): pointer {.inline.} =
  cast[ptr Proxy](riverLibinputAccelConfigV1).get_user_data()
proc getVersion*(riverLibinputAccelConfigV1: ptr RiverLibinputAccelConfigV1): uint32 {.inline.} =
  cast[ptr Proxy](riverLibinputAccelConfigV1).get_version()
proc destroy*(riverLibinputAccelConfigV1: ptr RiverLibinputAccelConfigV1) {.inline.} =
  ## destroy the accel object
  ## 
  ## This request indicates that the client will no longer use the accel
  ## config object and that it may be safely destroyed.
  ## 
  cast[ptr Proxy](riverLibinputAccelConfigV1).marshal_flags(RiverLibinputAccelConfigV1Request_destroy.ord, nil, cast[ptr Proxy](riverLibinputAccelConfigV1).get_version(), WL_MARSHAL_FLAG_DESTROY)
proc setPoints*(riverLibinputAccelConfigV1: ptr RiverLibinputAccelConfigV1; `type`: uint32; step: ptr Array; points: ptr Array): ptr RiverLibinputResultV1 {.inline.} =
  ## define custom acceleration function
  ## 
  ## Defines the acceleration function for a given movement type
  ## in an acceleration configuration with custom accel profile.
  ## 
  cast[ptr RiverLibinputResultV1](cast[ptr Proxy](riverLibinputAccelConfigV1).marshal_flags(RiverLibinputAccelConfigV1Request_set_points.ord, addr river_libinput_result_v1_interface, cast[ptr Proxy](riverLibinputAccelConfigV1).get_version(), 0, nil, `type`, step, points))
type RiverLibinputResultV1Listener* = object
  success*: proc(
    data: pointer;
    riverLibinputResultV1: ptr RiverLibinputResultV1;
  ) {.nimcall.}
  unsupported*: proc(
    data: pointer;
    riverLibinputResultV1: ptr RiverLibinputResultV1;
  ) {.nimcall.}
  invalid*: proc(
    data: pointer;
    riverLibinputResultV1: ptr RiverLibinputResultV1;
  ) {.nimcall.}
proc addListener*(riverLibinputResultV1: ptr RiverLibinputResultV1; listener: ptr RiverLibinputResultV1Listener; data: pointer): int {.inline.} =
  cast[ptr Proxy](riverLibinputResultV1).add_listener(listener, data)

proc setUserData*(riverLibinputResultV1: ptr RiverLibinputResultV1; userData: pointer) {.inline.} =
  cast[ptr Proxy](riverLibinputResultV1).set_user_data(user_data)
proc getUserData*(riverLibinputResultV1: ptr RiverLibinputResultV1): pointer {.inline.} =
  cast[ptr Proxy](riverLibinputResultV1).get_user_data()
proc getVersion*(riverLibinputResultV1: ptr RiverLibinputResultV1): uint32 {.inline.} =
  cast[ptr Proxy](riverLibinputResultV1).get_version()
proc destroy*(riverLibinputResultV1: ptr RiverLibinputResultV1) {.inline.} =
  destroy cast[ptr Proxy](riverLibinputResultV1)
