# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code
import protocols/river_input_management/code as river_input_management_code

var riverLibinputConfigV1_types: array[51, ptr Interface]
type RiverLibinputAccelConfigV1* = object
type RiverLibinputConfigV1* = object
type RiverLibinputDeviceV1* = object
type RiverLibinputResultV1* = object

let
  river_libinput_config_v1_requests {.exportc.} = [
    Message(name: "stop", signature: "", types: addr river_libinput_config_v1_types[0]),
    Message(name: "destroy", signature: "", types: addr river_libinput_config_v1_types[0]),
    Message(name: "create_accel_config", signature: "nu", types: addr river_libinput_config_v1_types[1]),
  ]

  river_libinput_config_v1_events {.exportc.} = [
    Message(name: "finished", signature: "", types: addr river_libinput_config_v1_types[0]),
    Message(name: "libinput_device", signature: "n", types: addr river_libinput_config_v1_types[3]),
  ]

  river_libinput_config_v1_interface* {.exportc.} = Interface(
    name: "river_libinput_config_v1",
    version: 2,
    method_count: 3,
    methods: addr river_libinput_config_v1_requests[0],
    event_count: 2,
    events: addr river_libinput_config_v1_events[0],
  )

  river_libinput_device_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr river_libinput_config_v1_types[0]),
    Message(name: "set_send_events", signature: "nu", types: addr river_libinput_config_v1_types[4]),
    Message(name: "set_tap", signature: "nu", types: addr river_libinput_config_v1_types[6]),
    Message(name: "set_tap_button_map", signature: "nu", types: addr river_libinput_config_v1_types[8]),
    Message(name: "set_drag", signature: "nu", types: addr river_libinput_config_v1_types[10]),
    Message(name: "set_drag_lock", signature: "nu", types: addr river_libinput_config_v1_types[12]),
    Message(name: "set_three_finger_drag", signature: "nu", types: addr river_libinput_config_v1_types[14]),
    Message(name: "set_calibration_matrix", signature: "na", types: addr river_libinput_config_v1_types[16]),
    Message(name: "set_accel_profile", signature: "nu", types: addr river_libinput_config_v1_types[18]),
    Message(name: "set_accel_speed", signature: "na", types: addr river_libinput_config_v1_types[20]),
    Message(name: "apply_accel_config", signature: "no", types: addr river_libinput_config_v1_types[22]),
    Message(name: "set_natural_scroll", signature: "nu", types: addr river_libinput_config_v1_types[24]),
    Message(name: "set_left_handed", signature: "nu", types: addr river_libinput_config_v1_types[26]),
    Message(name: "set_click_method", signature: "nu", types: addr river_libinput_config_v1_types[28]),
    Message(name: "set_clickfinger_button_map", signature: "nu", types: addr river_libinput_config_v1_types[30]),
    Message(name: "set_middle_emulation", signature: "nu", types: addr river_libinput_config_v1_types[32]),
    Message(name: "set_scroll_method", signature: "nu", types: addr river_libinput_config_v1_types[34]),
    Message(name: "set_scroll_button", signature: "nu", types: addr river_libinput_config_v1_types[36]),
    Message(name: "set_scroll_button_lock", signature: "nu", types: addr river_libinput_config_v1_types[38]),
    Message(name: "set_dwt", signature: "nu", types: addr river_libinput_config_v1_types[40]),
    Message(name: "set_dwtp", signature: "nu", types: addr river_libinput_config_v1_types[42]),
    Message(name: "set_rotation", signature: "nu", types: addr river_libinput_config_v1_types[44]),
  ]

  river_libinput_device_v1_events {.exportc.} = [
    Message(name: "removed", signature: "", types: addr river_libinput_config_v1_types[0]),
    Message(name: "input_device", signature: "o", types: addr river_libinput_config_v1_types[46]),
    Message(name: "send_events_support", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "send_events_default", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "send_events_current", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "tap_support", signature: "i", types: addr river_libinput_config_v1_types[0]),
    Message(name: "tap_default", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "tap_current", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "tap_button_map_default", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "tap_button_map_current", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "drag_default", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "drag_current", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "drag_lock_default", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "drag_lock_current", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "three_finger_drag_support", signature: "i", types: addr river_libinput_config_v1_types[0]),
    Message(name: "three_finger_drag_default", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "three_finger_drag_current", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "calibration_matrix_support", signature: "i", types: addr river_libinput_config_v1_types[0]),
    Message(name: "calibration_matrix_default", signature: "a", types: addr river_libinput_config_v1_types[0]),
    Message(name: "calibration_matrix_current", signature: "a", types: addr river_libinput_config_v1_types[0]),
    Message(name: "accel_profiles_support", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "accel_profile_default", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "accel_profile_current", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "accel_speed_default", signature: "a", types: addr river_libinput_config_v1_types[0]),
    Message(name: "accel_speed_current", signature: "a", types: addr river_libinput_config_v1_types[0]),
    Message(name: "natural_scroll_support", signature: "i", types: addr river_libinput_config_v1_types[0]),
    Message(name: "natural_scroll_default", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "natural_scroll_current", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "left_handed_support", signature: "i", types: addr river_libinput_config_v1_types[0]),
    Message(name: "left_handed_default", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "left_handed_current", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "click_method_support", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "click_method_default", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "click_method_current", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "clickfinger_button_map_default", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "clickfinger_button_map_current", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "middle_emulation_support", signature: "i", types: addr river_libinput_config_v1_types[0]),
    Message(name: "middle_emulation_default", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "middle_emulation_current", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "scroll_method_support", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "scroll_method_default", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "scroll_method_current", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "scroll_button_default", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "scroll_button_current", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "scroll_button_lock_default", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "scroll_button_lock_current", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "dwt_support", signature: "i", types: addr river_libinput_config_v1_types[0]),
    Message(name: "dwt_default", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "dwt_current", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "dwtp_support", signature: "i", types: addr river_libinput_config_v1_types[0]),
    Message(name: "dwtp_default", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "dwtp_current", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "rotation_support", signature: "i", types: addr river_libinput_config_v1_types[0]),
    Message(name: "rotation_default", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "rotation_current", signature: "u", types: addr river_libinput_config_v1_types[0]),
    Message(name: "done", signature: "2", types: addr river_libinput_config_v1_types[0]),
  ]

  river_libinput_device_v1_interface* {.exportc.} = Interface(
    name: "river_libinput_device_v1",
    version: 2,
    method_count: 22,
    methods: addr river_libinput_device_v1_requests[0],
    event_count: 56,
    events: addr river_libinput_device_v1_events[0],
  )

  river_libinput_accel_config_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr river_libinput_config_v1_types[0]),
    Message(name: "set_points", signature: "nuaa", types: addr river_libinput_config_v1_types[47]),
  ]

  river_libinput_accel_config_v1_interface* {.exportc.} = Interface(
    name: "river_libinput_accel_config_v1",
    version: 1,
    method_count: 2,
    methods: addr river_libinput_accel_config_v1_requests[0],
  )

  river_libinput_result_v1_events {.exportc.} = [
    Message(name: "success", signature: "", types: addr river_libinput_config_v1_types[0]),
    Message(name: "unsupported", signature: "", types: addr river_libinput_config_v1_types[0]),
    Message(name: "invalid", signature: "", types: addr river_libinput_config_v1_types[0]),
  ]

  river_libinput_result_v1_interface* {.exportc.} = Interface(
    name: "river_libinput_result_v1",
    version: 1,
    event_count: 3,
    events: addr river_libinput_result_v1_events[0],
  )


type RiverLibinputConfigV1Error* {.size: sizeof(uint32).} = enum
  error_invalid_arg = 0
  error_invalid_destroy = 1
func since*(e: RiverLibinputConfigV1Error): int =
  case e
  of error_invalid_arg: 1
  of error_invalid_destroy: 1
proc isValid*(e: RiverLibinputConfigV1Error; version: int): bool =
  version >= e.since

type RiverLibinputDeviceV1Error* {.size: sizeof(uint32).} = enum
  error_invalid_arg = 0
func since*(e: RiverLibinputDeviceV1Error): int =
  case e
  of error_invalid_arg: 1
proc isValid*(e: RiverLibinputDeviceV1Error; version: int): bool =
  version >= e.since

type RiverLibinputDeviceV1SendEventsModes* {.size: sizeof(uint32).} = enum
  send_events_modes_enabled = 0
  send_events_modes_disabled = 1
  send_events_modes_disabled_on_external_mouse = 2
func since*(e: RiverLibinputDeviceV1SendEventsModes): int =
  case e
  of send_events_modes_enabled: 1
  of send_events_modes_disabled: 1
  of send_events_modes_disabled_on_external_mouse: 1
proc isValid*(e: RiverLibinputDeviceV1SendEventsModes; version: int): bool =
  version >= e.since

type RiverLibinputDeviceV1TapState* {.size: sizeof(uint32).} = enum
  tap_state_disabled = 0
  tap_state_enabled = 1
func since*(e: RiverLibinputDeviceV1TapState): int =
  case e
  of tap_state_disabled: 1
  of tap_state_enabled: 1
proc isValid*(e: RiverLibinputDeviceV1TapState; version: int): bool =
  version >= e.since

type RiverLibinputDeviceV1TapButtonMap* {.size: sizeof(uint32).} = enum
  tap_button_map_lrm = 0
  tap_button_map_lmr = 1
func since*(e: RiverLibinputDeviceV1TapButtonMap): int =
  case e
  of tap_button_map_lrm: 1
  of tap_button_map_lmr: 1
proc isValid*(e: RiverLibinputDeviceV1TapButtonMap; version: int): bool =
  version >= e.since

type RiverLibinputDeviceV1DragState* {.size: sizeof(uint32).} = enum
  drag_state_disabled = 0
  drag_state_enabled = 1
func since*(e: RiverLibinputDeviceV1DragState): int =
  case e
  of drag_state_disabled: 1
  of drag_state_enabled: 1
proc isValid*(e: RiverLibinputDeviceV1DragState; version: int): bool =
  version >= e.since

type RiverLibinputDeviceV1DragLockState* {.size: sizeof(uint32).} = enum
  drag_lock_state_disabled = 0
  drag_lock_state_enabled_timeout = 1
  drag_lock_state_enabled_sticky = 2
func since*(e: RiverLibinputDeviceV1DragLockState): int =
  case e
  of drag_lock_state_disabled: 1
  of drag_lock_state_enabled_timeout: 1
  of drag_lock_state_enabled_sticky: 1
proc isValid*(e: RiverLibinputDeviceV1DragLockState; version: int): bool =
  version >= e.since

type RiverLibinputDeviceV1ThreeFingerDragState* {.size: sizeof(uint32).} = enum
  three_finger_drag_state_disabled = 0
  three_finger_drag_state_enabled_3fg = 1
  three_finger_drag_state_enabled_4fg = 2
func since*(e: RiverLibinputDeviceV1ThreeFingerDragState): int =
  case e
  of three_finger_drag_state_disabled: 1
  of three_finger_drag_state_enabled_3fg: 1
  of three_finger_drag_state_enabled_4fg: 1
proc isValid*(e: RiverLibinputDeviceV1ThreeFingerDragState; version: int): bool =
  version >= e.since

type RiverLibinputDeviceV1AccelProfile* {.size: sizeof(uint32).} = enum
  accel_profile_none = 0
  accel_profile_flat = 1
  accel_profile_adaptive = 2
  accel_profile_custom = 4
func since*(e: RiverLibinputDeviceV1AccelProfile): int =
  case e
  of accel_profile_none: 1
  of accel_profile_flat: 1
  of accel_profile_adaptive: 1
  of accel_profile_custom: 1
proc isValid*(e: RiverLibinputDeviceV1AccelProfile; version: int): bool =
  version >= e.since

type RiverLibinputDeviceV1AccelProfiles* {.size: sizeof(uint32).} = enum
  accel_profiles_none = 0
  accel_profiles_flat = 1
  accel_profiles_adaptive = 2
  accel_profiles_custom = 4
func since*(e: RiverLibinputDeviceV1AccelProfiles): int =
  case e
  of accel_profiles_none: 1
  of accel_profiles_flat: 1
  of accel_profiles_adaptive: 1
  of accel_profiles_custom: 1
proc isValid*(e: RiverLibinputDeviceV1AccelProfiles; version: int): bool =
  version >= e.since

type RiverLibinputDeviceV1NaturalScrollState* {.size: sizeof(uint32).} = enum
  natural_scroll_state_disabled = 0
  natural_scroll_state_enabled = 1
func since*(e: RiverLibinputDeviceV1NaturalScrollState): int =
  case e
  of natural_scroll_state_disabled: 1
  of natural_scroll_state_enabled: 1
proc isValid*(e: RiverLibinputDeviceV1NaturalScrollState; version: int): bool =
  version >= e.since

type RiverLibinputDeviceV1LeftHandedState* {.size: sizeof(uint32).} = enum
  left_handed_state_disabled = 0
  left_handed_state_enabled = 1
func since*(e: RiverLibinputDeviceV1LeftHandedState): int =
  case e
  of left_handed_state_disabled: 1
  of left_handed_state_enabled: 1
proc isValid*(e: RiverLibinputDeviceV1LeftHandedState; version: int): bool =
  version >= e.since

type RiverLibinputDeviceV1ClickMethod* {.size: sizeof(uint32).} = enum
  click_method_none = 0
  click_method_button_areas = 1
  click_method_clickfinger = 2
func since*(e: RiverLibinputDeviceV1ClickMethod): int =
  case e
  of click_method_none: 1
  of click_method_button_areas: 1
  of click_method_clickfinger: 1
proc isValid*(e: RiverLibinputDeviceV1ClickMethod; version: int): bool =
  version >= e.since

type RiverLibinputDeviceV1ClickMethods* {.size: sizeof(uint32).} = enum
  click_methods_none = 0
  click_methods_button_areas = 1
  click_methods_clickfinger = 2
func since*(e: RiverLibinputDeviceV1ClickMethods): int =
  case e
  of click_methods_none: 1
  of click_methods_button_areas: 1
  of click_methods_clickfinger: 1
proc isValid*(e: RiverLibinputDeviceV1ClickMethods; version: int): bool =
  version >= e.since

type RiverLibinputDeviceV1ClickfingerButtonMap* {.size: sizeof(uint32).} = enum
  clickfinger_button_map_lrm = 0
  clickfinger_button_map_lmr = 1
func since*(e: RiverLibinputDeviceV1ClickfingerButtonMap): int =
  case e
  of clickfinger_button_map_lrm: 1
  of clickfinger_button_map_lmr: 1
proc isValid*(e: RiverLibinputDeviceV1ClickfingerButtonMap; version: int): bool =
  version >= e.since

type RiverLibinputDeviceV1MiddleEmulationState* {.size: sizeof(uint32).} = enum
  middle_emulation_state_disabled = 0
  middle_emulation_state_enabled = 1
func since*(e: RiverLibinputDeviceV1MiddleEmulationState): int =
  case e
  of middle_emulation_state_disabled: 1
  of middle_emulation_state_enabled: 1
proc isValid*(e: RiverLibinputDeviceV1MiddleEmulationState; version: int): bool =
  version >= e.since

type RiverLibinputDeviceV1ScrollMethod* {.size: sizeof(uint32).} = enum
  scroll_method_no_scroll = 0
  scroll_method_two_finger = 1
  scroll_method_edge = 2
  scroll_method_on_button_down = 4
func since*(e: RiverLibinputDeviceV1ScrollMethod): int =
  case e
  of scroll_method_no_scroll: 1
  of scroll_method_two_finger: 1
  of scroll_method_edge: 1
  of scroll_method_on_button_down: 1
proc isValid*(e: RiverLibinputDeviceV1ScrollMethod; version: int): bool =
  version >= e.since

type RiverLibinputDeviceV1ScrollMethods* {.size: sizeof(uint32).} = enum
  scroll_methods_no_scroll = 0
  scroll_methods_two_finger = 1
  scroll_methods_edge = 2
  scroll_methods_on_button_down = 4
func since*(e: RiverLibinputDeviceV1ScrollMethods): int =
  case e
  of scroll_methods_no_scroll: 1
  of scroll_methods_two_finger: 1
  of scroll_methods_edge: 1
  of scroll_methods_on_button_down: 1
proc isValid*(e: RiverLibinputDeviceV1ScrollMethods; version: int): bool =
  version >= e.since

type RiverLibinputDeviceV1ScrollButtonLockState* {.size: sizeof(uint32).} = enum
  scroll_button_lock_state_disabled = 0
  scroll_button_lock_state_enabled = 1
func since*(e: RiverLibinputDeviceV1ScrollButtonLockState): int =
  case e
  of scroll_button_lock_state_disabled: 1
  of scroll_button_lock_state_enabled: 1
proc isValid*(e: RiverLibinputDeviceV1ScrollButtonLockState; version: int): bool =
  version >= e.since

type RiverLibinputDeviceV1DwtState* {.size: sizeof(uint32).} = enum
  dwt_state_disabled = 0
  dwt_state_enabled = 1
func since*(e: RiverLibinputDeviceV1DwtState): int =
  case e
  of dwt_state_disabled: 1
  of dwt_state_enabled: 1
proc isValid*(e: RiverLibinputDeviceV1DwtState; version: int): bool =
  version >= e.since

type RiverLibinputDeviceV1DwtpState* {.size: sizeof(uint32).} = enum
  dwtp_state_disabled = 0
  dwtp_state_enabled = 1
func since*(e: RiverLibinputDeviceV1DwtpState): int =
  case e
  of dwtp_state_disabled: 1
  of dwtp_state_enabled: 1
proc isValid*(e: RiverLibinputDeviceV1DwtpState; version: int): bool =
  version >= e.since

type RiverLibinputAccelConfigV1Error* {.size: sizeof(uint32).} = enum
  error_invalid_arg = 0
func since*(e: RiverLibinputAccelConfigV1Error): int =
  case e
  of error_invalid_arg: 1
proc isValid*(e: RiverLibinputAccelConfigV1Error; version: int): bool =
  version >= e.since

type RiverLibinputAccelConfigV1AccelType* {.size: sizeof(uint32).} = enum
  accel_type_fallback = 0
  accel_type_motion = 1
  accel_type_scroll = 2
func since*(e: RiverLibinputAccelConfigV1AccelType): int =
  case e
  of accel_type_fallback: 1
  of accel_type_motion: 1
  of accel_type_scroll: 1
proc isValid*(e: RiverLibinputAccelConfigV1AccelType; version: int): bool =
  version >= e.since

type RiverLibinputConfigV1Event* {.size: sizeof(uint32).} = enum
  RiverLibinputConfigV1Event_finished
  RiverLibinputConfigV1Event_libinput_device
proc since*(e: RiverLibinputConfigV1Event): int =
  case e
  of RiverLibinputConfigV1Event_finished: 1
  of RiverLibinputConfigV1Event_libinput_device: 1

type RiverLibinputConfigV1Request* {.size: sizeof(uint32).} = enum
  RiverLibinputConfigV1Request_stop
  RiverLibinputConfigV1Request_destroy
  RiverLibinputConfigV1Request_create_accel_config
proc since*(e: RiverLibinputConfigV1Request): int =
  case e
  of RiverLibinputConfigV1Request_stop: 1
  of RiverLibinputConfigV1Request_destroy: 1
  of RiverLibinputConfigV1Request_create_accel_config: 1

type RiverLibinputDeviceV1Event* {.size: sizeof(uint32).} = enum
  RiverLibinputDeviceV1Event_removed
  RiverLibinputDeviceV1Event_input_device
  RiverLibinputDeviceV1Event_send_events_support
  RiverLibinputDeviceV1Event_send_events_default
  RiverLibinputDeviceV1Event_send_events_current
  RiverLibinputDeviceV1Event_tap_support
  RiverLibinputDeviceV1Event_tap_default
  RiverLibinputDeviceV1Event_tap_current
  RiverLibinputDeviceV1Event_tap_button_map_default
  RiverLibinputDeviceV1Event_tap_button_map_current
  RiverLibinputDeviceV1Event_drag_default
  RiverLibinputDeviceV1Event_drag_current
  RiverLibinputDeviceV1Event_drag_lock_default
  RiverLibinputDeviceV1Event_drag_lock_current
  RiverLibinputDeviceV1Event_three_finger_drag_support
  RiverLibinputDeviceV1Event_three_finger_drag_default
  RiverLibinputDeviceV1Event_three_finger_drag_current
  RiverLibinputDeviceV1Event_calibration_matrix_support
  RiverLibinputDeviceV1Event_calibration_matrix_default
  RiverLibinputDeviceV1Event_calibration_matrix_current
  RiverLibinputDeviceV1Event_accel_profiles_support
  RiverLibinputDeviceV1Event_accel_profile_default
  RiverLibinputDeviceV1Event_accel_profile_current
  RiverLibinputDeviceV1Event_accel_speed_default
  RiverLibinputDeviceV1Event_accel_speed_current
  RiverLibinputDeviceV1Event_natural_scroll_support
  RiverLibinputDeviceV1Event_natural_scroll_default
  RiverLibinputDeviceV1Event_natural_scroll_current
  RiverLibinputDeviceV1Event_left_handed_support
  RiverLibinputDeviceV1Event_left_handed_default
  RiverLibinputDeviceV1Event_left_handed_current
  RiverLibinputDeviceV1Event_click_method_support
  RiverLibinputDeviceV1Event_click_method_default
  RiverLibinputDeviceV1Event_click_method_current
  RiverLibinputDeviceV1Event_clickfinger_button_map_default
  RiverLibinputDeviceV1Event_clickfinger_button_map_current
  RiverLibinputDeviceV1Event_middle_emulation_support
  RiverLibinputDeviceV1Event_middle_emulation_default
  RiverLibinputDeviceV1Event_middle_emulation_current
  RiverLibinputDeviceV1Event_scroll_method_support
  RiverLibinputDeviceV1Event_scroll_method_default
  RiverLibinputDeviceV1Event_scroll_method_current
  RiverLibinputDeviceV1Event_scroll_button_default
  RiverLibinputDeviceV1Event_scroll_button_current
  RiverLibinputDeviceV1Event_scroll_button_lock_default
  RiverLibinputDeviceV1Event_scroll_button_lock_current
  RiverLibinputDeviceV1Event_dwt_support
  RiverLibinputDeviceV1Event_dwt_default
  RiverLibinputDeviceV1Event_dwt_current
  RiverLibinputDeviceV1Event_dwtp_support
  RiverLibinputDeviceV1Event_dwtp_default
  RiverLibinputDeviceV1Event_dwtp_current
  RiverLibinputDeviceV1Event_rotation_support
  RiverLibinputDeviceV1Event_rotation_default
  RiverLibinputDeviceV1Event_rotation_current
  RiverLibinputDeviceV1Event_done
proc since*(e: RiverLibinputDeviceV1Event): int =
  case e
  of RiverLibinputDeviceV1Event_removed: 1
  of RiverLibinputDeviceV1Event_input_device: 1
  of RiverLibinputDeviceV1Event_send_events_support: 1
  of RiverLibinputDeviceV1Event_send_events_default: 1
  of RiverLibinputDeviceV1Event_send_events_current: 1
  of RiverLibinputDeviceV1Event_tap_support: 1
  of RiverLibinputDeviceV1Event_tap_default: 1
  of RiverLibinputDeviceV1Event_tap_current: 1
  of RiverLibinputDeviceV1Event_tap_button_map_default: 1
  of RiverLibinputDeviceV1Event_tap_button_map_current: 1
  of RiverLibinputDeviceV1Event_drag_default: 1
  of RiverLibinputDeviceV1Event_drag_current: 1
  of RiverLibinputDeviceV1Event_drag_lock_default: 1
  of RiverLibinputDeviceV1Event_drag_lock_current: 1
  of RiverLibinputDeviceV1Event_three_finger_drag_support: 1
  of RiverLibinputDeviceV1Event_three_finger_drag_default: 1
  of RiverLibinputDeviceV1Event_three_finger_drag_current: 1
  of RiverLibinputDeviceV1Event_calibration_matrix_support: 1
  of RiverLibinputDeviceV1Event_calibration_matrix_default: 1
  of RiverLibinputDeviceV1Event_calibration_matrix_current: 1
  of RiverLibinputDeviceV1Event_accel_profiles_support: 1
  of RiverLibinputDeviceV1Event_accel_profile_default: 1
  of RiverLibinputDeviceV1Event_accel_profile_current: 1
  of RiverLibinputDeviceV1Event_accel_speed_default: 1
  of RiverLibinputDeviceV1Event_accel_speed_current: 1
  of RiverLibinputDeviceV1Event_natural_scroll_support: 1
  of RiverLibinputDeviceV1Event_natural_scroll_default: 1
  of RiverLibinputDeviceV1Event_natural_scroll_current: 1
  of RiverLibinputDeviceV1Event_left_handed_support: 1
  of RiverLibinputDeviceV1Event_left_handed_default: 1
  of RiverLibinputDeviceV1Event_left_handed_current: 1
  of RiverLibinputDeviceV1Event_click_method_support: 1
  of RiverLibinputDeviceV1Event_click_method_default: 1
  of RiverLibinputDeviceV1Event_click_method_current: 1
  of RiverLibinputDeviceV1Event_clickfinger_button_map_default: 1
  of RiverLibinputDeviceV1Event_clickfinger_button_map_current: 1
  of RiverLibinputDeviceV1Event_middle_emulation_support: 1
  of RiverLibinputDeviceV1Event_middle_emulation_default: 1
  of RiverLibinputDeviceV1Event_middle_emulation_current: 1
  of RiverLibinputDeviceV1Event_scroll_method_support: 1
  of RiverLibinputDeviceV1Event_scroll_method_default: 1
  of RiverLibinputDeviceV1Event_scroll_method_current: 1
  of RiverLibinputDeviceV1Event_scroll_button_default: 1
  of RiverLibinputDeviceV1Event_scroll_button_current: 1
  of RiverLibinputDeviceV1Event_scroll_button_lock_default: 1
  of RiverLibinputDeviceV1Event_scroll_button_lock_current: 1
  of RiverLibinputDeviceV1Event_dwt_support: 1
  of RiverLibinputDeviceV1Event_dwt_default: 1
  of RiverLibinputDeviceV1Event_dwt_current: 1
  of RiverLibinputDeviceV1Event_dwtp_support: 1
  of RiverLibinputDeviceV1Event_dwtp_default: 1
  of RiverLibinputDeviceV1Event_dwtp_current: 1
  of RiverLibinputDeviceV1Event_rotation_support: 1
  of RiverLibinputDeviceV1Event_rotation_default: 1
  of RiverLibinputDeviceV1Event_rotation_current: 1
  of RiverLibinputDeviceV1Event_done: 2

type RiverLibinputDeviceV1Request* {.size: sizeof(uint32).} = enum
  RiverLibinputDeviceV1Request_destroy
  RiverLibinputDeviceV1Request_set_send_events
  RiverLibinputDeviceV1Request_set_tap
  RiverLibinputDeviceV1Request_set_tap_button_map
  RiverLibinputDeviceV1Request_set_drag
  RiverLibinputDeviceV1Request_set_drag_lock
  RiverLibinputDeviceV1Request_set_three_finger_drag
  RiverLibinputDeviceV1Request_set_calibration_matrix
  RiverLibinputDeviceV1Request_set_accel_profile
  RiverLibinputDeviceV1Request_set_accel_speed
  RiverLibinputDeviceV1Request_apply_accel_config
  RiverLibinputDeviceV1Request_set_natural_scroll
  RiverLibinputDeviceV1Request_set_left_handed
  RiverLibinputDeviceV1Request_set_click_method
  RiverLibinputDeviceV1Request_set_clickfinger_button_map
  RiverLibinputDeviceV1Request_set_middle_emulation
  RiverLibinputDeviceV1Request_set_scroll_method
  RiverLibinputDeviceV1Request_set_scroll_button
  RiverLibinputDeviceV1Request_set_scroll_button_lock
  RiverLibinputDeviceV1Request_set_dwt
  RiverLibinputDeviceV1Request_set_dwtp
  RiverLibinputDeviceV1Request_set_rotation
proc since*(e: RiverLibinputDeviceV1Request): int =
  case e
  of RiverLibinputDeviceV1Request_destroy: 1
  of RiverLibinputDeviceV1Request_set_send_events: 1
  of RiverLibinputDeviceV1Request_set_tap: 1
  of RiverLibinputDeviceV1Request_set_tap_button_map: 1
  of RiverLibinputDeviceV1Request_set_drag: 1
  of RiverLibinputDeviceV1Request_set_drag_lock: 1
  of RiverLibinputDeviceV1Request_set_three_finger_drag: 1
  of RiverLibinputDeviceV1Request_set_calibration_matrix: 1
  of RiverLibinputDeviceV1Request_set_accel_profile: 1
  of RiverLibinputDeviceV1Request_set_accel_speed: 1
  of RiverLibinputDeviceV1Request_apply_accel_config: 1
  of RiverLibinputDeviceV1Request_set_natural_scroll: 1
  of RiverLibinputDeviceV1Request_set_left_handed: 1
  of RiverLibinputDeviceV1Request_set_click_method: 1
  of RiverLibinputDeviceV1Request_set_clickfinger_button_map: 1
  of RiverLibinputDeviceV1Request_set_middle_emulation: 1
  of RiverLibinputDeviceV1Request_set_scroll_method: 1
  of RiverLibinputDeviceV1Request_set_scroll_button: 1
  of RiverLibinputDeviceV1Request_set_scroll_button_lock: 1
  of RiverLibinputDeviceV1Request_set_dwt: 1
  of RiverLibinputDeviceV1Request_set_dwtp: 1
  of RiverLibinputDeviceV1Request_set_rotation: 1

type RiverLibinputAccelConfigV1Request* {.size: sizeof(uint32).} = enum
  RiverLibinputAccelConfigV1Request_destroy
  RiverLibinputAccelConfigV1Request_set_points
proc since*(e: RiverLibinputAccelConfigV1Request): int =
  case e
  of RiverLibinputAccelConfigV1Request_destroy: 1
  of RiverLibinputAccelConfigV1Request_set_points: 1

type RiverLibinputResultV1Event* {.size: sizeof(uint32).} = enum
  RiverLibinputResultV1Event_success
  RiverLibinputResultV1Event_unsupported
  RiverLibinputResultV1Event_invalid
proc since*(e: RiverLibinputResultV1Event): int =
  case e
  of RiverLibinputResultV1Event_success: 1
  of RiverLibinputResultV1Event_unsupported: 1
  of RiverLibinputResultV1Event_invalid: 1

riverLibinputConfigV1_types = [
  nil,
  addr river_libinput_accel_config_v1_interface,
  nil,
  addr river_libinput_device_v1_interface,
  addr river_libinput_result_v1_interface,
  nil,
  addr river_libinput_result_v1_interface,
  nil,
  addr river_libinput_result_v1_interface,
  nil,
  addr river_libinput_result_v1_interface,
  nil,
  addr river_libinput_result_v1_interface,
  nil,
  addr river_libinput_result_v1_interface,
  nil,
  addr river_libinput_result_v1_interface,
  nil,
  addr river_libinput_result_v1_interface,
  nil,
  addr river_libinput_result_v1_interface,
  nil,
  addr river_libinput_result_v1_interface,
  addr river_libinput_accel_config_v1_interface,
  addr river_libinput_result_v1_interface,
  nil,
  addr river_libinput_result_v1_interface,
  nil,
  addr river_libinput_result_v1_interface,
  nil,
  addr river_libinput_result_v1_interface,
  nil,
  addr river_libinput_result_v1_interface,
  nil,
  addr river_libinput_result_v1_interface,
  nil,
  addr river_libinput_result_v1_interface,
  nil,
  addr river_libinput_result_v1_interface,
  nil,
  addr river_libinput_result_v1_interface,
  nil,
  addr river_libinput_result_v1_interface,
  nil,
  addr river_libinput_result_v1_interface,
  nil,
  addr river_input_device_v1_interface,
  addr river_libinput_result_v1_interface,
  nil,
  nil,
  nil,
]


