# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/server
import wayland/native/common
import protocols/river_input_management/server as river_input_management_server
import code
export code

## The river_libinput_config_v1 SERVER protocol
## ############################################
## 
## Interfaces
## ==========
## 
## * river_libinput_config_v1
## * river_libinput_device_v1
## * river_libinput_accel_config_v1
## * river_libinput_result_v1
## 
## Copyright
## =========
## 
## SPDX-FileCopyrightText: © 2025 Isaac Freund
## SPDX-License-Identifier: MIT
## 
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to
## deal in the Software without restriction, including without limitation the
## rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
## sell copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
## 
## The above copyright notice and this permission notice shall be included in
## all copies or substantial portions of the Software.
## 
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
## IN THE SOFTWARE.
## 

type RiverLibinputConfigV1Interface* = object
  stop*: proc(
    client: ptr Client;
    resource: ptr Resource;
  ) {.nimcall.}
  destroy*: proc(
    client: ptr Client;
    resource: ptr Resource;
  ) {.nimcall.}
  createAccelConfig*: proc(
    client: ptr Client;
    resource: ptr Resource;
    id: uint32;
    profile: uint32;
  ) {.nimcall.}

proc riverLibinputConfigV1SendFinished*(resource: ptr Resource) {.inline, exportc: "river_libinput_config_v1_send_finished".} =
  ## Sends an finished event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputConfigV1Event_finished.ord)

proc riverLibinputConfigV1SendLibinputDevice*(resource: ptr Resource; id: ptr Resource) {.inline, exportc: "river_libinput_config_v1_send_libinput_device".} =
  ## Sends an libinput_device event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputConfigV1Event_libinput_device.ord, id)

type RiverLibinputDeviceV1Interface* = object
  destroy*: proc(
    client: ptr Client;
    resource: ptr Resource;
  ) {.nimcall.}
  setSendEvents*: proc(
    client: ptr Client;
    resource: ptr Resource;
    result: uint32;
    mode: uint32;
  ) {.nimcall.}
  setTap*: proc(
    client: ptr Client;
    resource: ptr Resource;
    result: uint32;
    state: uint32;
  ) {.nimcall.}
  setTapButtonMap*: proc(
    client: ptr Client;
    resource: ptr Resource;
    result: uint32;
    buttonMap: uint32;
  ) {.nimcall.}
  setDrag*: proc(
    client: ptr Client;
    resource: ptr Resource;
    result: uint32;
    state: uint32;
  ) {.nimcall.}
  setDragLock*: proc(
    client: ptr Client;
    resource: ptr Resource;
    result: uint32;
    state: uint32;
  ) {.nimcall.}
  setThreeFingerDrag*: proc(
    client: ptr Client;
    resource: ptr Resource;
    result: uint32;
    state: uint32;
  ) {.nimcall.}
  setCalibrationMatrix*: proc(
    client: ptr Client;
    resource: ptr Resource;
    result: uint32;
    matrix: ptr Array;
  ) {.nimcall.}
  setAccelProfile*: proc(
    client: ptr Client;
    resource: ptr Resource;
    result: uint32;
    profile: uint32;
  ) {.nimcall.}
  setAccelSpeed*: proc(
    client: ptr Client;
    resource: ptr Resource;
    result: uint32;
    speed: ptr Array;
  ) {.nimcall.}
  applyAccelConfig*: proc(
    client: ptr Client;
    resource: ptr Resource;
    result: uint32;
    config: ptr Resource;
  ) {.nimcall.}
  setNaturalScroll*: proc(
    client: ptr Client;
    resource: ptr Resource;
    result: uint32;
    state: uint32;
  ) {.nimcall.}
  setLeftHanded*: proc(
    client: ptr Client;
    resource: ptr Resource;
    result: uint32;
    state: uint32;
  ) {.nimcall.}
  setClickMethod*: proc(
    client: ptr Client;
    resource: ptr Resource;
    result: uint32;
    `method`: uint32;
  ) {.nimcall.}
  setClickfingerButtonMap*: proc(
    client: ptr Client;
    resource: ptr Resource;
    result: uint32;
    buttonMap: uint32;
  ) {.nimcall.}
  setMiddleEmulation*: proc(
    client: ptr Client;
    resource: ptr Resource;
    result: uint32;
    state: uint32;
  ) {.nimcall.}
  setScrollMethod*: proc(
    client: ptr Client;
    resource: ptr Resource;
    result: uint32;
    `method`: uint32;
  ) {.nimcall.}
  setScrollButton*: proc(
    client: ptr Client;
    resource: ptr Resource;
    result: uint32;
    button: uint32;
  ) {.nimcall.}
  setScrollButtonLock*: proc(
    client: ptr Client;
    resource: ptr Resource;
    result: uint32;
    state: uint32;
  ) {.nimcall.}
  setDwt*: proc(
    client: ptr Client;
    resource: ptr Resource;
    result: uint32;
    state: uint32;
  ) {.nimcall.}
  setDwtp*: proc(
    client: ptr Client;
    resource: ptr Resource;
    result: uint32;
    state: uint32;
  ) {.nimcall.}
  setRotation*: proc(
    client: ptr Client;
    resource: ptr Resource;
    result: uint32;
    angle: uint32;
  ) {.nimcall.}

proc riverLibinputDeviceV1SendRemoved*(resource: ptr Resource) {.inline, exportc: "river_libinput_device_v1_send_removed".} =
  ## Sends an removed event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_removed.ord)

proc riverLibinputDeviceV1SendInputDevice*(resource: ptr Resource; device: ptr Resource) {.inline, exportc: "river_libinput_device_v1_send_input_device".} =
  ## Sends an input_device event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_input_device.ord, device)

proc riverLibinputDeviceV1SendSendEventsSupport*(resource: ptr Resource; modes: uint32) {.inline, exportc: "river_libinput_device_v1_send_send_events_support".} =
  ## Sends an send_events_support event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_send_events_support.ord, modes)

proc riverLibinputDeviceV1SendSendEventsDefault*(resource: ptr Resource; mode: uint32) {.inline, exportc: "river_libinput_device_v1_send_send_events_default".} =
  ## Sends an send_events_default event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_send_events_default.ord, mode)

proc riverLibinputDeviceV1SendSendEventsCurrent*(resource: ptr Resource; mode: uint32) {.inline, exportc: "river_libinput_device_v1_send_send_events_current".} =
  ## Sends an send_events_current event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_send_events_current.ord, mode)

proc riverLibinputDeviceV1SendTapSupport*(resource: ptr Resource; fingerCount: int32) {.inline, exportc: "river_libinput_device_v1_send_tap_support".} =
  ## Sends an tap_support event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_tap_support.ord, fingerCount)

proc riverLibinputDeviceV1SendTapDefault*(resource: ptr Resource; state: uint32) {.inline, exportc: "river_libinput_device_v1_send_tap_default".} =
  ## Sends an tap_default event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_tap_default.ord, state)

proc riverLibinputDeviceV1SendTapCurrent*(resource: ptr Resource; state: uint32) {.inline, exportc: "river_libinput_device_v1_send_tap_current".} =
  ## Sends an tap_current event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_tap_current.ord, state)

proc riverLibinputDeviceV1SendTapButtonMapDefault*(resource: ptr Resource; buttonMap: uint32) {.inline, exportc: "river_libinput_device_v1_send_tap_button_map_default".} =
  ## Sends an tap_button_map_default event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_tap_button_map_default.ord, buttonMap)

proc riverLibinputDeviceV1SendTapButtonMapCurrent*(resource: ptr Resource; buttonMap: uint32) {.inline, exportc: "river_libinput_device_v1_send_tap_button_map_current".} =
  ## Sends an tap_button_map_current event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_tap_button_map_current.ord, buttonMap)

proc riverLibinputDeviceV1SendDragDefault*(resource: ptr Resource; state: uint32) {.inline, exportc: "river_libinput_device_v1_send_drag_default".} =
  ## Sends an drag_default event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_drag_default.ord, state)

proc riverLibinputDeviceV1SendDragCurrent*(resource: ptr Resource; state: uint32) {.inline, exportc: "river_libinput_device_v1_send_drag_current".} =
  ## Sends an drag_current event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_drag_current.ord, state)

proc riverLibinputDeviceV1SendDragLockDefault*(resource: ptr Resource; state: uint32) {.inline, exportc: "river_libinput_device_v1_send_drag_lock_default".} =
  ## Sends an drag_lock_default event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_drag_lock_default.ord, state)

proc riverLibinputDeviceV1SendDragLockCurrent*(resource: ptr Resource; state: uint32) {.inline, exportc: "river_libinput_device_v1_send_drag_lock_current".} =
  ## Sends an drag_lock_current event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_drag_lock_current.ord, state)

proc riverLibinputDeviceV1SendThreeFingerDragSupport*(resource: ptr Resource; fingerCount: int32) {.inline, exportc: "river_libinput_device_v1_send_three_finger_drag_support".} =
  ## Sends an three_finger_drag_support event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_three_finger_drag_support.ord, fingerCount)

proc riverLibinputDeviceV1SendThreeFingerDragDefault*(resource: ptr Resource; state: uint32) {.inline, exportc: "river_libinput_device_v1_send_three_finger_drag_default".} =
  ## Sends an three_finger_drag_default event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_three_finger_drag_default.ord, state)

proc riverLibinputDeviceV1SendThreeFingerDragCurrent*(resource: ptr Resource; state: uint32) {.inline, exportc: "river_libinput_device_v1_send_three_finger_drag_current".} =
  ## Sends an three_finger_drag_current event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_three_finger_drag_current.ord, state)

proc riverLibinputDeviceV1SendCalibrationMatrixSupport*(resource: ptr Resource; supported: int32) {.inline, exportc: "river_libinput_device_v1_send_calibration_matrix_support".} =
  ## Sends an calibration_matrix_support event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *supported*: boolean
  resource.post_event(RiverLibinputDeviceV1Event_calibration_matrix_support.ord, supported)

proc riverLibinputDeviceV1SendCalibrationMatrixDefault*(resource: ptr Resource; matrix: ptr Array) {.inline, exportc: "river_libinput_device_v1_send_calibration_matrix_default".} =
  ## Sends an calibration_matrix_default event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *matrix*: array of 6 floats
  resource.post_event(RiverLibinputDeviceV1Event_calibration_matrix_default.ord, matrix)

proc riverLibinputDeviceV1SendCalibrationMatrixCurrent*(resource: ptr Resource; matrix: ptr Array) {.inline, exportc: "river_libinput_device_v1_send_calibration_matrix_current".} =
  ## Sends an calibration_matrix_current event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *matrix*: array of 6 floats
  resource.post_event(RiverLibinputDeviceV1Event_calibration_matrix_current.ord, matrix)

proc riverLibinputDeviceV1SendAccelProfilesSupport*(resource: ptr Resource; profiles: uint32) {.inline, exportc: "river_libinput_device_v1_send_accel_profiles_support".} =
  ## Sends an accel_profiles_support event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_accel_profiles_support.ord, profiles)

proc riverLibinputDeviceV1SendAccelProfileDefault*(resource: ptr Resource; profile: uint32) {.inline, exportc: "river_libinput_device_v1_send_accel_profile_default".} =
  ## Sends an accel_profile_default event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_accel_profile_default.ord, profile)

proc riverLibinputDeviceV1SendAccelProfileCurrent*(resource: ptr Resource; profile: uint32) {.inline, exportc: "river_libinput_device_v1_send_accel_profile_current".} =
  ## Sends an accel_profile_current event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_accel_profile_current.ord, profile)

proc riverLibinputDeviceV1SendAccelSpeedDefault*(resource: ptr Resource; speed: ptr Array) {.inline, exportc: "river_libinput_device_v1_send_accel_speed_default".} =
  ## Sends an accel_speed_default event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *speed*: double
  resource.post_event(RiverLibinputDeviceV1Event_accel_speed_default.ord, speed)

proc riverLibinputDeviceV1SendAccelSpeedCurrent*(resource: ptr Resource; speed: ptr Array) {.inline, exportc: "river_libinput_device_v1_send_accel_speed_current".} =
  ## Sends an accel_speed_current event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *speed*: double
  resource.post_event(RiverLibinputDeviceV1Event_accel_speed_current.ord, speed)

proc riverLibinputDeviceV1SendNaturalScrollSupport*(resource: ptr Resource; supported: int32) {.inline, exportc: "river_libinput_device_v1_send_natural_scroll_support".} =
  ## Sends an natural_scroll_support event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *supported*: boolean
  resource.post_event(RiverLibinputDeviceV1Event_natural_scroll_support.ord, supported)

proc riverLibinputDeviceV1SendNaturalScrollDefault*(resource: ptr Resource; state: uint32) {.inline, exportc: "river_libinput_device_v1_send_natural_scroll_default".} =
  ## Sends an natural_scroll_default event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_natural_scroll_default.ord, state)

proc riverLibinputDeviceV1SendNaturalScrollCurrent*(resource: ptr Resource; state: uint32) {.inline, exportc: "river_libinput_device_v1_send_natural_scroll_current".} =
  ## Sends an natural_scroll_current event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_natural_scroll_current.ord, state)

proc riverLibinputDeviceV1SendLeftHandedSupport*(resource: ptr Resource; supported: int32) {.inline, exportc: "river_libinput_device_v1_send_left_handed_support".} =
  ## Sends an left_handed_support event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *supported*: boolean
  resource.post_event(RiverLibinputDeviceV1Event_left_handed_support.ord, supported)

proc riverLibinputDeviceV1SendLeftHandedDefault*(resource: ptr Resource; state: uint32) {.inline, exportc: "river_libinput_device_v1_send_left_handed_default".} =
  ## Sends an left_handed_default event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_left_handed_default.ord, state)

proc riverLibinputDeviceV1SendLeftHandedCurrent*(resource: ptr Resource; state: uint32) {.inline, exportc: "river_libinput_device_v1_send_left_handed_current".} =
  ## Sends an left_handed_current event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_left_handed_current.ord, state)

proc riverLibinputDeviceV1SendClickMethodSupport*(resource: ptr Resource; methods: uint32) {.inline, exportc: "river_libinput_device_v1_send_click_method_support".} =
  ## Sends an click_method_support event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_click_method_support.ord, methods)

proc riverLibinputDeviceV1SendClickMethodDefault*(resource: ptr Resource; `method`: uint32) {.inline, exportc: "river_libinput_device_v1_send_click_method_default".} =
  ## Sends an click_method_default event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_click_method_default.ord, `method`)

proc riverLibinputDeviceV1SendClickMethodCurrent*(resource: ptr Resource; `method`: uint32) {.inline, exportc: "river_libinput_device_v1_send_click_method_current".} =
  ## Sends an click_method_current event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_click_method_current.ord, `method`)

proc riverLibinputDeviceV1SendClickfingerButtonMapDefault*(resource: ptr Resource; buttonMap: uint32) {.inline, exportc: "river_libinput_device_v1_send_clickfinger_button_map_default".} =
  ## Sends an clickfinger_button_map_default event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_clickfinger_button_map_default.ord, buttonMap)

proc riverLibinputDeviceV1SendClickfingerButtonMapCurrent*(resource: ptr Resource; buttonMap: uint32) {.inline, exportc: "river_libinput_device_v1_send_clickfinger_button_map_current".} =
  ## Sends an clickfinger_button_map_current event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_clickfinger_button_map_current.ord, buttonMap)

proc riverLibinputDeviceV1SendMiddleEmulationSupport*(resource: ptr Resource; supported: int32) {.inline, exportc: "river_libinput_device_v1_send_middle_emulation_support".} =
  ## Sends an middle_emulation_support event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *supported*: boolean
  resource.post_event(RiverLibinputDeviceV1Event_middle_emulation_support.ord, supported)

proc riverLibinputDeviceV1SendMiddleEmulationDefault*(resource: ptr Resource; state: uint32) {.inline, exportc: "river_libinput_device_v1_send_middle_emulation_default".} =
  ## Sends an middle_emulation_default event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_middle_emulation_default.ord, state)

proc riverLibinputDeviceV1SendMiddleEmulationCurrent*(resource: ptr Resource; state: uint32) {.inline, exportc: "river_libinput_device_v1_send_middle_emulation_current".} =
  ## Sends an middle_emulation_current event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_middle_emulation_current.ord, state)

proc riverLibinputDeviceV1SendScrollMethodSupport*(resource: ptr Resource; methods: uint32) {.inline, exportc: "river_libinput_device_v1_send_scroll_method_support".} =
  ## Sends an scroll_method_support event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_scroll_method_support.ord, methods)

proc riverLibinputDeviceV1SendScrollMethodDefault*(resource: ptr Resource; `method`: uint32) {.inline, exportc: "river_libinput_device_v1_send_scroll_method_default".} =
  ## Sends an scroll_method_default event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_scroll_method_default.ord, `method`)

proc riverLibinputDeviceV1SendScrollMethodCurrent*(resource: ptr Resource; `method`: uint32) {.inline, exportc: "river_libinput_device_v1_send_scroll_method_current".} =
  ## Sends an scroll_method_current event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_scroll_method_current.ord, `method`)

proc riverLibinputDeviceV1SendScrollButtonDefault*(resource: ptr Resource; button: uint32) {.inline, exportc: "river_libinput_device_v1_send_scroll_button_default".} =
  ## Sends an scroll_button_default event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_scroll_button_default.ord, button)

proc riverLibinputDeviceV1SendScrollButtonCurrent*(resource: ptr Resource; button: uint32) {.inline, exportc: "river_libinput_device_v1_send_scroll_button_current".} =
  ## Sends an scroll_button_current event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_scroll_button_current.ord, button)

proc riverLibinputDeviceV1SendScrollButtonLockDefault*(resource: ptr Resource; state: uint32) {.inline, exportc: "river_libinput_device_v1_send_scroll_button_lock_default".} =
  ## Sends an scroll_button_lock_default event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_scroll_button_lock_default.ord, state)

proc riverLibinputDeviceV1SendScrollButtonLockCurrent*(resource: ptr Resource; state: uint32) {.inline, exportc: "river_libinput_device_v1_send_scroll_button_lock_current".} =
  ## Sends an scroll_button_lock_current event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_scroll_button_lock_current.ord, state)

proc riverLibinputDeviceV1SendDwtSupport*(resource: ptr Resource; supported: int32) {.inline, exportc: "river_libinput_device_v1_send_dwt_support".} =
  ## Sends an dwt_support event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *supported*: boolean
  resource.post_event(RiverLibinputDeviceV1Event_dwt_support.ord, supported)

proc riverLibinputDeviceV1SendDwtDefault*(resource: ptr Resource; state: uint32) {.inline, exportc: "river_libinput_device_v1_send_dwt_default".} =
  ## Sends an dwt_default event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_dwt_default.ord, state)

proc riverLibinputDeviceV1SendDwtCurrent*(resource: ptr Resource; state: uint32) {.inline, exportc: "river_libinput_device_v1_send_dwt_current".} =
  ## Sends an dwt_current event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_dwt_current.ord, state)

proc riverLibinputDeviceV1SendDwtpSupport*(resource: ptr Resource; supported: int32) {.inline, exportc: "river_libinput_device_v1_send_dwtp_support".} =
  ## Sends an dwtp_support event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *supported*: boolean
  resource.post_event(RiverLibinputDeviceV1Event_dwtp_support.ord, supported)

proc riverLibinputDeviceV1SendDwtpDefault*(resource: ptr Resource; state: uint32) {.inline, exportc: "river_libinput_device_v1_send_dwtp_default".} =
  ## Sends an dwtp_default event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_dwtp_default.ord, state)

proc riverLibinputDeviceV1SendDwtpCurrent*(resource: ptr Resource; state: uint32) {.inline, exportc: "river_libinput_device_v1_send_dwtp_current".} =
  ## Sends an dwtp_current event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_dwtp_current.ord, state)

proc riverLibinputDeviceV1SendRotationSupport*(resource: ptr Resource; supported: int32) {.inline, exportc: "river_libinput_device_v1_send_rotation_support".} =
  ## Sends an rotation_support event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *supported*: boolean
  resource.post_event(RiverLibinputDeviceV1Event_rotation_support.ord, supported)

proc riverLibinputDeviceV1SendRotationDefault*(resource: ptr Resource; angle: uint32) {.inline, exportc: "river_libinput_device_v1_send_rotation_default".} =
  ## Sends an rotation_default event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_rotation_default.ord, angle)

proc riverLibinputDeviceV1SendRotationCurrent*(resource: ptr Resource; angle: uint32) {.inline, exportc: "river_libinput_device_v1_send_rotation_current".} =
  ## Sends an rotation_current event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_rotation_current.ord, angle)

proc riverLibinputDeviceV1SendDone*(resource: ptr Resource) {.inline, exportc: "river_libinput_device_v1_send_done".} =
  ## Sends an done event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputDeviceV1Event_done.ord)

type RiverLibinputAccelConfigV1Interface* = object
  destroy*: proc(
    client: ptr Client;
    resource: ptr Resource;
  ) {.nimcall.}
  setPoints*: proc(
    client: ptr Client;
    resource: ptr Resource;
    result: uint32;
    `type`: uint32;
    step: ptr Array;
    points: ptr Array;
  ) {.nimcall.}

proc riverLibinputResultV1SendSuccess*(resource: ptr Resource) {.inline, exportc: "river_libinput_result_v1_send_success".} =
  ## Sends an success event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputResultV1Event_success.ord)

proc riverLibinputResultV1SendUnsupported*(resource: ptr Resource) {.inline, exportc: "river_libinput_result_v1_send_unsupported".} =
  ## Sends an unsupported event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputResultV1Event_unsupported.ord)

proc riverLibinputResultV1SendInvalid*(resource: ptr Resource) {.inline, exportc: "river_libinput_result_v1_send_invalid".} =
  ## Sends an invalid event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverLibinputResultV1Event_invalid.ord)

