# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/client
import wayland/native/common
import protocols/river/client as river_client
import code
export code

## The river_xkb_bindings_v1 CLIENT protocol
## #########################################
## 
## Interfaces
## ==========
## 
## * river_xkb_bindings_v1
## * river_xkb_binding_v1
## * river_xkb_bindings_seat_v1
## 
## Copyright
## =========
## 
## SPDX-FileCopyrightText: © 2025 Isaac Freund
## SPDX-License-Identifier: MIT
## 
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to
## deal in the Software without restriction, including without limitation the
## rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
## sell copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
## 
## The above copyright notice and this permission notice shall be included in
## all copies or substantial portions of the Software.
## 
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
## IN THE SOFTWARE.
## 

proc setUserData*(riverXkbBindingsV1: ptr RiverXkbBindingsV1; userData: pointer) {.inline.} =
  cast[ptr Proxy](riverXkbBindingsV1).set_user_data(user_data)
proc getUserData*(riverXkbBindingsV1: ptr RiverXkbBindingsV1): pointer {.inline.} =
  cast[ptr Proxy](riverXkbBindingsV1).get_user_data()
proc getVersion*(riverXkbBindingsV1: ptr RiverXkbBindingsV1): uint32 {.inline.} =
  cast[ptr Proxy](riverXkbBindingsV1).get_version()
proc destroy*(riverXkbBindingsV1: ptr RiverXkbBindingsV1) {.inline.} =
  ## destroy the river_xkb_bindings_v1 object
  ## 
  ## This request indicates that the client will no longer use the
  ## river_xkb_bindings_v1 object.
  ## 
  cast[ptr Proxy](riverXkbBindingsV1).marshal_flags(RiverXkbBindingsV1Request_destroy.ord, nil, cast[ptr Proxy](riverXkbBindingsV1).get_version(), WL_MARSHAL_FLAG_DESTROY)
proc getXkbBinding*(riverXkbBindingsV1: ptr RiverXkbBindingsV1; seat: ptr RiverSeatV1; keysym: uint32; modifiers: uint32): ptr RiverXkbBindingV1 {.inline.} =
  ## define a new xkbcommon key binding
  ## 
  ## Define a key binding for the given seat in terms of an xkbcommon keysym
  ## and other configurable properties.
  ## 
  ## The new key binding is not enabled until initial configuration is
  ## completed and the enable request is made during a manage sequence.
  ## 
  cast[ptr RiverXkbBindingV1](cast[ptr Proxy](riverXkbBindingsV1).marshal_flags(RiverXkbBindingsV1Request_get_xkb_binding.ord, addr river_xkb_binding_v1_interface, cast[ptr Proxy](riverXkbBindingsV1).get_version(), 0, seat, nil, keysym, modifiers))
proc getSeat*(riverXkbBindingsV1: ptr RiverXkbBindingsV1; seat: ptr RiverSeatV1): ptr RiverXkbBindingsSeatV1 {.inline.} =
  ## manage seat-specific state
  ## 
  ## Create an object to manage seat-specific xkb bindings state.
  ## 
  ## It is a protocol error to make this request more than once for a given
  ## river_seat_v1 object.
  ## 
  cast[ptr RiverXkbBindingsSeatV1](cast[ptr Proxy](riverXkbBindingsV1).marshal_flags(RiverXkbBindingsV1Request_get_seat.ord, addr river_xkb_bindings_seat_v1_interface, cast[ptr Proxy](riverXkbBindingsV1).get_version(), 0, nil, seat))
type RiverXkbBindingV1Listener* = object
  pressed*: proc(
    data: pointer;
    riverXkbBindingV1: ptr RiverXkbBindingV1;
  ) {.nimcall.}
  released*: proc(
    data: pointer;
    riverXkbBindingV1: ptr RiverXkbBindingV1;
  ) {.nimcall.}
  stopRepeat*: proc(
    data: pointer;
    riverXkbBindingV1: ptr RiverXkbBindingV1;
  ) {.nimcall.}
proc addListener*(riverXkbBindingV1: ptr RiverXkbBindingV1; listener: ptr RiverXkbBindingV1Listener; data: pointer): int {.inline.} =
  cast[ptr Proxy](riverXkbBindingV1).add_listener(listener, data)

proc setUserData*(riverXkbBindingV1: ptr RiverXkbBindingV1; userData: pointer) {.inline.} =
  cast[ptr Proxy](riverXkbBindingV1).set_user_data(user_data)
proc getUserData*(riverXkbBindingV1: ptr RiverXkbBindingV1): pointer {.inline.} =
  cast[ptr Proxy](riverXkbBindingV1).get_user_data()
proc getVersion*(riverXkbBindingV1: ptr RiverXkbBindingV1): uint32 {.inline.} =
  cast[ptr Proxy](riverXkbBindingV1).get_version()
proc destroy*(riverXkbBindingV1: ptr RiverXkbBindingV1) {.inline.} =
  ## destroy the xkb binding object
  ## 
  ## This request indicates that the client will no longer use the xkb key
  ## binding object and that it may be safely destroyed.
  ## 
  cast[ptr Proxy](riverXkbBindingV1).marshal_flags(RiverXkbBindingV1Request_destroy.ord, nil, cast[ptr Proxy](riverXkbBindingV1).get_version(), WL_MARSHAL_FLAG_DESTROY)
proc setLayoutOverride*(riverXkbBindingV1: ptr RiverXkbBindingV1; layout: uint32) {.inline.} =
  ## override currently active xkb layout
  ## 
  ## Specify an xkb layout that should be used to translate key events for
  ## the purpose of triggering this key binding irrespective of the currently
  ## active xkb layout.
  ## 
  ## The layout argument is a 0-indexed xkbcommon layout number for the
  ## keyboard that generated the key event.
  ## 
  ## If this request is never made, the currently active xkb layout of the
  ## keyboard that generated the key event will be used.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverXkbBindingV1).marshal_flags(RiverXkbBindingV1Request_set_layout_override.ord, nil, cast[ptr Proxy](riverXkbBindingV1).get_version(), 0, layout)
proc enable*(riverXkbBindingV1: ptr RiverXkbBindingV1) {.inline.} =
  ## enable the key binding
  ## 
  ## This request should be made after all initial configuration has been
  ## completed and the window manager wishes the key binding to be able to be
  ## triggered.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverXkbBindingV1).marshal_flags(RiverXkbBindingV1Request_enable.ord, nil, cast[ptr Proxy](riverXkbBindingV1).get_version(), 0)
proc disable*(riverXkbBindingV1: ptr RiverXkbBindingV1) {.inline.} =
  ## disable the key binding
  ## 
  ## This request may be used to temporarily disable the key binding. It may
  ## be later re-enabled with the enable request.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverXkbBindingV1).marshal_flags(RiverXkbBindingV1Request_disable.ord, nil, cast[ptr Proxy](riverXkbBindingV1).get_version(), 0)
type RiverXkbBindingsSeatV1Listener* = object
  ateUnboundKey*: proc(
    data: pointer;
    riverXkbBindingsSeatV1: ptr RiverXkbBindingsSeatV1;
  ) {.nimcall.}
  modifiersUpdate*: proc(
    data: pointer;
    riverXkbBindingsSeatV1: ptr RiverXkbBindingsSeatV1;
    old: uint32;
    new: uint32;
  ) {.nimcall.}
proc addListener*(riverXkbBindingsSeatV1: ptr RiverXkbBindingsSeatV1; listener: ptr RiverXkbBindingsSeatV1Listener; data: pointer): int {.inline.} =
  cast[ptr Proxy](riverXkbBindingsSeatV1).add_listener(listener, data)

proc setUserData*(riverXkbBindingsSeatV1: ptr RiverXkbBindingsSeatV1; userData: pointer) {.inline.} =
  cast[ptr Proxy](riverXkbBindingsSeatV1).set_user_data(user_data)
proc getUserData*(riverXkbBindingsSeatV1: ptr RiverXkbBindingsSeatV1): pointer {.inline.} =
  cast[ptr Proxy](riverXkbBindingsSeatV1).get_user_data()
proc getVersion*(riverXkbBindingsSeatV1: ptr RiverXkbBindingsSeatV1): uint32 {.inline.} =
  cast[ptr Proxy](riverXkbBindingsSeatV1).get_version()
proc destroy*(riverXkbBindingsSeatV1: ptr RiverXkbBindingsSeatV1) {.inline.} =
  ## destroy the object
  ## 
  ## This request indicates that the client will no longer use the object and
  ## that it may be safely destroyed.
  ## 
  cast[ptr Proxy](riverXkbBindingsSeatV1).marshal_flags(RiverXkbBindingsSeatV1Request_destroy.ord, nil, cast[ptr Proxy](riverXkbBindingsSeatV1).get_version(), WL_MARSHAL_FLAG_DESTROY)
proc ensureNextKeyEaten*(riverXkbBindingsSeatV1: ptr RiverXkbBindingsSeatV1) {.inline.} =
  ## ensure the next key press event is eaten
  ## 
  ## Ensure that the next non-modifier key press and corresponding release
  ## events for this seat are not sent to the currently focused surface.
  ## 
  ## If the next non-modifier key press triggers a binding, the
  ## pressed/released events are sent to the river_xkb_binding_v1 object as
  ## usual.
  ## 
  ## If the next non-modifier key press does not trigger a binding, the
  ## ate_unbound_key event is sent instead.
  ## 
  ## Rationale: the window manager may wish to implement "chorded"
  ## keybindings where triggering a binding activates a "submap" with a
  ## different set of keybindings. Without a way to eat the next key
  ## press event, there is no good way for the window manager to know that it
  ## should error out and exit the submap when a key not bound in the submap
  ## is pressed.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverXkbBindingsSeatV1).marshal_flags(RiverXkbBindingsSeatV1Request_ensure_next_key_eaten.ord, nil, cast[ptr Proxy](riverXkbBindingsSeatV1).get_version(), 0)
proc cancelEnsureNextKeyEaten*(riverXkbBindingsSeatV1: ptr RiverXkbBindingsSeatV1) {.inline.} =
  ## cancel an ensure_next_key_eaten request
  ## 
  ## This requests cancels the effect of the latest ensure_next_key_eaten
  ## request if no key has been eaten due to the request yet. This request
  ## has no effect if a key has already been eaten or no
  ## ensure_next_key_eaten was made.
  ## 
  ## Rationale: the window manager may wish cancel an uncompleted "chorded"
  ## keybinding after a timeout of a few seconds. Note that since this
  ## timeout use-case requires the window manager to trigger a manage sequence
  ## with the river_window_manager_v1.manage_dirty request it is possible that
  ## the ate_unbound_key key event may be sent before the window manager has
  ## a chance to make the cancel_ensure_next_key_eaten request.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverXkbBindingsSeatV1).marshal_flags(RiverXkbBindingsSeatV1Request_cancel_ensure_next_key_eaten.ord, nil, cast[ptr Proxy](riverXkbBindingsSeatV1).get_version(), 0)
proc modifiersWatch*(riverXkbBindingsSeatV1: ptr RiverXkbBindingsSeatV1; modifiers: uint32) {.inline.} =
  ## watch for change in active modifiers
  ## 
  ## Request that the server send the modifiers_update event whenever a state
  ## change occurs for at least one of the modifiers specified by the
  ## modifiers argument.
  ## 
  ## The window manager should make this request with the modifiers argument
  ## set to 0 when it no longer wishes to take action based on a change in
  ## modifiers.
  ## 
  ## This request modifies window management state and may only be made as
  ## part of a manage sequence, see the river_window_manager_v1 description.
  ## 
  cast[ptr Proxy](riverXkbBindingsSeatV1).marshal_flags(RiverXkbBindingsSeatV1Request_modifiers_watch.ord, nil, cast[ptr Proxy](riverXkbBindingsSeatV1).get_version(), 0, modifiers)
