# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code
import protocols/river/code as river_code

var riverXkbBindingsV1_types: array[8, ptr Interface]
type RiverXkbBindingV1* = object
type RiverXkbBindingsSeatV1* = object
type RiverXkbBindingsV1* = object

let
  river_xkb_bindings_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr river_xkb_bindings_v1_types[0]),
    Message(name: "get_xkb_binding", signature: "onuu", types: addr river_xkb_bindings_v1_types[2]),
    Message(name: "get_seat", signature: "2no", types: addr river_xkb_bindings_v1_types[6]),
  ]

  river_xkb_bindings_v1_interface* {.exportc.} = Interface(
    name: "river_xkb_bindings_v1",
    version: 3,
    method_count: 3,
    methods: addr river_xkb_bindings_v1_requests[0],
  )

  river_xkb_binding_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr river_xkb_bindings_v1_types[0]),
    Message(name: "set_layout_override", signature: "u", types: addr river_xkb_bindings_v1_types[0]),
    Message(name: "enable", signature: "", types: addr river_xkb_bindings_v1_types[0]),
    Message(name: "disable", signature: "", types: addr river_xkb_bindings_v1_types[0]),
  ]

  river_xkb_binding_v1_events {.exportc.} = [
    Message(name: "pressed", signature: "", types: addr river_xkb_bindings_v1_types[0]),
    Message(name: "released", signature: "", types: addr river_xkb_bindings_v1_types[0]),
    Message(name: "stop_repeat", signature: "2", types: addr river_xkb_bindings_v1_types[0]),
  ]

  river_xkb_binding_v1_interface* {.exportc.} = Interface(
    name: "river_xkb_binding_v1",
    version: 3,
    method_count: 4,
    methods: addr river_xkb_binding_v1_requests[0],
    event_count: 3,
    events: addr river_xkb_binding_v1_events[0],
  )

  river_xkb_bindings_seat_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "2", types: addr river_xkb_bindings_v1_types[0]),
    Message(name: "ensure_next_key_eaten", signature: "2", types: addr river_xkb_bindings_v1_types[0]),
    Message(name: "cancel_ensure_next_key_eaten", signature: "2", types: addr river_xkb_bindings_v1_types[0]),
    Message(name: "modifiers_watch", signature: "3u", types: addr river_xkb_bindings_v1_types[0]),
  ]

  river_xkb_bindings_seat_v1_events {.exportc.} = [
    Message(name: "ate_unbound_key", signature: "2", types: addr river_xkb_bindings_v1_types[0]),
    Message(name: "modifiers_update", signature: "3uu", types: addr river_xkb_bindings_v1_types[0]),
  ]

  river_xkb_bindings_seat_v1_interface* {.exportc.} = Interface(
    name: "river_xkb_bindings_seat_v1",
    version: 3,
    method_count: 4,
    methods: addr river_xkb_bindings_seat_v1_requests[0],
    event_count: 2,
    events: addr river_xkb_bindings_seat_v1_events[0],
  )


type RiverXkbBindingsV1Error* {.size: sizeof(uint32).} = enum
  error_object_already_created = 0
func since*(e: RiverXkbBindingsV1Error): int =
  case e
  of error_object_already_created: 2
proc isValid*(e: RiverXkbBindingsV1Error; version: int): bool =
  version >= e.since

type RiverXkbBindingsV1Request* {.size: sizeof(uint32).} = enum
  RiverXkbBindingsV1Request_destroy
  RiverXkbBindingsV1Request_get_xkb_binding
  RiverXkbBindingsV1Request_get_seat
proc since*(e: RiverXkbBindingsV1Request): int =
  case e
  of RiverXkbBindingsV1Request_destroy: 1
  of RiverXkbBindingsV1Request_get_xkb_binding: 1
  of RiverXkbBindingsV1Request_get_seat: 2

type RiverXkbBindingV1Event* {.size: sizeof(uint32).} = enum
  RiverXkbBindingV1Event_pressed
  RiverXkbBindingV1Event_released
  RiverXkbBindingV1Event_stop_repeat
proc since*(e: RiverXkbBindingV1Event): int =
  case e
  of RiverXkbBindingV1Event_pressed: 1
  of RiverXkbBindingV1Event_released: 1
  of RiverXkbBindingV1Event_stop_repeat: 2

type RiverXkbBindingV1Request* {.size: sizeof(uint32).} = enum
  RiverXkbBindingV1Request_destroy
  RiverXkbBindingV1Request_set_layout_override
  RiverXkbBindingV1Request_enable
  RiverXkbBindingV1Request_disable
proc since*(e: RiverXkbBindingV1Request): int =
  case e
  of RiverXkbBindingV1Request_destroy: 1
  of RiverXkbBindingV1Request_set_layout_override: 1
  of RiverXkbBindingV1Request_enable: 1
  of RiverXkbBindingV1Request_disable: 1

type RiverXkbBindingsSeatV1Event* {.size: sizeof(uint32).} = enum
  RiverXkbBindingsSeatV1Event_ate_unbound_key
  RiverXkbBindingsSeatV1Event_modifiers_update
proc since*(e: RiverXkbBindingsSeatV1Event): int =
  case e
  of RiverXkbBindingsSeatV1Event_ate_unbound_key: 2
  of RiverXkbBindingsSeatV1Event_modifiers_update: 3

type RiverXkbBindingsSeatV1Request* {.size: sizeof(uint32).} = enum
  RiverXkbBindingsSeatV1Request_destroy
  RiverXkbBindingsSeatV1Request_ensure_next_key_eaten
  RiverXkbBindingsSeatV1Request_cancel_ensure_next_key_eaten
  RiverXkbBindingsSeatV1Request_modifiers_watch
proc since*(e: RiverXkbBindingsSeatV1Request): int =
  case e
  of RiverXkbBindingsSeatV1Request_destroy: 2
  of RiverXkbBindingsSeatV1Request_ensure_next_key_eaten: 2
  of RiverXkbBindingsSeatV1Request_cancel_ensure_next_key_eaten: 2
  of RiverXkbBindingsSeatV1Request_modifiers_watch: 3

riverXkbBindingsV1_types = [
  nil,
  nil,
  addr river_seat_v1_interface,
  addr river_xkb_binding_v1_interface,
  nil,
  nil,
  addr river_xkb_bindings_seat_v1_interface,
  addr river_seat_v1_interface,
]


