# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]: off.}
import wayland/native/server
import wayland/native/common
import protocols/river/server as river_server
import code
export code

## The river_xkb_bindings_v1 SERVER protocol
## #########################################
## 
## Interfaces
## ==========
## 
## * river_xkb_bindings_v1
## * river_xkb_binding_v1
## * river_xkb_bindings_seat_v1
## 
## Copyright
## =========
## 
## SPDX-FileCopyrightText: © 2025 Isaac Freund
## SPDX-License-Identifier: MIT
## 
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to
## deal in the Software without restriction, including without limitation the
## rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
## sell copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
## 
## The above copyright notice and this permission notice shall be included in
## all copies or substantial portions of the Software.
## 
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
## IN THE SOFTWARE.
## 

type RiverXkbBindingsV1Interface* = object
  destroy*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  getXkbBinding*: proc(
    client: ptr Client,
    resource: ptr Resource,
    seat: ptr Resource,
    id: uint32,
    keysym: uint32,
    modifiers: uint32,
  ) {.nimcall.}
  getSeat*: proc(
    client: ptr Client, resource: ptr Resource, id: uint32, seat: ptr Resource
  ) {.nimcall.}

type RiverXkbBindingV1Interface* = object
  destroy*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  setLayoutOverride*:
    proc(client: ptr Client, resource: ptr Resource, layout: uint32) {.nimcall.}
  enable*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  disable*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}

proc riverXkbBindingV1SendPressed*(
    resource: ptr Resource
) {.inline, exportc: "river_xkb_binding_v1_send_pressed".} =
  ## Sends an pressed event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverXkbBindingV1Event_pressed.ord)

proc riverXkbBindingV1SendReleased*(
    resource: ptr Resource
) {.inline, exportc: "river_xkb_binding_v1_send_released".} =
  ## Sends an released event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverXkbBindingV1Event_released.ord)

proc riverXkbBindingV1SendStopRepeat*(
    resource: ptr Resource
) {.inline, exportc: "river_xkb_binding_v1_send_stop_repeat".} =
  ## Sends an stop_repeat event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverXkbBindingV1Event_stop_repeat.ord)

type RiverXkbBindingsSeatV1Interface* = object
  destroy*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  ensureNextKeyEaten*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  cancelEnsureNextKeyEaten*:
    proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  modifiersWatch*:
    proc(client: ptr Client, resource: ptr Resource, modifiers: uint32) {.nimcall.}

proc riverXkbBindingsSeatV1SendAteUnboundKey*(
    resource: ptr Resource
) {.inline, exportc: "river_xkb_bindings_seat_v1_send_ate_unbound_key".} =
  ## Sends an ate_unbound_key event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverXkbBindingsSeatV1Event_ate_unbound_key.ord)

proc riverXkbBindingsSeatV1SendModifiersUpdate*(
    resource: ptr Resource, old: uint32, new: uint32
) {.inline, exportc: "river_xkb_bindings_seat_v1_send_modifiers_update".} =
  ## Sends an modifiers_update event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *old*: previously active modifiers
  ## * *new*: currently active modifiers
  resource.post_event(RiverXkbBindingsSeatV1Event_modifiers_update.ord, old, new)
