# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]: off.}
import wayland/native/client
import wayland/native/common
import code
export code

## The wlr_output_management_unstable_v1 CLIENT protocol
## #####################################################
## 
## Interfaces
## ==========
## 
## * zwlr_output_manager_v1
## * zwlr_output_head_v1
## * zwlr_output_mode_v1
## * zwlr_output_configuration_v1
## * zwlr_output_configuration_head_v1
## 
## Copyright
## =========
## 
## Copyright © 2019 Purism SPC
## 
## Permission to use, copy, modify, distribute, and sell this
## software and its documentation for any purpose is hereby granted
## without fee, provided that the above copyright notice appear in
## all copies and that both that copyright notice and this permission
## notice appear in supporting documentation, and that the name of
## the copyright holders not be used in advertising or publicity
## pertaining to distribution of the software without specific,
## written prior permission.  The copyright holders make no
## representations about the suitability of this software for any
## purpose.  It is provided "as is" without express or implied
## warranty.
## 
## THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
## SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
## FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
## SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
## WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
## AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
## ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
## THIS SOFTWARE.
## 

type ZwlrOutputManagerV1Listener* = object
  head*: proc(
    data: pointer,
    zwlrOutputManagerV1: ptr ZwlrOutputManagerV1,
    head: ptr ZwlrOutputHeadV1,
  ) {.nimcall.}
  done*: proc(
    data: pointer, zwlrOutputManagerV1: ptr ZwlrOutputManagerV1, serial: uint32
  ) {.nimcall.}
  finished*:
    proc(data: pointer, zwlrOutputManagerV1: ptr ZwlrOutputManagerV1) {.nimcall.}

proc addListener*(
    zwlrOutputManagerV1: ptr ZwlrOutputManagerV1,
    listener: ptr ZwlrOutputManagerV1Listener,
    data: pointer,
): int {.inline.} =
  cast[ptr Proxy](zwlrOutputManagerV1).add_listener(listener, data)

proc setUserData*(
    zwlrOutputManagerV1: ptr ZwlrOutputManagerV1, userData: pointer
) {.inline.} =
  cast[ptr Proxy](zwlrOutputManagerV1).set_user_data(user_data)

proc getUserData*(zwlrOutputManagerV1: ptr ZwlrOutputManagerV1): pointer {.inline.} =
  cast[ptr Proxy](zwlrOutputManagerV1).get_user_data()

proc getVersion*(zwlrOutputManagerV1: ptr ZwlrOutputManagerV1): uint32 {.inline.} =
  cast[ptr Proxy](zwlrOutputManagerV1).get_version()

proc destroy*(zwlrOutputManagerV1: ptr ZwlrOutputManagerV1) {.inline.} =
  destroy cast[ptr Proxy](zwlrOutputManagerV1)

proc createConfiguration*(
    zwlrOutputManagerV1: ptr ZwlrOutputManagerV1, serial: uint32
): ptr ZwlrOutputConfigurationV1 {.inline.} =
  ## create a new output configuration object
  ## 
  ## Create a new output configuration object. This allows to update head
  ## properties.
  ## 
  cast[ptr ZwlrOutputConfigurationV1](cast[ptr Proxy](zwlrOutputManagerV1).marshal_flags(
    ZwlrOutputManagerV1Request_create_configuration.ord,
    addr zwlr_output_configuration_v1_interface,
    cast[ptr Proxy](zwlrOutputManagerV1).get_version(),
    0,
    nil,
    serial,
  ))

proc stop*(zwlrOutputManagerV1: ptr ZwlrOutputManagerV1) {.inline.} =
  ## stop sending events
  ## 
  ## Indicates the client no longer wishes to receive events for output
  ## configuration changes. However the compositor may emit further events,
  ## until the finished event is emitted.
  ## 
  ## The client must not send any more requests after this one.
  ## 
  cast[ptr Proxy](zwlrOutputManagerV1).marshal_flags(
    ZwlrOutputManagerV1Request_stop.ord,
    nil,
    cast[ptr Proxy](zwlrOutputManagerV1).get_version(),
    0,
  )

type ZwlrOutputHeadV1Listener* = object
  name*: proc(data: pointer, zwlrOutputHeadV1: ptr ZwlrOutputHeadV1, name: cstring) {.
    nimcall
  .}
  description*: proc(
    data: pointer, zwlrOutputHeadV1: ptr ZwlrOutputHeadV1, description: cstring
  ) {.nimcall.}
  physicalSize*: proc(
    data: pointer, zwlrOutputHeadV1: ptr ZwlrOutputHeadV1, width: int32, height: int32
  ) {.nimcall.}
  mode*: proc(
    data: pointer, zwlrOutputHeadV1: ptr ZwlrOutputHeadV1, mode: ptr ZwlrOutputModeV1
  ) {.nimcall.}
  enabled*: proc(data: pointer, zwlrOutputHeadV1: ptr ZwlrOutputHeadV1, enabled: int32) {.
    nimcall
  .}
  currentMode*: proc(
    data: pointer, zwlrOutputHeadV1: ptr ZwlrOutputHeadV1, mode: ptr ZwlrOutputModeV1
  ) {.nimcall.}
  position*: proc(
    data: pointer, zwlrOutputHeadV1: ptr ZwlrOutputHeadV1, x: int32, y: int32
  ) {.nimcall.}
  transform*: proc(
    data: pointer, zwlrOutputHeadV1: ptr ZwlrOutputHeadV1, transform: int32
  ) {.nimcall.}
  scale*: proc(data: pointer, zwlrOutputHeadV1: ptr ZwlrOutputHeadV1, scale: Fixed) {.
    nimcall
  .}
  finished*: proc(data: pointer, zwlrOutputHeadV1: ptr ZwlrOutputHeadV1) {.nimcall.}
  make*: proc(data: pointer, zwlrOutputHeadV1: ptr ZwlrOutputHeadV1, make: cstring) {.
    nimcall
  .}
  model*: proc(data: pointer, zwlrOutputHeadV1: ptr ZwlrOutputHeadV1, model: cstring) {.
    nimcall
  .}
  serialNumber*: proc(
    data: pointer, zwlrOutputHeadV1: ptr ZwlrOutputHeadV1, serialNumber: cstring
  ) {.nimcall.}
  adaptiveSync*: proc(
    data: pointer, zwlrOutputHeadV1: ptr ZwlrOutputHeadV1, state: uint32
  ) {.nimcall.}

proc addListener*(
    zwlrOutputHeadV1: ptr ZwlrOutputHeadV1,
    listener: ptr ZwlrOutputHeadV1Listener,
    data: pointer,
): int {.inline.} =
  cast[ptr Proxy](zwlrOutputHeadV1).add_listener(listener, data)

proc setUserData*(
    zwlrOutputHeadV1: ptr ZwlrOutputHeadV1, userData: pointer
) {.inline.} =
  cast[ptr Proxy](zwlrOutputHeadV1).set_user_data(user_data)

proc getUserData*(zwlrOutputHeadV1: ptr ZwlrOutputHeadV1): pointer {.inline.} =
  cast[ptr Proxy](zwlrOutputHeadV1).get_user_data()

proc getVersion*(zwlrOutputHeadV1: ptr ZwlrOutputHeadV1): uint32 {.inline.} =
  cast[ptr Proxy](zwlrOutputHeadV1).get_version()

proc destroy*(zwlrOutputHeadV1: ptr ZwlrOutputHeadV1) {.inline.} =
  destroy cast[ptr Proxy](zwlrOutputHeadV1)

proc release*(zwlrOutputHeadV1: ptr ZwlrOutputHeadV1) {.inline.} =
  ## destroy the head object
  ## 
  ## This request indicates that the client will no longer use this head
  ## object.
  ## 
  cast[ptr Proxy](zwlrOutputHeadV1).marshal_flags(
    ZwlrOutputHeadV1Request_release.ord,
    nil,
    cast[ptr Proxy](zwlrOutputHeadV1).get_version(),
    WL_MARSHAL_FLAG_DESTROY,
  )

type ZwlrOutputModeV1Listener* = object
  size*: proc(
    data: pointer, zwlrOutputModeV1: ptr ZwlrOutputModeV1, width: int32, height: int32
  ) {.nimcall.}
  refresh*: proc(data: pointer, zwlrOutputModeV1: ptr ZwlrOutputModeV1, refresh: int32) {.
    nimcall
  .}
  preferred*: proc(data: pointer, zwlrOutputModeV1: ptr ZwlrOutputModeV1) {.nimcall.}
  finished*: proc(data: pointer, zwlrOutputModeV1: ptr ZwlrOutputModeV1) {.nimcall.}

proc addListener*(
    zwlrOutputModeV1: ptr ZwlrOutputModeV1,
    listener: ptr ZwlrOutputModeV1Listener,
    data: pointer,
): int {.inline.} =
  cast[ptr Proxy](zwlrOutputModeV1).add_listener(listener, data)

proc setUserData*(
    zwlrOutputModeV1: ptr ZwlrOutputModeV1, userData: pointer
) {.inline.} =
  cast[ptr Proxy](zwlrOutputModeV1).set_user_data(user_data)

proc getUserData*(zwlrOutputModeV1: ptr ZwlrOutputModeV1): pointer {.inline.} =
  cast[ptr Proxy](zwlrOutputModeV1).get_user_data()

proc getVersion*(zwlrOutputModeV1: ptr ZwlrOutputModeV1): uint32 {.inline.} =
  cast[ptr Proxy](zwlrOutputModeV1).get_version()

proc destroy*(zwlrOutputModeV1: ptr ZwlrOutputModeV1) {.inline.} =
  destroy cast[ptr Proxy](zwlrOutputModeV1)

proc release*(zwlrOutputModeV1: ptr ZwlrOutputModeV1) {.inline.} =
  ## destroy the mode object
  ## 
  ## This request indicates that the client will no longer use this mode
  ## object.
  ## 
  cast[ptr Proxy](zwlrOutputModeV1).marshal_flags(
    ZwlrOutputModeV1Request_release.ord,
    nil,
    cast[ptr Proxy](zwlrOutputModeV1).get_version(),
    WL_MARSHAL_FLAG_DESTROY,
  )

type ZwlrOutputConfigurationV1Listener* = object
  succeeded*: proc(
    data: pointer, zwlrOutputConfigurationV1: ptr ZwlrOutputConfigurationV1
  ) {.nimcall.}
  failed*: proc(data: pointer, zwlrOutputConfigurationV1: ptr ZwlrOutputConfigurationV1) {.
    nimcall
  .}
  cancelled*: proc(
    data: pointer, zwlrOutputConfigurationV1: ptr ZwlrOutputConfigurationV1
  ) {.nimcall.}

proc addListener*(
    zwlrOutputConfigurationV1: ptr ZwlrOutputConfigurationV1,
    listener: ptr ZwlrOutputConfigurationV1Listener,
    data: pointer,
): int {.inline.} =
  cast[ptr Proxy](zwlrOutputConfigurationV1).add_listener(listener, data)

proc setUserData*(
    zwlrOutputConfigurationV1: ptr ZwlrOutputConfigurationV1, userData: pointer
) {.inline.} =
  cast[ptr Proxy](zwlrOutputConfigurationV1).set_user_data(user_data)

proc getUserData*(
    zwlrOutputConfigurationV1: ptr ZwlrOutputConfigurationV1
): pointer {.inline.} =
  cast[ptr Proxy](zwlrOutputConfigurationV1).get_user_data()

proc getVersion*(
    zwlrOutputConfigurationV1: ptr ZwlrOutputConfigurationV1
): uint32 {.inline.} =
  cast[ptr Proxy](zwlrOutputConfigurationV1).get_version()

proc enableHead*(
    zwlrOutputConfigurationV1: ptr ZwlrOutputConfigurationV1, head: ptr ZwlrOutputHeadV1
): ptr ZwlrOutputConfigurationHeadV1 {.inline.} =
  ## enable and configure a head
  ## 
  ## Enable a head. This request creates a head configuration object that can
  ## be used to change the head's properties.
  ## 
  cast[ptr ZwlrOutputConfigurationHeadV1](cast[ptr Proxy](zwlrOutputConfigurationV1).marshal_flags(
    ZwlrOutputConfigurationV1Request_enable_head.ord,
    addr zwlr_output_configuration_head_v1_interface,
    cast[ptr Proxy](zwlrOutputConfigurationV1).get_version(),
    0,
    nil,
    head,
  ))

proc disableHead*(
    zwlrOutputConfigurationV1: ptr ZwlrOutputConfigurationV1, head: ptr ZwlrOutputHeadV1
) {.inline.} =
  ## disable a head
  ## 
  ## Disable a head.
  ## 
  cast[ptr Proxy](zwlrOutputConfigurationV1).marshal_flags(
    ZwlrOutputConfigurationV1Request_disable_head.ord,
    nil,
    cast[ptr Proxy](zwlrOutputConfigurationV1).get_version(),
    0,
    head,
  )

proc apply*(zwlrOutputConfigurationV1: ptr ZwlrOutputConfigurationV1) {.inline.} =
  ## apply the configuration
  ## 
  ## Apply the new output configuration.
  ## 
  ## In case the configuration is successfully applied, there is no guarantee
  ## that the new output state matches completely the requested
  ## configuration. For instance, a compositor might round the scale if it
  ## doesn't support fractional scaling.
  ## 
  ## After this request has been sent, the compositor must respond with an
  ## succeeded, failed or cancelled event. Sending a request that isn't the
  ## destructor is a protocol error.
  ## 
  cast[ptr Proxy](zwlrOutputConfigurationV1).marshal_flags(
    ZwlrOutputConfigurationV1Request_apply.ord,
    nil,
    cast[ptr Proxy](zwlrOutputConfigurationV1).get_version(),
    0,
  )

proc test*(zwlrOutputConfigurationV1: ptr ZwlrOutputConfigurationV1) {.inline.} =
  ## test the configuration
  ## 
  ## Test the new output configuration. The configuration won't be applied,
  ## but will only be validated.
  ## 
  ## Even if the compositor succeeds to test a configuration, applying it may
  ## fail.
  ## 
  ## After this request has been sent, the compositor must respond with an
  ## succeeded, failed or cancelled event. Sending a request that isn't the
  ## destructor is a protocol error.
  ## 
  cast[ptr Proxy](zwlrOutputConfigurationV1).marshal_flags(
    ZwlrOutputConfigurationV1Request_test.ord,
    nil,
    cast[ptr Proxy](zwlrOutputConfigurationV1).get_version(),
    0,
  )

proc destroy*(zwlrOutputConfigurationV1: ptr ZwlrOutputConfigurationV1) {.inline.} =
  ## destroy the output configuration
  ## 
  ## Using this request a client can tell the compositor that it is not going
  ## to use the configuration object anymore. Any changes to the outputs
  ## that have not been applied will be discarded.
  ## 
  ## This request also destroys wlr_output_configuration_head objects created
  ## via this object.
  ## 
  cast[ptr Proxy](zwlrOutputConfigurationV1).marshal_flags(
    ZwlrOutputConfigurationV1Request_destroy.ord,
    nil,
    cast[ptr Proxy](zwlrOutputConfigurationV1).get_version(),
    WL_MARSHAL_FLAG_DESTROY,
  )

proc setUserData*(
    zwlrOutputConfigurationHeadV1: ptr ZwlrOutputConfigurationHeadV1, userData: pointer
) {.inline.} =
  cast[ptr Proxy](zwlrOutputConfigurationHeadV1).set_user_data(user_data)

proc getUserData*(
    zwlrOutputConfigurationHeadV1: ptr ZwlrOutputConfigurationHeadV1
): pointer {.inline.} =
  cast[ptr Proxy](zwlrOutputConfigurationHeadV1).get_user_data()

proc getVersion*(
    zwlrOutputConfigurationHeadV1: ptr ZwlrOutputConfigurationHeadV1
): uint32 {.inline.} =
  cast[ptr Proxy](zwlrOutputConfigurationHeadV1).get_version()

proc destroy*(
    zwlrOutputConfigurationHeadV1: ptr ZwlrOutputConfigurationHeadV1
) {.inline.} =
  destroy cast[ptr Proxy](zwlrOutputConfigurationHeadV1)

proc setMode*(
    zwlrOutputConfigurationHeadV1: ptr ZwlrOutputConfigurationHeadV1,
    mode: ptr ZwlrOutputModeV1,
) {.inline.} =
  ## set the mode
  ## 
  ## This request sets the head's mode.
  ## 
  cast[ptr Proxy](zwlrOutputConfigurationHeadV1).marshal_flags(
    ZwlrOutputConfigurationHeadV1Request_set_mode.ord,
    nil,
    cast[ptr Proxy](zwlrOutputConfigurationHeadV1).get_version(),
    0,
    mode,
  )

proc setCustomMode*(
    zwlrOutputConfigurationHeadV1: ptr ZwlrOutputConfigurationHeadV1,
    width: int32,
    height: int32,
    refresh: int32,
) {.inline.} =
  ## set a custom mode
  ## 
  ## This request assigns a custom mode to the head. The size is given in
  ## physical hardware units of the output device. If set to zero, the
  ## refresh rate is unspecified.
  ## 
  ## It is a protocol error to set both a mode and a custom mode.
  ## 
  cast[ptr Proxy](zwlrOutputConfigurationHeadV1).marshal_flags(
    ZwlrOutputConfigurationHeadV1Request_set_custom_mode.ord,
    nil,
    cast[ptr Proxy](zwlrOutputConfigurationHeadV1).get_version(),
    0,
    width,
    height,
    refresh,
  )

proc setPosition*(
    zwlrOutputConfigurationHeadV1: ptr ZwlrOutputConfigurationHeadV1, x: int32, y: int32
) {.inline.} =
  ## set the position
  ## 
  ## This request sets the head's position in the global compositor space.
  ## 
  cast[ptr Proxy](zwlrOutputConfigurationHeadV1).marshal_flags(
    ZwlrOutputConfigurationHeadV1Request_set_position.ord,
    nil,
    cast[ptr Proxy](zwlrOutputConfigurationHeadV1).get_version(),
    0,
    x,
    y,
  )

proc setTransform*(
    zwlrOutputConfigurationHeadV1: ptr ZwlrOutputConfigurationHeadV1, transform: int32
) {.inline.} =
  ## set the transform
  ## 
  ## This request sets the head's transform.
  ## 
  cast[ptr Proxy](zwlrOutputConfigurationHeadV1).marshal_flags(
    ZwlrOutputConfigurationHeadV1Request_set_transform.ord,
    nil,
    cast[ptr Proxy](zwlrOutputConfigurationHeadV1).get_version(),
    0,
    transform,
  )

proc setScale*(
    zwlrOutputConfigurationHeadV1: ptr ZwlrOutputConfigurationHeadV1, scale: Fixed
) {.inline.} =
  ## set the scale
  ## 
  ## This request sets the head's scale.
  ## 
  cast[ptr Proxy](zwlrOutputConfigurationHeadV1).marshal_flags(
    ZwlrOutputConfigurationHeadV1Request_set_scale.ord,
    nil,
    cast[ptr Proxy](zwlrOutputConfigurationHeadV1).get_version(),
    0,
    scale,
  )

proc setAdaptiveSync*(
    zwlrOutputConfigurationHeadV1: ptr ZwlrOutputConfigurationHeadV1, state: uint32
) {.inline.} =
  ## enable/disable adaptive sync
  ## 
  ## This request enables/disables adaptive sync. Adaptive sync is also
  ## known as Variable Refresh Rate or VRR.
  ## 
  cast[ptr Proxy](zwlrOutputConfigurationHeadV1).marshal_flags(
    ZwlrOutputConfigurationHeadV1Request_set_adaptive_sync.ord,
    nil,
    cast[ptr Proxy](zwlrOutputConfigurationHeadV1).get_version(),
    0,
    state,
  )
