# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]: off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code

var wlrOutputManagementUnstableV1_types: array[12, ptr Interface]
type ZwlrOutputConfigurationHeadV1* = object
type ZwlrOutputConfigurationV1* = object
type ZwlrOutputHeadV1* = object
type ZwlrOutputManagerV1* = object
type ZwlrOutputModeV1* = object

let
  zwlr_output_manager_v1_requests {.exportc.} = [
    Message(
      name: "create_configuration",
      signature: "nu",
      types: addr wlr_output_management_unstable_v1_types[3],
    ),
    Message(
      name: "stop",
      signature: "",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
  ]

  zwlr_output_manager_v1_events {.exportc.} = [
    Message(
      name: "head",
      signature: "n",
      types: addr wlr_output_management_unstable_v1_types[5],
    ),
    Message(
      name: "done",
      signature: "u",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
    Message(
      name: "finished",
      signature: "",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
  ]

  zwlr_output_manager_v1_interface* {.exportc.} = Interface(
    name: "zwlr_output_manager_v1",
    version: 4,
    method_count: 2,
    methods: addr zwlr_output_manager_v1_requests[0],
    event_count: 3,
    events: addr zwlr_output_manager_v1_events[0],
  )

  zwlr_output_head_v1_requests {.exportc.} = [
    Message(
      name: "release",
      signature: "3",
      types: addr wlr_output_management_unstable_v1_types[0],
    )
  ]

  zwlr_output_head_v1_events {.exportc.} = [
    Message(
      name: "name",
      signature: "s",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
    Message(
      name: "description",
      signature: "s",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
    Message(
      name: "physical_size",
      signature: "ii",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
    Message(
      name: "mode",
      signature: "n",
      types: addr wlr_output_management_unstable_v1_types[6],
    ),
    Message(
      name: "enabled",
      signature: "i",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
    Message(
      name: "current_mode",
      signature: "o",
      types: addr wlr_output_management_unstable_v1_types[7],
    ),
    Message(
      name: "position",
      signature: "ii",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
    Message(
      name: "transform",
      signature: "i",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
    Message(
      name: "scale",
      signature: "f",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
    Message(
      name: "finished",
      signature: "",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
    Message(
      name: "make",
      signature: "2s",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
    Message(
      name: "model",
      signature: "2s",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
    Message(
      name: "serial_number",
      signature: "2s",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
    Message(
      name: "adaptive_sync",
      signature: "4u",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
  ]

  zwlr_output_head_v1_interface* {.exportc.} = Interface(
    name: "zwlr_output_head_v1",
    version: 4,
    method_count: 1,
    methods: addr zwlr_output_head_v1_requests[0],
    event_count: 14,
    events: addr zwlr_output_head_v1_events[0],
  )

  zwlr_output_mode_v1_requests {.exportc.} = [
    Message(
      name: "release",
      signature: "3",
      types: addr wlr_output_management_unstable_v1_types[0],
    )
  ]

  zwlr_output_mode_v1_events {.exportc.} = [
    Message(
      name: "size",
      signature: "ii",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
    Message(
      name: "refresh",
      signature: "i",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
    Message(
      name: "preferred",
      signature: "",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
    Message(
      name: "finished",
      signature: "",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
  ]

  zwlr_output_mode_v1_interface* {.exportc.} = Interface(
    name: "zwlr_output_mode_v1",
    version: 3,
    method_count: 1,
    methods: addr zwlr_output_mode_v1_requests[0],
    event_count: 4,
    events: addr zwlr_output_mode_v1_events[0],
  )

  zwlr_output_configuration_v1_requests {.exportc.} = [
    Message(
      name: "enable_head",
      signature: "no",
      types: addr wlr_output_management_unstable_v1_types[8],
    ),
    Message(
      name: "disable_head",
      signature: "o",
      types: addr wlr_output_management_unstable_v1_types[10],
    ),
    Message(
      name: "apply",
      signature: "",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
    Message(
      name: "test",
      signature: "",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
    Message(
      name: "destroy",
      signature: "",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
  ]

  zwlr_output_configuration_v1_events {.exportc.} = [
    Message(
      name: "succeeded",
      signature: "",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
    Message(
      name: "failed",
      signature: "",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
    Message(
      name: "cancelled",
      signature: "",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
  ]

  zwlr_output_configuration_v1_interface* {.exportc.} = Interface(
    name: "zwlr_output_configuration_v1",
    version: 4,
    method_count: 5,
    methods: addr zwlr_output_configuration_v1_requests[0],
    event_count: 3,
    events: addr zwlr_output_configuration_v1_events[0],
  )

  zwlr_output_configuration_head_v1_requests {.exportc.} = [
    Message(
      name: "set_mode",
      signature: "o",
      types: addr wlr_output_management_unstable_v1_types[11],
    ),
    Message(
      name: "set_custom_mode",
      signature: "iii",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
    Message(
      name: "set_position",
      signature: "ii",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
    Message(
      name: "set_transform",
      signature: "i",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
    Message(
      name: "set_scale",
      signature: "f",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
    Message(
      name: "set_adaptive_sync",
      signature: "4u",
      types: addr wlr_output_management_unstable_v1_types[0],
    ),
  ]

  zwlr_output_configuration_head_v1_interface* {.exportc.} = Interface(
    name: "zwlr_output_configuration_head_v1",
    version: 4,
    method_count: 6,
    methods: addr zwlr_output_configuration_head_v1_requests[0],
  )

type ZwlrOutputHeadV1AdaptiveSyncState* {.size: sizeof(uint32).} = enum
  adaptive_sync_state_disabled = 0
  adaptive_sync_state_enabled = 1

func since*(e: ZwlrOutputHeadV1AdaptiveSyncState): int =
  case e
  of adaptive_sync_state_disabled: 4
  of adaptive_sync_state_enabled: 4
proc isValid*(e: ZwlrOutputHeadV1AdaptiveSyncState, version: int): bool =
  version >= e.since

type ZwlrOutputConfigurationV1Error* {.size: sizeof(uint32).} = enum
  error_already_configured_head = 1
  error_unconfigured_head = 2
  error_already_used = 3

func since*(e: ZwlrOutputConfigurationV1Error): int =
  case e
  of error_already_configured_head: 1
  of error_unconfigured_head: 1
  of error_already_used: 1
proc isValid*(e: ZwlrOutputConfigurationV1Error, version: int): bool =
  version >= e.since

type ZwlrOutputConfigurationHeadV1Error* {.size: sizeof(uint32).} = enum
  error_already_set = 1
  error_invalid_mode = 2
  error_invalid_custom_mode = 3
  error_invalid_transform = 4
  error_invalid_scale = 5
  error_invalid_adaptive_sync_state = 6

func since*(e: ZwlrOutputConfigurationHeadV1Error): int =
  case e
  of error_already_set: 1
  of error_invalid_mode: 1
  of error_invalid_custom_mode: 1
  of error_invalid_transform: 1
  of error_invalid_scale: 1
  of error_invalid_adaptive_sync_state: 4
proc isValid*(e: ZwlrOutputConfigurationHeadV1Error, version: int): bool =
  version >= e.since

type ZwlrOutputManagerV1Event* {.size: sizeof(uint32).} = enum
  ZwlrOutputManagerV1Event_head
  ZwlrOutputManagerV1Event_done
  ZwlrOutputManagerV1Event_finished

proc since*(e: ZwlrOutputManagerV1Event): int =
  case e
  of ZwlrOutputManagerV1Event_head: 1
  of ZwlrOutputManagerV1Event_done: 1
  of ZwlrOutputManagerV1Event_finished: 1

type ZwlrOutputManagerV1Request* {.size: sizeof(uint32).} = enum
  ZwlrOutputManagerV1Request_create_configuration
  ZwlrOutputManagerV1Request_stop

proc since*(e: ZwlrOutputManagerV1Request): int =
  case e
  of ZwlrOutputManagerV1Request_create_configuration: 1
  of ZwlrOutputManagerV1Request_stop: 1

type ZwlrOutputHeadV1Event* {.size: sizeof(uint32).} = enum
  ZwlrOutputHeadV1Event_name
  ZwlrOutputHeadV1Event_description
  ZwlrOutputHeadV1Event_physical_size
  ZwlrOutputHeadV1Event_mode
  ZwlrOutputHeadV1Event_enabled
  ZwlrOutputHeadV1Event_current_mode
  ZwlrOutputHeadV1Event_position
  ZwlrOutputHeadV1Event_transform
  ZwlrOutputHeadV1Event_scale
  ZwlrOutputHeadV1Event_finished
  ZwlrOutputHeadV1Event_make
  ZwlrOutputHeadV1Event_model
  ZwlrOutputHeadV1Event_serial_number
  ZwlrOutputHeadV1Event_adaptive_sync

proc since*(e: ZwlrOutputHeadV1Event): int =
  case e
  of ZwlrOutputHeadV1Event_name: 1
  of ZwlrOutputHeadV1Event_description: 1
  of ZwlrOutputHeadV1Event_physical_size: 1
  of ZwlrOutputHeadV1Event_mode: 1
  of ZwlrOutputHeadV1Event_enabled: 1
  of ZwlrOutputHeadV1Event_current_mode: 1
  of ZwlrOutputHeadV1Event_position: 1
  of ZwlrOutputHeadV1Event_transform: 1
  of ZwlrOutputHeadV1Event_scale: 1
  of ZwlrOutputHeadV1Event_finished: 1
  of ZwlrOutputHeadV1Event_make: 2
  of ZwlrOutputHeadV1Event_model: 2
  of ZwlrOutputHeadV1Event_serial_number: 2
  of ZwlrOutputHeadV1Event_adaptive_sync: 4

type ZwlrOutputHeadV1Request* {.size: sizeof(uint32).} = enum
  ZwlrOutputHeadV1Request_release

proc since*(e: ZwlrOutputHeadV1Request): int =
  case e
  of ZwlrOutputHeadV1Request_release: 3

type ZwlrOutputModeV1Event* {.size: sizeof(uint32).} = enum
  ZwlrOutputModeV1Event_size
  ZwlrOutputModeV1Event_refresh
  ZwlrOutputModeV1Event_preferred
  ZwlrOutputModeV1Event_finished

proc since*(e: ZwlrOutputModeV1Event): int =
  case e
  of ZwlrOutputModeV1Event_size: 1
  of ZwlrOutputModeV1Event_refresh: 1
  of ZwlrOutputModeV1Event_preferred: 1
  of ZwlrOutputModeV1Event_finished: 1

type ZwlrOutputModeV1Request* {.size: sizeof(uint32).} = enum
  ZwlrOutputModeV1Request_release

proc since*(e: ZwlrOutputModeV1Request): int =
  case e
  of ZwlrOutputModeV1Request_release: 3

type ZwlrOutputConfigurationV1Event* {.size: sizeof(uint32).} = enum
  ZwlrOutputConfigurationV1Event_succeeded
  ZwlrOutputConfigurationV1Event_failed
  ZwlrOutputConfigurationV1Event_cancelled

proc since*(e: ZwlrOutputConfigurationV1Event): int =
  case e
  of ZwlrOutputConfigurationV1Event_succeeded: 1
  of ZwlrOutputConfigurationV1Event_failed: 1
  of ZwlrOutputConfigurationV1Event_cancelled: 1

type ZwlrOutputConfigurationV1Request* {.size: sizeof(uint32).} = enum
  ZwlrOutputConfigurationV1Request_enable_head
  ZwlrOutputConfigurationV1Request_disable_head
  ZwlrOutputConfigurationV1Request_apply
  ZwlrOutputConfigurationV1Request_test
  ZwlrOutputConfigurationV1Request_destroy

proc since*(e: ZwlrOutputConfigurationV1Request): int =
  case e
  of ZwlrOutputConfigurationV1Request_enable_head: 1
  of ZwlrOutputConfigurationV1Request_disable_head: 1
  of ZwlrOutputConfigurationV1Request_apply: 1
  of ZwlrOutputConfigurationV1Request_test: 1
  of ZwlrOutputConfigurationV1Request_destroy: 1

type ZwlrOutputConfigurationHeadV1Request* {.size: sizeof(uint32).} = enum
  ZwlrOutputConfigurationHeadV1Request_set_mode
  ZwlrOutputConfigurationHeadV1Request_set_custom_mode
  ZwlrOutputConfigurationHeadV1Request_set_position
  ZwlrOutputConfigurationHeadV1Request_set_transform
  ZwlrOutputConfigurationHeadV1Request_set_scale
  ZwlrOutputConfigurationHeadV1Request_set_adaptive_sync

proc since*(e: ZwlrOutputConfigurationHeadV1Request): int =
  case e
  of ZwlrOutputConfigurationHeadV1Request_set_mode: 1
  of ZwlrOutputConfigurationHeadV1Request_set_custom_mode: 1
  of ZwlrOutputConfigurationHeadV1Request_set_position: 1
  of ZwlrOutputConfigurationHeadV1Request_set_transform: 1
  of ZwlrOutputConfigurationHeadV1Request_set_scale: 1
  of ZwlrOutputConfigurationHeadV1Request_set_adaptive_sync: 4

wlrOutputManagementUnstableV1_types = [
  nil,
  nil,
  nil,
  addr zwlr_output_configuration_v1_interface,
  nil,
  addr zwlr_output_head_v1_interface,
  addr zwlr_output_mode_v1_interface,
  addr zwlr_output_mode_v1_interface,
  addr zwlr_output_configuration_head_v1_interface,
  addr zwlr_output_head_v1_interface,
  addr zwlr_output_head_v1_interface,
  addr zwlr_output_mode_v1_interface,
]
