# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]: off.}
import wayland/native/server
import wayland/native/common
import code
export code

## The wlr_output_management_unstable_v1 SERVER protocol
## #####################################################
## 
## Interfaces
## ==========
## 
## * zwlr_output_manager_v1
## * zwlr_output_head_v1
## * zwlr_output_mode_v1
## * zwlr_output_configuration_v1
## * zwlr_output_configuration_head_v1
## 
## Copyright
## =========
## 
## Copyright © 2019 Purism SPC
## 
## Permission to use, copy, modify, distribute, and sell this
## software and its documentation for any purpose is hereby granted
## without fee, provided that the above copyright notice appear in
## all copies and that both that copyright notice and this permission
## notice appear in supporting documentation, and that the name of
## the copyright holders not be used in advertising or publicity
## pertaining to distribution of the software without specific,
## written prior permission.  The copyright holders make no
## representations about the suitability of this software for any
## purpose.  It is provided "as is" without express or implied
## warranty.
## 
## THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
## SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
## FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
## SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
## WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
## AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
## ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
## THIS SOFTWARE.
## 

type ZwlrOutputManagerV1Interface* = object
  createConfiguration*: proc(
    client: ptr Client, resource: ptr Resource, id: uint32, serial: uint32
  ) {.nimcall.}
  stop*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}

proc zwlrOutputManagerV1SendHead*(
    resource: ptr Resource, head: ptr Resource
) {.inline, exportc: "zwlr_output_manager_v1_send_head".} =
  ## Sends an head event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(ZwlrOutputManagerV1Event_head.ord, head)

proc zwlrOutputManagerV1SendDone*(
    resource: ptr Resource, serial: uint32
) {.inline, exportc: "zwlr_output_manager_v1_send_done".} =
  ## Sends an done event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *serial*: current configuration serial
  resource.post_event(ZwlrOutputManagerV1Event_done.ord, serial)

proc zwlrOutputManagerV1SendFinished*(
    resource: ptr Resource
) {.inline, exportc: "zwlr_output_manager_v1_send_finished".} =
  ## Sends an finished event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(ZwlrOutputManagerV1Event_finished.ord)

type ZwlrOutputHeadV1Interface* = object
  release*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}

proc zwlrOutputHeadV1SendName*(
    resource: ptr Resource, name: cstring
) {.inline, exportc: "zwlr_output_head_v1_send_name".} =
  ## Sends an name event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(ZwlrOutputHeadV1Event_name.ord, name)

proc zwlrOutputHeadV1SendDescription*(
    resource: ptr Resource, description: cstring
) {.inline, exportc: "zwlr_output_head_v1_send_description".} =
  ## Sends an description event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(ZwlrOutputHeadV1Event_description.ord, description)

proc zwlrOutputHeadV1SendPhysicalSize*(
    resource: ptr Resource, width: int32, height: int32
) {.inline, exportc: "zwlr_output_head_v1_send_physical_size".} =
  ## Sends an physical_size event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *width*: width in millimeters of the output
  ## * *height*: height in millimeters of the output
  resource.post_event(ZwlrOutputHeadV1Event_physical_size.ord, width, height)

proc zwlrOutputHeadV1SendMode*(
    resource: ptr Resource, mode: ptr Resource
) {.inline, exportc: "zwlr_output_head_v1_send_mode".} =
  ## Sends an mode event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(ZwlrOutputHeadV1Event_mode.ord, mode)

proc zwlrOutputHeadV1SendEnabled*(
    resource: ptr Resource, enabled: int32
) {.inline, exportc: "zwlr_output_head_v1_send_enabled".} =
  ## Sends an enabled event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *enabled*: zero if disabled, non-zero if enabled
  resource.post_event(ZwlrOutputHeadV1Event_enabled.ord, enabled)

proc zwlrOutputHeadV1SendCurrentMode*(
    resource: ptr Resource, mode: ptr Resource
) {.inline, exportc: "zwlr_output_head_v1_send_current_mode".} =
  ## Sends an current_mode event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(ZwlrOutputHeadV1Event_current_mode.ord, mode)

proc zwlrOutputHeadV1SendPosition*(
    resource: ptr Resource, x: int32, y: int32
) {.inline, exportc: "zwlr_output_head_v1_send_position".} =
  ## Sends an position event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *x*: x position within the global compositor space
  ## * *y*: y position within the global compositor space
  resource.post_event(ZwlrOutputHeadV1Event_position.ord, x, y)

proc zwlrOutputHeadV1SendTransform*(
    resource: ptr Resource, transform: int32
) {.inline, exportc: "zwlr_output_head_v1_send_transform".} =
  ## Sends an transform event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(ZwlrOutputHeadV1Event_transform.ord, transform)

proc zwlrOutputHeadV1SendScale*(
    resource: ptr Resource, scale: Fixed
) {.inline, exportc: "zwlr_output_head_v1_send_scale".} =
  ## Sends an scale event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(ZwlrOutputHeadV1Event_scale.ord, scale)

proc zwlrOutputHeadV1SendFinished*(
    resource: ptr Resource
) {.inline, exportc: "zwlr_output_head_v1_send_finished".} =
  ## Sends an finished event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(ZwlrOutputHeadV1Event_finished.ord)

proc zwlrOutputHeadV1SendMake*(
    resource: ptr Resource, make: cstring
) {.inline, exportc: "zwlr_output_head_v1_send_make".} =
  ## Sends an make event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(ZwlrOutputHeadV1Event_make.ord, make)

proc zwlrOutputHeadV1SendModel*(
    resource: ptr Resource, model: cstring
) {.inline, exportc: "zwlr_output_head_v1_send_model".} =
  ## Sends an model event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(ZwlrOutputHeadV1Event_model.ord, model)

proc zwlrOutputHeadV1SendSerialNumber*(
    resource: ptr Resource, serialNumber: cstring
) {.inline, exportc: "zwlr_output_head_v1_send_serial_number".} =
  ## Sends an serial_number event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(ZwlrOutputHeadV1Event_serial_number.ord, serialNumber)

proc zwlrOutputHeadV1SendAdaptiveSync*(
    resource: ptr Resource, state: uint32
) {.inline, exportc: "zwlr_output_head_v1_send_adaptive_sync".} =
  ## Sends an adaptive_sync event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(ZwlrOutputHeadV1Event_adaptive_sync.ord, state)

type ZwlrOutputModeV1Interface* = object
  release*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}

proc zwlrOutputModeV1SendSize*(
    resource: ptr Resource, width: int32, height: int32
) {.inline, exportc: "zwlr_output_mode_v1_send_size".} =
  ## Sends an size event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *width*: width of the mode in hardware units
  ## * *height*: height of the mode in hardware units
  resource.post_event(ZwlrOutputModeV1Event_size.ord, width, height)

proc zwlrOutputModeV1SendRefresh*(
    resource: ptr Resource, refresh: int32
) {.inline, exportc: "zwlr_output_mode_v1_send_refresh".} =
  ## Sends an refresh event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *refresh*: vertical refresh rate in mHz
  resource.post_event(ZwlrOutputModeV1Event_refresh.ord, refresh)

proc zwlrOutputModeV1SendPreferred*(
    resource: ptr Resource
) {.inline, exportc: "zwlr_output_mode_v1_send_preferred".} =
  ## Sends an preferred event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(ZwlrOutputModeV1Event_preferred.ord)

proc zwlrOutputModeV1SendFinished*(
    resource: ptr Resource
) {.inline, exportc: "zwlr_output_mode_v1_send_finished".} =
  ## Sends an finished event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(ZwlrOutputModeV1Event_finished.ord)

type ZwlrOutputConfigurationV1Interface* = object
  enableHead*: proc(
    client: ptr Client, resource: ptr Resource, id: uint32, head: ptr Resource
  ) {.nimcall.}
  disableHead*:
    proc(client: ptr Client, resource: ptr Resource, head: ptr Resource) {.nimcall.}
  apply*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  test*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}
  destroy*: proc(client: ptr Client, resource: ptr Resource) {.nimcall.}

proc zwlrOutputConfigurationV1SendSucceeded*(
    resource: ptr Resource
) {.inline, exportc: "zwlr_output_configuration_v1_send_succeeded".} =
  ## Sends an succeeded event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(ZwlrOutputConfigurationV1Event_succeeded.ord)

proc zwlrOutputConfigurationV1SendFailed*(
    resource: ptr Resource
) {.inline, exportc: "zwlr_output_configuration_v1_send_failed".} =
  ## Sends an failed event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(ZwlrOutputConfigurationV1Event_failed.ord)

proc zwlrOutputConfigurationV1SendCancelled*(
    resource: ptr Resource
) {.inline, exportc: "zwlr_output_configuration_v1_send_cancelled".} =
  ## Sends an cancelled event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(ZwlrOutputConfigurationV1Event_cancelled.ord)

type ZwlrOutputConfigurationHeadV1Interface* = object
  setMode*:
    proc(client: ptr Client, resource: ptr Resource, mode: ptr Resource) {.nimcall.}
  setCustomMode*: proc(
    client: ptr Client,
    resource: ptr Resource,
    width: int32,
    height: int32,
    refresh: int32,
  ) {.nimcall.}
  setPosition*:
    proc(client: ptr Client, resource: ptr Resource, x: int32, y: int32) {.nimcall.}
  setTransform*:
    proc(client: ptr Client, resource: ptr Resource, transform: int32) {.nimcall.}
  setScale*: proc(client: ptr Client, resource: ptr Resource, scale: Fixed) {.nimcall.}
  setAdaptiveSync*:
    proc(client: ptr Client, resource: ptr Resource, state: uint32) {.nimcall.}
