# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/client
import wayland/native/common
import code
export code

## The river_input_management_v1 CLIENT protocol
## #############################################
## 
## Interfaces
## ==========
## 
## * river_input_manager_v1
## * river_input_device_v1
## 
## Copyright
## =========
## 
## SPDX-FileCopyrightText: © 2025 Isaac Freund
## SPDX-License-Identifier: MIT
## 
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to
## deal in the Software without restriction, including without limitation the
## rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
## sell copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
## 
## The above copyright notice and this permission notice shall be included in
## all copies or substantial portions of the Software.
## 
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
## IN THE SOFTWARE.
## 

type RiverInputManagerV1Listener* = object
  finished*: proc(
    data: pointer;
    riverInputManagerV1: ptr RiverInputManagerV1;
  ) {.nimcall.}
  inputDevice*: proc(
    data: pointer;
    riverInputManagerV1: ptr RiverInputManagerV1;
    id: ptr RiverInputDeviceV1;
  ) {.nimcall.}
proc addListener*(riverInputManagerV1: ptr RiverInputManagerV1; listener: ptr RiverInputManagerV1Listener; data: pointer): int {.inline.} =
  cast[ptr Proxy](riverInputManagerV1).add_listener(listener, data)

proc setUserData*(riverInputManagerV1: ptr RiverInputManagerV1; userData: pointer) {.inline.} =
  cast[ptr Proxy](riverInputManagerV1).set_user_data(user_data)
proc getUserData*(riverInputManagerV1: ptr RiverInputManagerV1): pointer {.inline.} =
  cast[ptr Proxy](riverInputManagerV1).get_user_data()
proc getVersion*(riverInputManagerV1: ptr RiverInputManagerV1): uint32 {.inline.} =
  cast[ptr Proxy](riverInputManagerV1).get_version()
proc stop*(riverInputManagerV1: ptr RiverInputManagerV1) {.inline.} =
  ## stop sending events
  ## 
  ## This request indicates that the client no longer wishes to receive
  ## events on this object.
  ## 
  ## The Wayland protocol is asynchronous, which means the server may send
  ## further events until the stop request is processed. The client must wait
  ## for a river_input_manager_v1.finished event before destroying this
  ## object.
  ## 
  cast[ptr Proxy](riverInputManagerV1).marshal_flags(RiverInputManagerV1Request_stop.ord, nil, cast[ptr Proxy](riverInputManagerV1).get_version(), 0)
proc destroy*(riverInputManagerV1: ptr RiverInputManagerV1) {.inline.} =
  ## destroy the river_input_manager_v1 object
  ## 
  ## This request should be called after the finished event has been received
  ## to complete destruction of the object.
  ## 
  ## It is a protocol error to make this request before the finished event
  ## has been received.
  ## 
  ## If a client wishes to destroy this object it should send a
  ## river_input_manager_v1.stop request and wait for a
  ## river_input_manager_v1.finished event. Once the finished event is
  ## received it is safe to destroy this object and any other objects created
  ## through this interface.
  ## 
  cast[ptr Proxy](riverInputManagerV1).marshal_flags(RiverInputManagerV1Request_destroy.ord, nil, cast[ptr Proxy](riverInputManagerV1).get_version(), WL_MARSHAL_FLAG_DESTROY)
proc createSeat*(riverInputManagerV1: ptr RiverInputManagerV1; name: cstring) {.inline.} =
  ## create a new seat
  ## 
  ## Create a new seat with the given name. Has no effect if a seat with the
  ## given name already exists.
  ## 
  ## The default seat with name "default" always exists and does not need to
  ## be explicitly created.
  ## 
  cast[ptr Proxy](riverInputManagerV1).marshal_flags(RiverInputManagerV1Request_create_seat.ord, nil, cast[ptr Proxy](riverInputManagerV1).get_version(), 0, name)
proc destroySeat*(riverInputManagerV1: ptr RiverInputManagerV1; name: cstring) {.inline.} =
  ## destroy a seat
  ## 
  ## Destroy the seat with the given name. Has no effect if a seat with the
  ## given name does not exist.
  ## 
  ## The default seat with name "default" cannot be destroyed and attempting
  ## to destroy it will have no effect.
  ## 
  ## Any input devices assigned to the destroyed seat at the time of
  ## destruction are assigned to the default seat.
  ## 
  cast[ptr Proxy](riverInputManagerV1).marshal_flags(RiverInputManagerV1Request_destroy_seat.ord, nil, cast[ptr Proxy](riverInputManagerV1).get_version(), 0, name)
type RiverInputDeviceV1Listener* = object
  removed*: proc(
    data: pointer;
    riverInputDeviceV1: ptr RiverInputDeviceV1;
  ) {.nimcall.}
  `type`*: proc(
    data: pointer;
    riverInputDeviceV1: ptr RiverInputDeviceV1;
    `type`: uint32;
  ) {.nimcall.}
  name*: proc(
    data: pointer;
    riverInputDeviceV1: ptr RiverInputDeviceV1;
    name: cstring;
  ) {.nimcall.}
  done*: proc(
    data: pointer;
    riverInputDeviceV1: ptr RiverInputDeviceV1;
  ) {.nimcall.}
proc addListener*(riverInputDeviceV1: ptr RiverInputDeviceV1; listener: ptr RiverInputDeviceV1Listener; data: pointer): int {.inline.} =
  cast[ptr Proxy](riverInputDeviceV1).add_listener(listener, data)

proc setUserData*(riverInputDeviceV1: ptr RiverInputDeviceV1; userData: pointer) {.inline.} =
  cast[ptr Proxy](riverInputDeviceV1).set_user_data(user_data)
proc getUserData*(riverInputDeviceV1: ptr RiverInputDeviceV1): pointer {.inline.} =
  cast[ptr Proxy](riverInputDeviceV1).get_user_data()
proc getVersion*(riverInputDeviceV1: ptr RiverInputDeviceV1): uint32 {.inline.} =
  cast[ptr Proxy](riverInputDeviceV1).get_version()
proc destroy*(riverInputDeviceV1: ptr RiverInputDeviceV1) {.inline.} =
  ## destroy the input device object
  ## 
  ## This request indicates that the client will no longer use the input
  ## device object and that it may be safely destroyed.
  ## 
  cast[ptr Proxy](riverInputDeviceV1).marshal_flags(RiverInputDeviceV1Request_destroy.ord, nil, cast[ptr Proxy](riverInputDeviceV1).get_version(), WL_MARSHAL_FLAG_DESTROY)
proc assignToSeat*(riverInputDeviceV1: ptr RiverInputDeviceV1; name: cstring) {.inline.} =
  ## assign the input device to a seat
  ## 
  ## Assign the input device to a seat. All input devices not explicitly
  ## assigned to a seat are considered assigned to the default seat.
  ## 
  ## Has no effect if a seat with the given name does not exist.
  ## 
  cast[ptr Proxy](riverInputDeviceV1).marshal_flags(RiverInputDeviceV1Request_assign_to_seat.ord, nil, cast[ptr Proxy](riverInputDeviceV1).get_version(), 0, name)
proc setRepeatInfo*(riverInputDeviceV1: ptr RiverInputDeviceV1; rate: int32; delay: int32) {.inline.} =
  ## set keyboard repeat rate and delay
  ## 
  ## Set repeat rate and delay for a keyboard input device. Has no effect if
  ## the device is not a keyboard.
  ## 
  ## Negative values for either rate or delay are illegal. A rate of zero
  ## will disable any repeating (regardless of the value of delay).
  ## 
  cast[ptr Proxy](riverInputDeviceV1).marshal_flags(RiverInputDeviceV1Request_set_repeat_info.ord, nil, cast[ptr Proxy](riverInputDeviceV1).get_version(), 0, rate, delay)
proc setScrollFactor*(riverInputDeviceV1: ptr RiverInputDeviceV1; factor: Fixed) {.inline.} =
  ## set scroll factor
  ## 
  ## Set the scroll factor for a pointer input device. Has no effect if the
  ## device is not a pointer.
  ## 
  ## For example, a factor of 0.5 will make scrolling twice as slow while a
  ## factor of 3.0 will make scrolling 3 times as fast.
  ## 
  ## Setting a scroll factor less than 0 is a protocol error.
  ## 
  cast[ptr Proxy](riverInputDeviceV1).marshal_flags(RiverInputDeviceV1Request_set_scroll_factor.ord, nil, cast[ptr Proxy](riverInputDeviceV1).get_version(), 0, factor)
proc mapToOutput*(riverInputDeviceV1: ptr RiverInputDeviceV1; output: ptr Output) {.inline.} =
  ## map input device to the given output
  ## 
  ## Map the input device to the given output. Has no effect if the device is
  ## not a pointer, touch, or tablet device.
  ## 
  ## If mapped to both an output and a rectangle, the rectangle has priority.
  ## 
  ## Passing null clears an existing mapping.
  ## 
  cast[ptr Proxy](riverInputDeviceV1).marshal_flags(RiverInputDeviceV1Request_map_to_output.ord, nil, cast[ptr Proxy](riverInputDeviceV1).get_version(), 0, output)
proc mapToRectangle*(riverInputDeviceV1: ptr RiverInputDeviceV1; x: int32; y: int32; width: int32; height: int32) {.inline.} =
  ## map input device to the given rectangle
  ## 
  ## Map the input device to the given rectangle in the global compositor
  ## coordinate space. Has no effect if the device is not a pointer, touch,
  ## or tablet device.
  ## 
  ## If mapped to both an output and a rectangle, the rectangle has priority.
  ## 
  ## Width and height must be greater than or equal to 0.
  ## 
  ## Passing 0 for width or height clears an existing mapping.
  ## 
  cast[ptr Proxy](riverInputDeviceV1).marshal_flags(RiverInputDeviceV1Request_map_to_rectangle.ord, nil, cast[ptr Proxy](riverInputDeviceV1).get_version(), 0, x, y, width, height)
