# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code

var riverInputManagementV1_types: array[6, ptr Interface]
type RiverInputDeviceV1* = object
type RiverInputManagerV1* = object

let
  river_input_manager_v1_requests {.exportc.} = [
    Message(name: "stop", signature: "", types: addr river_input_management_v1_types[0]),
    Message(name: "destroy", signature: "", types: addr river_input_management_v1_types[0]),
    Message(name: "create_seat", signature: "s", types: addr river_input_management_v1_types[0]),
    Message(name: "destroy_seat", signature: "s", types: addr river_input_management_v1_types[0]),
  ]

  river_input_manager_v1_events {.exportc.} = [
    Message(name: "finished", signature: "", types: addr river_input_management_v1_types[0]),
    Message(name: "input_device", signature: "n", types: addr river_input_management_v1_types[4]),
  ]

  river_input_manager_v1_interface* {.exportc.} = Interface(
    name: "river_input_manager_v1",
    version: 2,
    method_count: 4,
    methods: addr river_input_manager_v1_requests[0],
    event_count: 2,
    events: addr river_input_manager_v1_events[0],
  )

  river_input_device_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr river_input_management_v1_types[0]),
    Message(name: "assign_to_seat", signature: "s", types: addr river_input_management_v1_types[0]),
    Message(name: "set_repeat_info", signature: "ii", types: addr river_input_management_v1_types[0]),
    Message(name: "set_scroll_factor", signature: "f", types: addr river_input_management_v1_types[0]),
    Message(name: "map_to_output", signature: "?o", types: addr river_input_management_v1_types[5]),
    Message(name: "map_to_rectangle", signature: "iiii", types: addr river_input_management_v1_types[0]),
  ]

  river_input_device_v1_events {.exportc.} = [
    Message(name: "removed", signature: "", types: addr river_input_management_v1_types[0]),
    Message(name: "type", signature: "u", types: addr river_input_management_v1_types[0]),
    Message(name: "name", signature: "s", types: addr river_input_management_v1_types[0]),
    Message(name: "done", signature: "2", types: addr river_input_management_v1_types[0]),
  ]

  river_input_device_v1_interface* {.exportc.} = Interface(
    name: "river_input_device_v1",
    version: 2,
    method_count: 6,
    methods: addr river_input_device_v1_requests[0],
    event_count: 4,
    events: addr river_input_device_v1_events[0],
  )


type RiverInputManagerV1Error* {.size: sizeof(uint32).} = enum
  error_invalid_destroy = 0
func since*(e: RiverInputManagerV1Error): int =
  case e
  of error_invalid_destroy: 1
proc isValid*(e: RiverInputManagerV1Error; version: int): bool =
  version >= e.since

type RiverInputDeviceV1Error* {.size: sizeof(uint32).} = enum
  error_invalid_repeat_info = 0
  error_invalid_scroll_factor = 1
  error_invalid_map_to_rectangle = 2
func since*(e: RiverInputDeviceV1Error): int =
  case e
  of error_invalid_repeat_info: 1
  of error_invalid_scroll_factor: 1
  of error_invalid_map_to_rectangle: 1
proc isValid*(e: RiverInputDeviceV1Error; version: int): bool =
  version >= e.since

type RiverInputDeviceV1Type* {.size: sizeof(uint32).} = enum
  type_keyboard = 0
  type_pointer = 1
  type_touch = 2
  type_tablet = 3
func since*(e: RiverInputDeviceV1Type): int =
  case e
  of type_keyboard: 1
  of type_pointer: 1
  of type_touch: 1
  of type_tablet: 1
proc isValid*(e: RiverInputDeviceV1Type; version: int): bool =
  version >= e.since

type RiverInputManagerV1Event* {.size: sizeof(uint32).} = enum
  RiverInputManagerV1Event_finished
  RiverInputManagerV1Event_input_device
proc since*(e: RiverInputManagerV1Event): int =
  case e
  of RiverInputManagerV1Event_finished: 1
  of RiverInputManagerV1Event_input_device: 1

type RiverInputManagerV1Request* {.size: sizeof(uint32).} = enum
  RiverInputManagerV1Request_stop
  RiverInputManagerV1Request_destroy
  RiverInputManagerV1Request_create_seat
  RiverInputManagerV1Request_destroy_seat
proc since*(e: RiverInputManagerV1Request): int =
  case e
  of RiverInputManagerV1Request_stop: 1
  of RiverInputManagerV1Request_destroy: 1
  of RiverInputManagerV1Request_create_seat: 1
  of RiverInputManagerV1Request_destroy_seat: 1

type RiverInputDeviceV1Event* {.size: sizeof(uint32).} = enum
  RiverInputDeviceV1Event_removed
  RiverInputDeviceV1Event_type
  RiverInputDeviceV1Event_name
  RiverInputDeviceV1Event_done
proc since*(e: RiverInputDeviceV1Event): int =
  case e
  of RiverInputDeviceV1Event_removed: 1
  of RiverInputDeviceV1Event_type: 1
  of RiverInputDeviceV1Event_name: 1
  of RiverInputDeviceV1Event_done: 2

type RiverInputDeviceV1Request* {.size: sizeof(uint32).} = enum
  RiverInputDeviceV1Request_destroy
  RiverInputDeviceV1Request_assign_to_seat
  RiverInputDeviceV1Request_set_repeat_info
  RiverInputDeviceV1Request_set_scroll_factor
  RiverInputDeviceV1Request_map_to_output
  RiverInputDeviceV1Request_map_to_rectangle
proc since*(e: RiverInputDeviceV1Request): int =
  case e
  of RiverInputDeviceV1Request_destroy: 1
  of RiverInputDeviceV1Request_assign_to_seat: 1
  of RiverInputDeviceV1Request_set_repeat_info: 1
  of RiverInputDeviceV1Request_set_scroll_factor: 1
  of RiverInputDeviceV1Request_map_to_output: 1
  of RiverInputDeviceV1Request_map_to_rectangle: 1

riverInputManagementV1_types = [
  nil,
  nil,
  nil,
  nil,
  addr river_input_device_v1_interface,
  addr wl_output_interface,
]


