# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/server
import wayland/native/common
import code
export code

## The river_input_management_v1 SERVER protocol
## #############################################
## 
## Interfaces
## ==========
## 
## * river_input_manager_v1
## * river_input_device_v1
## 
## Copyright
## =========
## 
## SPDX-FileCopyrightText: © 2025 Isaac Freund
## SPDX-License-Identifier: MIT
## 
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to
## deal in the Software without restriction, including without limitation the
## rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
## sell copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
## 
## The above copyright notice and this permission notice shall be included in
## all copies or substantial portions of the Software.
## 
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
## IN THE SOFTWARE.
## 

type RiverInputManagerV1Interface* = object
  stop*: proc(
    client: ptr Client;
    resource: ptr Resource;
  ) {.nimcall.}
  destroy*: proc(
    client: ptr Client;
    resource: ptr Resource;
  ) {.nimcall.}
  createSeat*: proc(
    client: ptr Client;
    resource: ptr Resource;
    name: cstring;
  ) {.nimcall.}
  destroySeat*: proc(
    client: ptr Client;
    resource: ptr Resource;
    name: cstring;
  ) {.nimcall.}

proc riverInputManagerV1SendFinished*(resource: ptr Resource) {.inline, exportc: "river_input_manager_v1_send_finished".} =
  ## Sends an finished event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverInputManagerV1Event_finished.ord)

proc riverInputManagerV1SendInputDevice*(resource: ptr Resource; id: ptr Resource) {.inline, exportc: "river_input_manager_v1_send_input_device".} =
  ## Sends an input_device event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverInputManagerV1Event_input_device.ord, id)

type RiverInputDeviceV1Interface* = object
  destroy*: proc(
    client: ptr Client;
    resource: ptr Resource;
  ) {.nimcall.}
  assignToSeat*: proc(
    client: ptr Client;
    resource: ptr Resource;
    name: cstring;
  ) {.nimcall.}
  setRepeatInfo*: proc(
    client: ptr Client;
    resource: ptr Resource;
    rate: int32;
    delay: int32;
  ) {.nimcall.}
  setScrollFactor*: proc(
    client: ptr Client;
    resource: ptr Resource;
    factor: Fixed;
  ) {.nimcall.}
  mapToOutput*: proc(
    client: ptr Client;
    resource: ptr Resource;
    output: ptr Resource;
  ) {.nimcall.}
  mapToRectangle*: proc(
    client: ptr Client;
    resource: ptr Resource;
    x: int32;
    y: int32;
    width: int32;
    height: int32;
  ) {.nimcall.}

proc riverInputDeviceV1SendRemoved*(resource: ptr Resource) {.inline, exportc: "river_input_device_v1_send_removed".} =
  ## Sends an removed event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverInputDeviceV1Event_removed.ord)

proc riverInputDeviceV1SendType*(resource: ptr Resource; `type`: uint32) {.inline, exportc: "river_input_device_v1_send_type".} =
  ## Sends an type event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverInputDeviceV1Event_type.ord, `type`)

proc riverInputDeviceV1SendName*(resource: ptr Resource; name: cstring) {.inline, exportc: "river_input_device_v1_send_name".} =
  ## Sends an name event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverInputDeviceV1Event_name.ord, name)

proc riverInputDeviceV1SendDone*(resource: ptr Resource) {.inline, exportc: "river_input_device_v1_send_done".} =
  ## Sends an done event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(RiverInputDeviceV1Event_done.ord)

